<script lang="ts">
  import type { RecoveryForm } from "../persistence/recovery";
  import { CATALOG, evaluateWorkspace, createAction, closeAction, addDecision, reviewNeeded, type Finding, type Workspace } from "@rgpdesk/privacy-core";
  import { untrack, tick } from "svelte";
  import { questionPlaybook } from "../guidance";
  import Icon from "./Icon.svelte";
  import CollectionRequests from "./CollectionRequests.svelte";
  import Emblem from "./Emblem.svelte";
  let { workspace, busy, initialActivityId = "", onSave, onLeave, tab=$bindable<"actions"|"requests">("actions") }: { tab?:"actions"|"requests"; onLeave:(action:()=>void)=>void; workspace: Workspace; busy: boolean; initialActivityId?: string; onSave: (next: Workspace) => Promise<void> } = $props();
  let scope = $state(untrack(() => initialActivityId)); let ownerFilter = $state(""); let dueFilter = $state(""); let ruleFilter = $state("");
  let selected: Finding | null = $state(null); let owner = $state(""); let due = $state(""); let closing = $state(""); let author = $state(""); let justification = $state("");
  let showDecision = $state(false); let decisionRule = $state("R-009"); let decisionActivity = $state(""); let conclusion = $state("");
  const now = () => new Date().toISOString();
  let findings = $derived(evaluateWorkspace(workspace, now().slice(0, 10)));
  let visible = $derived(findings.filter((f) => (!scope || f.activityId === scope) && (!ruleFilter || f.ruleId === ruleFilter)));
  let actions = $derived(workspace.actions.filter((a) => (!scope || a.activityId === scope) && (!ownerFilter || a.owner.toLocaleLowerCase().includes(ownerFilter.toLocaleLowerCase())) && (!dueFilter || a.due !== null && a.due <= dueFilter)));
  let requests:CollectionRequests|undefined=$state();
  function switchTab(value:typeof tab){onLeave(()=>{selected=null;closing="";showDecision=false;tab=value;});}
  export function hasUnsavedChanges(){if(tab==="requests")return !!requests?.getRecovery();return !!(selected||closing||showDecision);}
  export function getRecovery():RecoveryForm|null{if(tab==="requests")return requests?.getRecovery()??null;return hasUnsavedChanges()?{kind:'actions',selectedKey:selected?.key??'',owner,due,closing,author,justification,showDecision,decisionRule,decisionActivity,conclusion}:null;}
  export async function restoreRecovery(f:RecoveryForm){if(f.kind==='request-prepare'||f.kind==='request-reply'){tab='requests';await tick();await requests?.restoreRecovery(f);return;}if(f.kind!=='actions')return;selected=findings.find(x=>x.key===f.selectedKey)??null;owner=f.owner;due=f.due;closing=f.closing;author=f.author;justification=f.justification;showDecision=f.showDecision;decisionRule=f.decisionRule;decisionActivity=f.decisionActivity;conclusion=f.conclusion;}
</script>
<nav class="section-tabs" aria-label="Suivi de la mission"><button class:active={tab==='actions'} aria-pressed={tab==='actions'} onclick={()=>switchTab('actions')}>Actions et décisions</button><button class:active={tab==='requests'} aria-pressed={tab==='requests'} onclick={()=>switchTab('requests')}>Demandes aux métiers <span class="count">{workspace.collections?.length??0}</span></button></nav>
{#if tab==='requests'}<CollectionRequests bind:this={requests} {workspace} {busy} {onSave} {onLeave}/>{:else}
<section class="panel">
  <div class="section-heading"><div><p class="eyebrow">Suivi documentaire</p><h2>Chaque question trouve sa suite.</h2></div><Emblem name="actions" /></div>
  <p class="help">Choisissez une question à clarifier, identifiez la personne qui peut y répondre et fixez votre prochaine étape. Une action clôturée reste dans l’historique.</p>
  <div class="filters"><label class="field">Périmètre<select aria-label="Périmètre" bind:value={scope}><option value="">Toutes les activités</option>{#each workspace.activities as a}<option value={a.id}>{a.title}</option>{/each}</select></label><label class="field">Information manquante<select aria-label="Information manquante" bind:value={ruleFilter}><option value="">Tous les contrôles</option>{#each CATALOG.filter((r) => r.id !== "R-010") as r}<option value={r.id}>{r.title}</option>{/each}</select></label></div>
  <div class="interview-card"><strong>Par exemple, la conservation n’est pas précisée</strong><p>Créez une action pour retrouver la règle applicable avec l’équipe concernée. Quand la réponse est établie, complétez la fiche puis consignez la clôture et sa justification.</p></div><h3>Questions ouvertes <span class="count">{visible.length}</span></h3>
  <ul class="finding-list">{#each visible as f (f.key)}<li><span class="finding-marker"><Icon name="eye" size={18} /></span><div class="grow"><strong>{CATALOG.find((r) => r.id === f.ruleId)?.title}</strong><p>{workspace.activities.find((a) => a.id === f.activityId)?.title ?? "Organisation"} · {f.message}</p>{#if questionPlaybook[f.ruleId]}<details class="question-prompt"><summary>Préparer l’échange</summary><p><strong>À demander</strong><br />{questionPlaybook[f.ruleId].ask}</p><p><strong>Avec qui</strong><br />{questionPlaybook[f.ruleId].who}</p><p><strong>À retrouver</strong><br />{questionPlaybook[f.ruleId].find}</p><p class="help">Question d’entretien proposée par RGPDESK. <a href={CATALOG.find((r) => r.id === f.ruleId)?.source} target="_blank" rel="noopener noreferrer">Consulter la référence CNIL associée</a>.</p></details>{/if}</div>{#if workspace.actions.some((a) => a.findingKey === f.key)}<span class="tag">Action déjà suivie</span>{:else}<button class="secondary" disabled={busy} onclick={() => { selected = f; owner = ""; due = ""; }}>Créer une action</button>{/if}</li>{/each}</ul>
  {#if selected}<form class="subpanel" onsubmit={(e) => { e.preventDefault(); if (selected) void onSave(createAction(workspace, selected, { id: crypto.randomUUID(), owner, due: due || null }, now())); }}><fieldset disabled={busy}><h3>Nouvelle action · {CATALOG.find((r) => r.id === selected!.ruleId)?.title}</h3>{#if questionPlaybook[selected.ruleId]}<p>{questionPlaybook[selected.ruleId].ask}</p><p class="help">À retrouver : {questionPlaybook[selected.ruleId].find}</p>{/if}<div class="grid-two"><label class="field">Responsable de l’action<input required maxlength="160" bind:value={owner} /></label><label class="field">Échéance déclarée<input type="date" bind:value={due} /></label></div><button type="submit">Enregistrer l’action</button><button type="button" class="secondary" onclick={() => selected = null}>Annuler l’action</button></fieldset></form>{/if}
  <div class="section-heading"><h3>Plan d’actions</h3><span class="tag">{workspace.actions.filter((a) => !a.closure).length} en cours</span></div>
  <div class="filters"><label class="field">Filtrer par responsable<input maxlength="160" bind:value={ownerFilter} placeholder="Responsable de l’action" /></label><label class="field">Échéance au plus tard<input type="date" bind:value={dueFilter} /></label></div>
  <ul class="records">{#each actions as a}<li><span class="record-icon"><Icon name={a.closure ? "check" : "clock"} /></span><div class="grow"><strong>{CATALOG.find((r) => r.id === a.ruleId)?.title} · {a.scope}</strong><p>{a.owner} · {a.due ?? "Sans échéance"} · {a.closure ? "Clôture déclarée" : "En cours"}{reviewNeeded(a, workspace) ? " · À revoir après une évolution du dossier" : ""}</p>{#if a.closure}<p>{a.closure.at} · {a.closure.author} : {a.closure.justification}</p>{/if}</div>{#if !a.closure}<button class="secondary" disabled={busy} onclick={() => { closing = a.id; author = ""; justification = ""; }}>Clôturer</button>{/if}</li>{/each}</ul>
  {#if closing}<form class="subpanel" onsubmit={(e) => { e.preventDefault(); void onSave(closeAction(workspace, closing, author, justification, now())); }}><fieldset disabled={busy}><h3>Conserver la justification de clôture</h3><label class="field">Auteur déclaré de la clôture<input required maxlength="160" bind:value={author} /></label><label class="field">Justification de clôture<textarea required maxlength="4000" bind:value={justification}></textarea></label><p class="help">Cette déclaration ne prouve pas l’exécution dans vos systèmes. La clôture sera conservée sans réécriture.</p><button>Enregistrer la clôture</button><button type="button" class="secondary" onclick={() => closing = ""}>Annuler la clôture</button></fieldset></form>{/if}
  <div class="section-heading"><h3>Décisions motivées</h3><button class="secondary" disabled={busy} onclick={() => { showDecision = !showDecision; author = ""; justification = ""; conclusion = ""; }}>Documenter une décision</button></div>
  {#if showDecision}<form class="subpanel" onsubmit={(e) => { e.preventDefault(); void onSave(addDecision(workspace, { id: crypto.randomUUID(), ruleId: decisionRule, activityId: decisionActivity || null, author, justification, conclusion }, now())); }}><fieldset disabled={busy}>
    <div class="grid-two"><label class="field">Question examinée<select aria-label="Question examinée" bind:value={decisionRule}>{#each CATALOG.filter((r) => r.id !== "R-010") as r}<option value={r.id}>{r.title}</option>{/each}</select></label><label class="field">Périmètre de la décision<select aria-label="Périmètre de la décision" bind:value={decisionActivity}><option value="">Organisation</option>{#each workspace.activities as a}<option value={a.id}>{a.title}</option>{/each}</select></label></div>
    <label class="field">Auteur déclaré de la décision<input required maxlength="160" bind:value={author} /></label><label class="field">Décision déclarée<textarea required maxlength="4000" bind:value={conclusion}></textarea></label><label class="field">Motivation de la décision<textarea required maxlength="4000" bind:value={justification}></textarea></label><button>Conserver la décision</button>
  </fieldset></form>{/if}
  {#each workspace.decisions as d}<article class="subpanel"><span class="tag">{reviewNeeded(d, workspace) ? "À réexaminer" : "Déclaration sur cette révision"}</span><h4>{d.conclusion}</h4><p>{d.justification}</p><small>{d.author} · {d.createdAt} · révision {d.revision}</small></article>{/each}
  <details class="subpanel"><summary>Comprendre les questions et leurs sources</summary><p class="help">Ces repères vous aident à examiner votre dossier. Ils ne remplacent pas l’analyse de votre situation ni des règles propres à votre secteur. Consultez les textes pour motiver vos choix et revoyez-les lorsque le traitement évolue.</p>{#each CATALOG as rule}<article><h4>{rule.id} · {rule.title}</h4><p>{rule.explanation}</p><p class="help">Informations à réunir : {rule.facts}.</p><a href={rule.source} target="_blank" rel="noreferrer noopener">Source CNIL · articles {rule.article}</a></article>{/each}</details>
</section>

{/if}
