<script lang="ts">
  import { onMount } from "svelte";
  let heading:HTMLHeadingElement;
  onMount(()=>{heading?.focus({preventScroll:true});heading?.closest('.reader-cover')?.scrollIntoView({block:"start"});});
  import { knowledgeText, resolvedFlows, evaluateWorkspace, CATALOG, type Activity, type Workspace } from "@rgpdesk/privacy-core";
  import FlowMap from "./FlowMap.svelte";
  import Icon from "./Icon.svelte";
  import Emblem from "./Emblem.svelte";
  let { activity, workspace, busy, onEdit, onClose, onDocument, onQuestions }: {activity:Activity;workspace:Workspace;busy:boolean;onEdit:(section:"record"|"flows"|"evidence"|"analysis",step?:number)=>void;onClose:()=>void;onDocument:(id:string)=>void;onQuestions:()=>void}=$props();
  let questions=$derived(evaluateWorkspace(workspace,new Date().toISOString().slice(0,10)).filter(f=>f.activityId===activity.id));
  let documents=$derived(workspace.documents.filter(d=>d.activityIds.includes(activity.id)));
  const text=knowledgeText;
</script>
<article class="panel activity-reader" aria-label="Lecture de l’activité">
  <header class="reader-cover"><Emblem name="register"/><div><p class="eyebrow">Fiche de lecture · {activity.role==='controller'?'Responsable de traitement':'Sous-traitant'}</p><h2 bind:this={heading} tabindex="-1">{activity.title}</h2><p>{activity.status==='archived'?'Activité archivée':activity.status==='draft'?'Fiche en cours de documentation':'Activité déclarée active'}. Les informations ci-dessous sont vos déclarations enregistrées.</p></div></header>
  <div class="draft-toolbar"><span><Icon name="eye"/> Lecture du dossier enregistré</span><div class="actions"><button class="secondary" disabled={busy} onclick={()=>onEdit('record')}>Modifier la fiche</button><button class="secondary" onclick={onClose}>Revenir au registre</button></div></div>
  <section class="reader-section"><div class="section-heading"><h3>Pourquoi ce traitement ?</h3><button class="text-button" disabled={busy} onclick={()=>onEdit('record',1)}>Modifier les objectifs</button></div>
  {#if activity.role==='controller'}{#each activity.purposes as p}<div class="reader-purpose"><strong>{text(p.description)||'Finalité à préciser'}</strong><dl class="reader-facts"><div><dt>Fondement juridique déclaré</dt><dd>{text(p.legalBasis)||'À examiner'}</dd></div><div><dt>Conservation déclarée</dt><dd>{text(p.retention.period)||'À examiner'}</dd></div><div><dt>Départ de la conservation</dt><dd>{text(p.retention.trigger)||'À préciser'}</dd></div></dl></div>{/each}{#if !activity.purposes.length}<p>Aucune finalité renseignée.</p>{/if}{:else}<dl class="reader-facts"><div><dt>Opérations confiées</dt><dd>{text(activity.operations)||'À préciser'}</dd></div><div><dt>Instructions</dt><dd>{text(activity.instructions)||'À retrouver'}</dd></div><div><dt>Clients responsables</dt><dd>{workspace.parties.filter(p=>activity.controllerIds.includes(p.id)).map(p=>p.name).join(', ')||'À identifier'}</dd></div></dl>{/if}</section>
  <section class="reader-section"><div class="section-heading"><h3>Les personnes et les données</h3><button class="text-button" disabled={busy} onclick={()=>onEdit('record',2)}>Modifier les données</button></div><div class="reader-cards">{#each [["parties","Personnes concernées",activity.dataSubjects],["documents","Données utilisées",activity.dataCategories],["transfer","Destinataires",activity.recipients]] as [icon,label,value]}<div><Icon name={String(icon)} size={28}/><h4>{label}</h4><p>{text(value as Activity['dataSubjects'])||'À documenter'}</p></div>{/each}</div></section>
  <section class="reader-section"><div class="section-heading"><h3>Le parcours des données</h3><button class="text-button" disabled={busy} onclick={()=>onEdit('flows')}>Modifier les flux</button></div>{#if activity.flows.length}<FlowMap flows={resolvedFlows(activity,workspace)}/>{:else}<p>Aucun mouvement décrit. Le schéma apparaîtra à partir des flux que vous renseignerez.</p>{/if}</section>
  <section class="reader-section"><div class="section-heading"><h3>Les protections et les moyens</h3><button class="text-button" disabled={busy} onclick={()=>onEdit('record',3)}>Modifier les protections</button></div><dl class="reader-facts"><div><dt>Mesures déclarées</dt><dd>{text(activity.securityMeasures)||'À documenter'}</dd></div><div><dt>Transferts déclarés</dt><dd>{text(activity.transfers)||'À examiner'}</dd></div><div><dt>Systèmes liés</dt><dd>{workspace.systems.filter(s=>activity.systemIds.includes(s.id)).map(s=>s.name).join(', ')||'Aucun système relié'}</dd></div><div><dt>Intervenants liés</dt><dd>{workspace.parties.filter(p=>activity.participantIds.includes(p.id)||activity.review.subcontractorIds.includes(p.id)).map(p=>p.name).join(', ')||'Aucun intervenant relié'}</dd></div></dl><button class="text-button" disabled={busy} onclick={()=>onEdit('record',4)}>Modifier les moyens et relations</button></section>
  <section class="reader-section"><div class="section-heading"><h3>Les justificatifs reliés</h3><button class="text-button" disabled={busy} onclick={()=>onEdit('evidence')}>Modifier les liens documentaires</button></div><ul class="records">{#each documents as d}<li><Icon name="evidence"/><span class="grow"><strong>{d.title}</strong><p>{d.version||'Version à préciser'} · {d.internalRef||'Localisation à renseigner'}</p></span><button class="secondary" disabled={busy} onclick={()=>onDocument(d.id)}>Examiner la référence</button></li>{/each}</ul>{#if !documents.length}<p>Aucune référence reliée à cette activité.</p>{/if}</section>
  <section class="reader-section"><div class="section-heading"><h3>Les questions encore ouvertes</h3><button class="text-button" disabled={busy} onclick={onQuestions}>Préparer les demandes</button></div><ul>{#each questions as q}<li>{CATALOG.find(r=>r.id===q.ruleId)?.title} : {q.message}</li>{/each}{#each activity.interviewQuestions??[] as q}<li>{q}</li>{/each}</ul><p class="help">Ces repères portent sur la documentation, sans score ni conclusion de conformité.</p><button class="secondary" disabled={busy} onclick={()=>onEdit('analysis')}>Examiner les arguments de l’analyse</button></section>
</article>
