<script lang="ts">
 import {untrack,tick} from 'svelte';
 import {previewCorrectiveAction,correctiveVersion,CORRECTION_PRIORITIES,correctionFields,newCorrectionChange,correctionValueText,correctiveConflicts,correctiveReexamination,sortCorrectiveActions,prepareCorrectiveAction,completeCorrectiveAction,abandonCorrectiveAction,knowledge,unknown,PrivacyError,type Workspace,type CorrectiveDraft,type DocumentaryAction,type CorrectionValue} from '@rgpdesk/privacy-core';
 import type {RecoveryForm} from '../persistence/recovery';
 import Icon from './Icon.svelte';
 import Emblem from './Emblem.svelte';
 import CorrectiveSnapshot from './CorrectiveSnapshot.svelte';
 let {workspace,busy,initialActivityId='',onSave,onLeave,onRegister,onShare,onDocument}:{workspace:Workspace;busy:boolean;initialActivityId?:string;onSave:(w:Workspace)=>Promise<void>;onLeave:(next:()=>void)=>void;onRegister:(id:string)=>void;onShare:(id:string)=>void;onDocument:(id:string)=>void}=$props();
 let scope=$state(untrack(()=>initialActivityId)),priorityFilter=$state(''),visible=$state(8),draft:CorrectiveDraft|null=$state(null),selectedField=$state(''),error=$state(''),confirmed=$state(false),formHeading=$state<HTMLHeadingElement>();
 let selectedAction=$derived(workspace.actions.find(a=>a.id===draft?.actionId));
 let activity=$derived(workspace.activities.find(a=>a.id===draft?.activityId));
 let catalogue=$derived(activity?correctionFields(activity,workspace):[]);
 let items=$derived(sortCorrectiveActions(workspace.actions.filter(a=>a.corrective&&(!scope||a.activityId===scope)&&(!priorityFilter||a.corrective.priority===priorityFilter))));
 let documents=$derived(workspace.documents.filter(d=>d.activityIds.includes(draft?.activityId??'')));
 let conflicts=$derived(selectedAction?correctiveConflicts(workspace,selectedAction):[]);
 let preview=$derived.by(()=>{if(draft?.mode!=='complete'||!selectedAction||conflicts.length)return null;try{return previewCorrectiveAction(workspace,selectedAction.id);}catch{return null;}});
 const now=()=>new Date().toISOString();
 const copy=<T,>(v:T):T=>structuredClone($state.snapshot(v)) as T;
 const empty=(id:string):CorrectiveDraft=>({kind:'corrective',mode:'prepare',actionId:'',activityId:id,title:'',priority:'',reason:'',owner:'',due:'',dependsOn:[],changes:[],author:'',justification:'',evidence:[]});
 export function discard(){draft=null;confirmed=false;error='';}
 export async function start(id:string){draft=empty(id);error='';confirmed=false;await tick();formHeading?.focus();formHeading?.scrollIntoView({block:'start'});}
 export function getRecovery():RecoveryForm|null{return draft?copy(draft):null;}
 export async function restoreRecovery(f:RecoveryForm){if(f.kind==='corrective'){draft=copy(f);confirmed=false;error='';await tick();formHeading?.focus();}}
 async function open(a:DocumentaryAction,mode:CorrectiveDraft['mode']){const p=a.corrective!;draft={...empty(a.activityId!),actionId:a.id,mode,title:p.title,priority:p.priority,reason:p.reason,owner:a.owner,due:a.due??'',dependsOn:[...p.dependsOn],changes:copy(p.changes)};confirmed=false;error='';await tick();formHeading?.focus();formHeading?.scrollIntoView({block:'start'});}
 function changeValue(i:number,value:CorrectionValue){if(draft){draft.changes[i]!.after=value;confirmed=false;}}
 function selectEvidence(id:string,checked:boolean){if(!draft)return;const d=documents.find(d=>d.id===id);if(!d)return;draft.evidence=checked?[...draft.evidence,{documentId:id,version:d.version,locator:'',meaning:''}]:draft.evidence.filter(e=>e.documentId!==id);confirmed=false;}
 function refresh(i:number){if(!draft)return;const c=draft.changes[i]!,f=catalogue.find(f=>f.key===c.key);if(f)draft.changes[i]={...newCorrectionChange(f),after:copy(c.after)};confirmed=false;}
 function readable(v:CorrectionValue,key:string){return correctionValueText(v,catalogue.find(f=>f.key===key)?.options);}
 async function save(){if(!draft)return;error='';try{const d=copy(draft);let next:Workspace;
  if(d.mode==='prepare'){if(!d.priority)throw new PrivacyError('INVALID');next=prepareCorrectiveAction(workspace,{id:d.actionId||crypto.randomUUID(),activityId:d.activityId,title:d.title,priority:d.priority,reason:d.reason,owner:d.owner,due:d.due||null,dependsOn:d.dependsOn,changes:d.changes},workspace.revision,now());}
  else {if(!confirmed)throw new PrivacyError('INVALID');next=d.mode==='complete'?completeCorrectiveAction(workspace,d.actionId,{author:d.author,justification:d.justification,evidence:d.evidence},workspace.revision,now()):abandonCorrectiveAction(workspace,d.actionId,d.author,d.justification,workspace.revision,now());}
  await onSave(next);
 }catch(e){error=e instanceof PrivacyError&&e.code==='CONFLICT'?'Application bloquée : les faits, une preuve ou une dépendance ont changé. Reprenez le correctif et relisez son état de départ.':e instanceof PrivacyError&&e.code==='LIMIT'?'La limite du coffre serait dépassée. Rien n’a été appliqué.':'Enregistrement refusé. Vérifiez les champs, les changements réels et les références sélectionnées. Rien n’a été appliqué.';}}
</script>
<section class="panel corrective-plan" aria-label="Plan de corrections">
 <header class="corrective-cover"><Emblem name="actions"/><div><p class="eyebrow">Du constat au registre actualisé</p><h2>Une action. Un changement traçable.</h2><p>Préparez le correctif sur les faits déjà saisis. Quand sa réalisation est documentée, confirmez l’avant/après : la description, les flux et votre prochain registre reprennent ces mêmes faits.</p></div><button type="button" disabled={busy||!!draft} onclick={()=>onLeave(()=>{void start(scope);})}>Préparer un correctif <Icon name="plus"/></button></header>
 <div class="corrective-metrics" role="group" aria-label="Avancement du plan"><span><strong>{items.filter(a=>!a.closure).length}</strong> à réaliser</span><span><strong>{items.filter(a=>a.corrective?.application).length}</strong> appliqués au registre</span><span><strong>{items.filter(a=>a.closure&&!a.corrective?.application).length}</strong> abandonnés avec motif</span></div>
 {#if !draft}<div class="filters"><label class="field">Ensemble concerné<select bind:value={scope}><option value="">Tous les ensembles</option>{#each workspace.activities as a}<option value={a.id}>{a.title}</option>{/each}</select></label><label class="field">Priorité du plan<select bind:value={priorityFilter}><option value="">Toutes les priorités</option>{#each Object.entries(CORRECTION_PRIORITIES) as [id,label]}<option value={id}>{label}</option>{/each}</select></label></div>{/if}
 {#if draft}<form class="corrective-form" onsubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy}>
  <h3 tabindex="-1" bind:this={formHeading} data-draft-heading>{draft.mode==='prepare'?'Préparer le changement':draft.mode==='complete'?'C’est fait : documenter et appliquer':'Abandonner sans modifier le registre'}</h3>
  {#if error}<p class="notice error" role="alert">{error}</p>{/if}
  {#if draft.mode==='prepare'}
   <label class="field">Ensemble à corriger<select required disabled={!!draft.actionId} value={draft.activityId} onchange={e=>{if(draft){draft.activityId=e.currentTarget.value;draft.changes=[];selectedField='';}}}><option value="">Choisir un ensemble</option>{#each workspace.activities as a}<option value={a.id}>{a.title}</option>{/each}</select></label>
   <label class="field">Correctif attendu<input required maxlength="160" bind:value={draft.title} placeholder="Ex. Restreindre les personnes autorisées à consulter"/></label>
   <div class="grid-two"><label class="field">Priorité choisie<select required bind:value={draft.priority}><option value="">Choisir la priorité</option>{#each Object.entries(CORRECTION_PRIORITIES) as [id,label]}<option value={id}>{label}</option>{/each}</select></label><label class="field">Responsable de la réalisation<input required maxlength="160" bind:value={draft.owner}/></label></div>
   <label class="field">Pourquoi ce correctif et cette priorité ?<textarea required maxlength="4000" rows="3" bind:value={draft.reason}></textarea></label>
   <label class="field">Échéance du correctif<input type="date" bind:value={draft.due}/></label>
   <details class="subpanel"><summary>Dépend d’un autre correctif</summary><p class="help">La réalisation des correctifs choisis sera requise avant l’application de celui-ci. Une action abandonnée ne lève pas cette dépendance.</p>{#each workspace.actions.filter(a=>a.corrective&&a.id!==draft?.actionId&&!a.closure) as a}<label class="check"><input type="checkbox" checked={draft.dependsOn.includes(a.id)} onchange={e=>{if(draft)draft.dependsOn=e.currentTarget.checked?[...draft.dependsOn,a.id]:draft.dependsOn.filter(id=>id!==a.id);}}/>{a.corrective?.title}</label>{/each}{#each draft.dependsOn.filter(id=>workspace.actions.find(a=>a.id===id)?.closure) as id}<label class="check"><input type="checkbox" checked onchange={()=>{if(draft)draft.dependsOn=draft.dependsOn.filter(x=>x!==id);}}/>{workspace.actions.find(a=>a.id===id)?.corrective?.title} · déjà clôturé</label>{/each}</details>
   {#if activity}<div class="corrective-picker"><label class="field">Élément à modifier<select bind:value={selectedField}><option value="">Choisir parmi les faits de cet ensemble</option>{#each catalogue.filter(f=>!draft?.changes.some(c=>c.key===f.key)) as f}<option value={f.key}>{f.label}</option>{/each}</select></label><button type="button" class="secondary" disabled={!selectedField||draft.changes.length>=12} onclick={()=>{const f=catalogue.find(f=>f.key===selectedField);if(draft&&f){draft.changes.push(newCorrectionChange(f));selectedField='';}}}>Ajouter ce changement</button></div>{/if}
   {#each draft.changes as c,i (c.key)}{@const f=catalogue.find(f=>f.key===c.key)}<article class="corrective-change"><header><span class="corrective-number">{String(i+1).padStart(2,'0')}</span><h4>{c.label}</h4><button type="button" class="text-button" onclick={()=>{if(draft)draft.changes=draft.changes.filter(x=>x.key!==c.key);}}>Retirer ce changement</button></header>
    {#if !f}<p class="notice">Cet élément a été retiré de la description. Retirez ce changement et choisissez une cible existante.</p>{:else}
     {#if f.basis!==c.basis}<p class="notice">L’état de départ a changé. Aujourd’hui : {correctionValueText(f.value,f.options)}</p><button type="button" class="secondary" onclick={()=>refresh(i)}>Reprendre l’état actuel pour ce changement</button>{/if}
     <div class="corrective-before-after"><div><p class="eyebrow">État de départ conservé</p><p>{readable(c.before,c.key)}</p></div><div><p class="eyebrow">Après réalisation</p>
      {#if f.kind==='knowledge'}<label class="field">Nouvelle valeur · {c.label}<textarea required maxlength="4000" rows="3" value={typeof c.after==='object'&&!Array.isArray(c.after)&&'state' in c.after&&c.after.state==='documented'?c.after.value:''} oninput={e=>changeValue(i,knowledge(e.currentTarget.value))}></textarea></label>
      {:else if f.kind==='text'}<label class="field">Nouvelle valeur · {c.label}<input required maxlength="160" value={typeof c.after==='string'?c.after:''} oninput={e=>changeValue(i,e.currentTarget.value)}/></label>
      {:else if f.kind==='links'}<fieldset class="choices"><legend>Nouveaux liens · {c.label}</legend>{#each f.options as option}<label><input type="checkbox" checked={Array.isArray(c.after)&&c.after.includes(option.value)} onchange={e=>{const ids=Array.isArray(c.after)?c.after:[];changeValue(i,e.currentTarget.checked?[...ids,option.value]:ids.filter(id=>id!==option.value));}}/>{option.label}</label>{/each}</fieldset>
      {:else if typeof c.after==='object'&&!Array.isArray(c.after)&&'reference' in c.after}<label class="field">Nouvelle référence · {c.label}<select value={c.after.reference} onchange={e=>changeValue(i,{reference:e.currentTarget.value,description:unknown()})}>{#each f.options as o}<option value={o.value}>{o.label}</option>{/each}</select></label>{#if !c.after.reference}<label class="field">Nouvelle description · {c.label}<textarea required maxlength="4000" rows="3" value={c.after.description.state==='documented'?c.after.description.value:''} oninput={e=>changeValue(i,{reference:'',description:knowledge(e.currentTarget.value)})}></textarea></label>{/if}{/if}
     </div></div>
    {/if}
   </article>{/each}
   <p class="help">Jusqu’à 12 changements liés. Une valeur juridique ou une durée est votre décision explicite. Préparer le correctif ne modifie pas les faits du registre.</p>
   <button type="submit" disabled={!draft.changes.length}>Enregistrer le correctif prévu</button>
  {:else}
   <p><strong>{draft.title}</strong> · {activity?.title}</p>
   {#if draft.mode==='complete'}
    {#if conflicts.length}<p class="notice" role="alert">Des faits ont changé : {conflicts.join(' ; ')}. Reprenez le correctif avant de l’appliquer.</p>{/if}
    {#each draft.changes as c}<div class="corrective-change"><h4>{c.label}</h4><dl class="corrective-before-after"><div><dt>État de départ</dt><dd>{readable(c.before,c.key)}</dd></div><div><dt>État à appliquer</dt><dd>{readable(c.after,c.key)}</dd></div></dl></div>{/each}
    {#if preview}<details class="corrective-history"><summary>Voir la description et les flux après ce correctif</summary><CorrectiveSnapshot preview context={preview} version={correctiveVersion(workspace,draft.activityId)+1}/></details>{/if}
    <h4>Voilà la preuve</h4><p>Choisissez une référence de cet ensemble. L’original reste chez vous ; sa version et votre constat seront conservés avec la réalisation.</p>
    {#if !documents.some(d=>d.version.trim())}<p class="notice">Il faut une référence documentaire avec une version. Ajoutez-la dans Documents et reliez-la à cet ensemble.</p>{/if}
    <fieldset class="choices"><legend>Justificatifs de réalisation</legend>{#each documents as d}<label><input type="checkbox" disabled={!d.version.trim()||draft.evidence.length>=8&&!draft.evidence.some(e=>e.documentId===d.id)} checked={draft.evidence.some(e=>e.documentId===d.id)} onchange={e=>selectEvidence(d.id,e.currentTarget.checked)}/>{d.documentCode?`${d.documentCode} · `:''}{d.title} · {d.version||'Version à renseigner'}</label>{/each}</fieldset>
    {#each draft.evidence as citation}<section class="corrective-proof"><h5>{documents.find(d=>d.id===citation.documentId)?.title}</h5><p class="help">Version conservée : {citation.version}</p><label class="field">Passage ou repère examiné<input required maxlength="500" bind:value={citation.locator} oninput={()=>confirmed=false}/></label><label class="field">Ce que cette pièce permet de constater<textarea required maxlength="2000" rows="3" bind:value={citation.meaning} oninput={()=>confirmed=false}></textarea></label></section>{/each}
    <aside class="corrective-review"><Icon name="analysis"/><div><strong>À réexaminer après le changement</strong><p>{correctiveReexamination(workspace,draft.activityId).join(' · ')}</p><p class="help">Vos positions et leurs revues ne sont pas validées automatiquement.</p></div></aside>
   {/if}
   <label class="field">Auteur de la validation<input required maxlength="160" bind:value={draft.author} oninput={()=>confirmed=false}/></label><label class="field">{draft.mode==='complete'?'Constat de réalisation':'Motif de l’abandon'}<textarea required maxlength="4000" rows="3" bind:value={draft.justification} oninput={()=>confirmed=false}></textarea></label>
   <label class="check"><input type="checkbox" bind:checked={confirmed}/>{draft.mode==='complete'?'J’ai relu les changements et les justificatifs. Je confirme leur application aux faits du registre.':'Je confirme l’abandon de ce correctif. Les faits du registre resteront inchangés.'}</label>
   <button type="submit" disabled={!confirmed||draft.mode==='complete'&&(!draft.evidence.length||!!conflicts.length)}>{draft.mode==='complete'?'Confirmer la réalisation et mettre à jour le dossier':'Conserver le motif d’abandon'}</button>
  {/if}
  <button type="button" class="secondary" onclick={()=>onLeave(()=>{draft=null;error='';confirmed=false;})}>Quitter cette saisie</button>
 </fieldset></form>{/if}
 {#if !items.length&&!draft}<div class="corrective-empty"><Icon name="actions" size={34}/><h3>Vos corrections deviendront votre prochaine description.</h3><p>Partez d’un constat de l’analyse : un accès trop large, un canal à remplacer, des données à réduire ou une garantie à mettre en œuvre.</p></div>{/if}
 {#each items.slice(0,visible) as a (a.id)}{@const p=a.corrective!}{@const app=p.application}{@const blocked=correctiveConflicts(workspace,a)}<article class="corrective-card" class:applied={!!app}>
  <header><span class="corrective-card-icon"><Icon name={app?'check':a.closure?'history':'actions'} size={25}/></span><div><p class="eyebrow">{CORRECTION_PRIORITIES[p.priority]} · {a.closure?app?'Réalisation documentée':'Abandonné avec motif':'Correctif prévu'}</p><h3>{p.title}</h3><p>{workspace.activities.find(x=>x.id===a.activityId)?.title} · {a.owner} · {a.due??'Sans échéance'}</p></div>{#if app}<span class="corrective-version">v{app.version-1}<Icon name="arrow"/>v{app.version}</span>{/if}</header>
  <p>{p.reason}</p><p class="help">{p.changes.length} changement(s) préparé(s). {p.dependsOn.length} dépendance(s).</p>
  {#if !a.closure}{#if blocked.length}<p class="notice">État de départ à revoir : {blocked.join(' ; ')}</p>{/if}{#if p.dependsOn.some(id=>!workspace.actions.find(x=>x.id===id)?.corrective?.application)}<p class="notice">Une dépendance reste à réaliser : {p.dependsOn.filter(id=>!workspace.actions.find(x=>x.id===id)?.corrective?.application).map(id=>workspace.actions.find(x=>x.id===id)?.corrective?.title).join(' ; ')}</p>{/if}<div class="actions"><button disabled={busy||!!draft||!!blocked.length||p.dependsOn.some(id=>!workspace.actions.find(x=>x.id===id)?.corrective?.application)} onclick={()=>open(a,'complete')}>C’est fait, voilà la preuve <Icon name="check"/></button><button class="secondary" disabled={busy||!!draft} onclick={()=>open(a,'prepare')}>Reprendre le correctif</button><button class="text-button" disabled={busy||!!draft} onclick={()=>onDocument(a.activityId!)}>Référencer une preuve</button><button class="text-button" disabled={busy||!!draft} onclick={()=>open(a,'abandon')}>Abandonner sans appliquer</button></div>
  {:else}<p class="help">{a.closure.at.slice(0,10)} · {a.closure.author} : {a.closure.justification}</p>
   {#if app}<div class="actions"><button class="secondary" disabled={busy||!!draft} onclick={()=>onRegister(a.activityId!)}>Voir le registre actualisé</button><button class="secondary" disabled={busy||!!draft} onclick={()=>onShare(a.activityId!)}>Préparer l’export du registre <Icon name="download"/></button></div>
    <details class="corrective-history"><summary>Avant / après et justificatifs conservés · v{app.version-1} → v{app.version}</summary><p>Ces versions décrivent l’état immédiatement avant et après ce correctif. Les modifications ultérieures restent visibles dans le registre courant.</p><div class="corrective-proof">{#each app.evidence as c}<p><strong>{app.before.documents.find(d=>d.id===c.documentId)?.title}</strong> · version {c.version} · {c.locator}<br/>{c.meaning}</p>{/each}</div><details><summary>Description avant · v{app.version-1}</summary><CorrectiveSnapshot context={app.before} version={app.version-1}/></details><details><summary>Description après · v{app.version}</summary><CorrectiveSnapshot context={app.after} version={app.version}/></details></details>
   {/if}
  {/if}
 </article>{/each}
 {#if items.length>visible}<button class="secondary" onclick={()=>visible+=8}>Afficher les correctifs suivants ({items.length-visible})</button>{/if}
 <p class="help">Priorités choisies par le DPO, sans score. La confirmation consigne une réalisation déclarée et ses justificatifs ; RGPDESK ne vérifie pas les réglages de vos systèmes. Chaque application conserve un avant/après dans le coffre. Les exports restent soumis à votre sélection et à votre relecture.</p>
</section>
