<script lang="ts">
  import { onDestroy, untrack } from "svelte";
  import { correctiveVersion, documentaryActionLabel, resolvedFlows, knowledgeText, projectShare, PROFILE_LABELS, COVERAGE_LABELS, SHARE_LIMITATION, shareRows, type ShareOptions, type SharedRegister, type Workspace } from "@rgpdesk/privacy-core";
  import { packageFiles } from "@rgpdesk/privacy-verifier";
  import Icon from "./Icon.svelte";
  import ExportReviewToolbar from "./ExportReviewToolbar.svelte";
  import "../export-review.css";
  let exportConfirmation:HTMLElement | undefined = $state();
  import DeliveryComparison from "./DeliveryComparison.svelte";
  import ReportPreview from "./ReportPreview.svelte";
  export interface PreparedDelivery { workspaceId: string; revision: number; register: SharedRegister; files: Record<string, string>; manifestHash: string }
  let { workspace, busy, initialActivityId = "", demo = false, onDeliver, onDownload, onRead }: { workspace: Workspace; busy: boolean; initialActivityId?: string; demo?: boolean; onDeliver: (prepared: PreparedDelivery, format?: "zip" | "pdf") => Promise<void>; onRead: (id:string)=>Promise<SharedRegister>; onDownload: (id: string, format?: "zip" | "pdf") => Promise<void> } = $props();
  const initial = untrack(()=>workspace.activities.find(a=>a.id===initialActivityId));
  let options = $state<ShareOptions>({ profile: initial?.role==='processor'?'article30-processor':'article30-controller', recipient: "", scope: initial?`Description actualisée · v${untrack(()=>correctiveVersion(workspace,initial.id))} · ${initial.title}`:'', reservations: [], activityIds: initial?[initial.id]:[], documentIds: [], clientId: null });
  let reservations = $state(""); let prepared = $state<PreparedDelivery | null>(null); let confirmed = $state(false); let preparing = $state(false); let error = $state(""); let generation = 0;
  let eligible = $derived(workspace.activities.filter((a) => options.profile === "article30-controller" ? a.role === "controller" : options.profile === "internal-review" ? true : a.role === "processor" && (options.profile !== "client-excerpt" || a.controllerIds.length === 1 && a.controllerIds[0] === options.clientId)));
  let documents = $derived(workspace.documents.filter((d) => d.publicReference.trim() && d.activityIds.length && d.activityIds.every((id) => options.activityIds.includes(id)) && (options.profile !== "client-excerpt" || d.partyIds.every((id) => id === options.clientId))));
  function useDemoSelection() {
    options = { profile: "article30-controller", recipient: "Comité de mission fictif", scope: "DÉMONSTRATION FICTIVE Maison Sillage : activités responsables de traitement. Aucun usage réel ni validation juridique.", reservations: [], activityIds: workspace.activities.filter((a) => a.role === "controller").map((a) => a.id), documentIds: [], clientId: null };
    reservations = "Exercice fictif. Fondements juridiques, durées et transferts restent à examiner.\nLes références ne constituent pas des preuves. L’AIPD reste dans le dossier de travail et n’est pas exportée.";
  }
  function resetSelection() { options.activityIds = []; options.documentIds = []; options.flowIds = []; options.decisionIds = []; options.actionIds = []; options.presentation = false; delete options.executive; }
  async function prepare() {
    const current = ++generation; preparing = true; error = "";
    try {
      const captured = $state.snapshot(workspace);
      const register = projectShare(captured, { ...$state.snapshot(options), reservations: reservations.split("\n").filter(Boolean) }, () => crypto.randomUUID(), new Date().toISOString());
      const result = await packageFiles(register);
      if (current === generation) { prepared = { workspaceId: captured.id, revision: captured.revision, register, ...result }; confirmed = false; }
    } catch { if (current === generation) error = "Préparation refusée. Vérifiez le destinataire, le périmètre, les activités sélectionnées et les limites du dossier."; }
    finally { if (current === generation) preparing = false; }
  }
  onDestroy(() => { generation++; });
</script>
<section class="panel">
  <div class="section-heading"><div><p class="eyebrow">Préparer votre restitution</p><h2>Partager ce que vous avez examiné.</h2></div><span class="icon-tile"><Icon name="delivery" size={28} /></span></div>
  <p>À qui devez-vous remettre le registre et pour quel usage ? Définissez ce périmètre, choisissez les fiches, puis vérifiez ce que votre destinataire pourra lire.</p>
  <ol class="stepper" aria-label="Étapes du partage"><li class:current={!prepared}><span>1</span>Périmètre</li><li class:current={!!prepared}><span>2</span>Revue du contenu</li><li><span>3</span>Dossier & historique</li></ol>
  {#if error}<p class="notice error" role="alert">{error}</p>{/if}
  {#if !prepared}{#if demo}<div class="demo-share-preset"><Icon name="delivery" size={24} /><div><strong>Voir tout de suite à quoi ressemble une restitution.</strong><p><a href="/app/privacy/demo/" target="_blank" rel="noopener noreferrer">Lire le dossier final d’exemple (nouvel onglet)</a>, ou charger une sélection pour essayer le partage vous-même.</p></div><button class="secondary" disabled={busy || preparing} onclick={useDemoSelection}>Charger la sélection d’exemple</button></div>{/if}<form onsubmit={(e) => { e.preventDefault(); void prepare(); }}><fieldset disabled={busy || preparing}>
    <div class="grid-two"><label class="field">Profil de livraison<select aria-label="Profil de livraison" bind:value={options.profile} onchange={resetSelection}>{#each Object.entries(PROFILE_LABELS) as [value, label]}<option {value}>{label}</option>{/each}</select></label><label class="field">Destinataire déclaré<input required maxlength="160" bind:value={options.recipient} placeholder="Fonction ou organisme destinataire" /></label></div>
    <label class="field">Périmètre public de cette livraison<textarea required maxlength="4000" bind:value={options.scope} placeholder="Décrivez les activités, entités et limites couvertes."></textarea></label>
    {#if options.profile === "client-excerpt"}<label class="field">Client de l’extrait<select aria-label="Client de l’extrait" bind:value={options.clientId} onchange={resetSelection}><option value={null}>Choisir explicitement un client</option>{#each workspace.parties as p}<option value={p.id}>{p.name}</option>{/each}</select></label><p class="notice">Seules les fiches sous-traitantes dédiées à ce client sont proposées. Les fiches communes à plusieurs clients sont exclues. Relisez aussi les champs libres pour retirer toute information étrangère au périmètre.</p>{/if}
    <p class="help">Le prochain export reprend les faits enregistrés, y compris les correctifs appliqués. Les preuves internes et les versions précédentes restent dans le coffre. Les dossiers déjà livrés sont conservés dans leur état d’origine.</p><fieldset class="choices"><legend>Activités à inclure</legend>{#each eligible as a}<label><input type="checkbox" checked={options.activityIds.includes(a.id)} onchange={(e) => { options.activityIds = e.currentTarget.checked ? [...options.activityIds, a.id] : options.activityIds.filter((id) => id !== a.id); options.documentIds = []; options.flowIds = []; options.decisionIds = []; options.actionIds = []; options.presentation = false; delete options.executive; }} />{a.title} · {a.role === "controller" ? "Responsable" : "Sous-traitant"}</label>{/each}{#if !eligible.length}<p class="help">Aucune fiche éligible à ce profil. Documentez une activité dédiée au périmètre choisi.</p>{/if}</fieldset>
    <fieldset class="choices"><legend>Références publiques facultatives</legend>{#each documents as d}<label><input type="checkbox" checked={options.documentIds.includes(d.id)} onchange={(e) => options.documentIds = e.currentTarget.checked ? [...options.documentIds, d.id] : options.documentIds.filter((id) => id !== d.id)} />{d.publicReference}</label>{/each}{#if !documents.length}<p class="help">Aucune référence publique éligible. Les localisations et titres internes sont toujours exclus.</p>{/if}</fieldset>
    {#if options.profile !== "client-excerpt"}<details class="presentation-options"><summary>Ajouter une synthèse direction et des flux choisis</summary>
      <label class="check"><input type="checkbox" bind:checked={options.presentation} />Ajouter la synthèse des positions et suites sélectionnées</label>
      <label class="check"><input type="checkbox" checked={!!options.executive} onchange={e=>{if(e.currentTarget.checked)options.executive={changes:"",arbitrations:""};else delete options.executive;}} />Ouvrir le rapport par une lecture pour la direction</label>
      {#if options.executive}<div class="subpanel"><p>Deux messages courts pour ce destinataire. Les prochaines actions réutilisent votre sélection ci-dessous ; aucune note interne n’est copiée automatiquement.</p><label class="field">Ce qui change pour ce périmètre<textarea required maxlength="800" rows="3" bind:value={options.executive.changes}></textarea></label><label class="field">Arbitrages demandés à la direction<textarea required maxlength="800" rows="3" bind:value={options.executive.arbitrations}></textarea></label><p class="help">Ces textes seront communiqués en clair. S’il n’y a pas de changement ou d’arbitrage identifié, indiquez-le explicitement avec la portée de votre examen.</p></div>{/if}
      <p class="help">Aucun élément n’est sélectionné par défaut. Les noms d’acteurs et d’outils, les lieux et les habilitations des flux choisis seront lisibles. Relisez le contenu pour ce destinataire.</p>
      <fieldset class="choices"><legend>Flux à communiquer (60 maximum)</legend>{#each workspace.activities.filter((a) => options.activityIds.includes(a.id)) as a}{#each resolvedFlows(a, workspace) as f}<label><input type="checkbox" checked={options.flowIds?.includes(f.id) ?? false} onchange={(e) => options.flowIds = e.currentTarget.checked ? [...(options.flowIds ?? []), f.id] : options.flowIds?.filter((id) => id !== f.id)} />{a.title} · {knowledgeText(f.source) || "Origine à préciser"} → {knowledgeText(f.destination) || "Destination à préciser"}</label>{/each}{/each}</fieldset>
      <fieldset class="choices"><legend>Positions à communiquer, avec leurs motifs (10 maximum)</legend>{#each workspace.decisions.filter((d) => !d.activityId || options.activityIds.includes(d.activityId)) as d}<label><input type="checkbox" checked={options.decisionIds?.includes(d.id) ?? false} onchange={(e) => options.decisionIds = e.currentTarget.checked ? [...(options.decisionIds ?? []), d.id] : options.decisionIds?.filter((id) => id !== d.id)} />{d.conclusion}</label>{/each}</fieldset>
      <fieldset class="choices"><legend>Suites à communiquer, avec responsable et échéance (10 maximum)</legend>{#each workspace.actions.filter((a) => !a.closure && (!a.activityId || options.activityIds.includes(a.activityId))) as a}<label><input type="checkbox" checked={options.actionIds?.includes(a.id) ?? false} onchange={(e) => options.actionIds = e.currentTarget.checked ? [...(options.actionIds ?? []), a.id] : options.actionIds?.filter((id) => id !== a.id)} />{documentaryActionLabel(a)}</label>{/each}</fieldset>
    </details>{:else}<p class="help">La synthèse et les flux sont exclus du profil extrait client. Utilisez un dossier au périmètre spécifiquement relu pour partager une cartographie.</p>{/if}
    <label class="field">Réserves à communiquer<textarea maxlength="12000" bind:value={reservations} placeholder="Une réserve par ligne. Les inconnues resteront visibles même sans réserve ajoutée."></textarea></label>
    <p class="help">Le dossier partagé contient des données en clair. Les notes d’analyse, citations internes, provenances et identifiants du coffre sont exclus. Seuls les flux, positions et suites explicitement cochés peuvent compléter le registre ; leurs champs autorisés apparaissent dans la relecture. Le profil « revue documentaire » peut inclure les bases légales déclarées. Les noms et champs libres autorisés doivent être relus.</p>
    <button type="submit" disabled={!options.activityIds.length}>{preparing ? "Préparation locale…" : "Prévisualiser le dossier"}<Icon name="arrow" /></button>
  </fieldset></form>{:else}
    <div class="review-banner"><Icon name="eye" size={26} /><div><strong>{COVERAGE_LABELS[prepared.register.coverage]}</strong><p>{PROFILE_LABELS[prepared.register.profile]} · Destinataire : {prepared.register.recipient} · Révision examinée : {prepared.revision}</p></div></div>
    <p class="help">Le rapport HTML présente une vue d’ensemble et des fiches visuelles, générées à partir de cette sélection. Voici le contenu qui alimentera les fichiers JSON, CSV et HTML. Les rubriques renseignées ne constituent pas une conclusion juridique. Les identifiants visibles sont propres à cette livraison.</p>
    <ExportReviewToolbar target={exportConfirmation} formats="PDF · dossier ZIP" />
    <ReportPreview register={prepared.register}/>
    <details><summary>Examiner tous les champs du dossier</summary><div class="table-scroll preview-table"><table><caption>Contenu exact à partager</caption><thead><tr><th>Rubrique</th><th>Déclaration</th></tr></thead><tbody>{#each shareRows(prepared.register) as row}<tr><th scope="row">{row[0]}</th><td>{row[1]}</td></tr>{/each}</tbody></table></div></details>
    <p class="help">{SHARE_LIMITATION}</p>
    <section class="export-confirmation" aria-label="Confirmation de l’export" tabindex="-1" bind:this={exportConfirmation}><h3>Choisissez votre format.</h3><p>Confirmez le contenu relu, puis préparez le fichier à remettre.</p>
    <label class="check"><input type="checkbox" disabled={busy} bind:checked={confirmed} />J’ai relu ce contenu en clair, ses réserves et son destinataire. Je confirme ce partage pour cette révision.</label>
    <div class="actions"><button disabled={busy || !confirmed} onclick={() => { if (prepared) void onDeliver($state.snapshot(prepared)); }}>Confirmer et télécharger le dossier</button><button disabled={busy || !confirmed} class="secondary" onclick={() => { if (prepared) void onDeliver($state.snapshot(prepared), "pdf"); }}><Icon name="print" />Conserver et exporter en PDF</button><button disabled={busy} class="secondary" onclick={() => { prepared = null; confirmed = false; }}>Modifier le partage</button></div>
    <p class="help">{demo ? "Cet historique de démonstration reste en mémoire uniquement et disparaît en quittant la visite." : "L’historique chiffré sera enregistré avant le téléchargement."} Vérifiez ensuite le fichier sur votre disque. Au maximum 8 livraisons de 512 Kio dans cet espace.</p>
    </section>
  {/if}
</section>
<section class="panel delivery-history"><div class="section-heading"><div><p class="eyebrow">{demo ? "Historique de cette visite" : "Historique chiffré"}</p><h2>Les versions remises restent intactes.</h2></div><a class="button secondary" href="/app/privacy/verify/" target="_blank" rel="noreferrer noopener"><Icon name="shield" />Vérifier un dossier</a></div><p class="help">Instantanés historiques, sans mise à jour automatique. Un téléchargement préparé ne prouve pas sa réception par le destinataire.</p>
  {#if !workspace.deliveries.length}<p class="empty">Aucune livraison conservée pour le moment.</p>{/if}
  <DeliveryComparison {workspace} {busy} {onRead}/>
  <ul class="records">{#each workspace.deliveries as d}<li><span class="record-icon"><Icon name="delivery" /></span><div class="grow"><strong>{PROFILE_LABELS[d.profile]} · {d.recipient}</strong><p>{d.createdAt} · révision {d.revision}</p></div><button disabled={busy} class="secondary" onclick={() => onDownload(d.id)}>Télécharger l’instantané</button><button disabled={busy} class="secondary" onclick={() => onDownload(d.id, "pdf")}><Icon name="print" />Exporter en PDF</button></li>{/each}</ul>
</section>
