<script lang="ts">
 import {onDestroy} from 'svelte';
 import {compareDeliveries,PROFILE_LABELS,type Workspace,type SharedRegister} from '@rgpdesk/privacy-core';
 import Icon from './Icon.svelte';
 let {workspace,busy,onRead}:{workspace:Workspace;busy:boolean;onRead:(id:string)=>Promise<SharedRegister>}=$props();
 let before=$state(''),after=$state(''),loading=$state(false),error=$state(''),result=$state<ReturnType<typeof compareDeliveries>|null>(null),all=$state(false),generation=0;
 function reset(){generation++;result=null;error='';loading=false;all=false;}
 onDestroy(reset);
 async function compare(){if(!before||!after||before===after)return;reset();const ticket=++generation;loading=true;try{const a=await onRead(before);if(ticket!==generation)return;const b=await onRead(after);if(ticket===generation)result=compareDeliveries(a,b);}catch{if(ticket===generation)error='Comparaison indisponible. Les deux instantanés doivent être présents et vérifiables dans ce coffre.';}finally{if(ticket===generation)loading=false;}}
 const labels:Record<string,string>={name:'Nom',contact:'Contact',dpo:'DPO',representatives:'Représentants',changes:'Évolutions',arbitrations:'Arbitrages',description:'Finalité',legalBasis:'Fondement déclaré',retention:'Conservation',period:'Durée',trigger:'Point de départ',activity:'Activité',activities:'Activités',title:'Intitulé',role:'Rôle',source:'Origine',destination:'Destination',operation:'Opération',data:'Données',channel:'Canal',location:'Lieu',access:'Accès',text:'Référence',position:'Position',reason:'Motif',task:'Suite',owner:'Responsable',due:'Échéance'};
 function describe(v:unknown,key=''):string{if(v===null)return 'Non renseigné';if(typeof v==='string')return key==='role'&&v==='controller'?'Responsable de traitement':key==='role'&&v==='processor'?'Sous-traitant':v;if(Array.isArray(v))return v.map(item=>describe(item)).join(' ; ');if(v&&typeof v==='object'){const x=v as Record<string,unknown>;if(x.state==='unknown')return 'À documenter';if(x.state==='documented')return String(x.value);return Object.entries(x).map(([k,v])=>`${labels[k]??k} : ${describe(v,k)}`).join('\n');}return String(v);}
 function readable(s:string,structured:boolean){if(!structured)return s;return s.split('\n').map(line=>{try{return describe(JSON.parse(line));}catch{return line;}}).join('\n\n');}
</script>
{#if workspace.deliveries.length>=2}<details class="delivery-comparison"><summary><Icon name="delivery"/>Comparer deux dossiers conservés</summary><div class="comparison-body">
 <p>Comparez ce qui figurait effectivement dans deux partages. Une absence signifie « non inclus dans ce dossier », jamais « supprimé du registre » ou « action clôturée ».</p>
 <div class="grid-two"><label class="field">Premier dossier<select aria-label="Premier dossier" bind:value={before} onchange={reset}><option value="">Choisir une version</option>{#each workspace.deliveries as d}<option value={d.id}>Révision {d.revision} · {d.recipient} · {PROFILE_LABELS[d.profile]}</option>{/each}</select></label><label class="field">Second dossier<select aria-label="Second dossier" bind:value={after} onchange={reset}><option value="">Choisir une version</option>{#each workspace.deliveries as d}<option value={d.id}>Révision {d.revision} · {d.recipient} · {PROFILE_LABELS[d.profile]}</option>{/each}</select></label></div>
 <button disabled={busy||loading||!before||!after||before===after} onclick={compare}>{loading?'Lecture des instantanés…':'Comparer les contenus remis'}</button>
 {#if error}<p role="alert">{error}</p>{/if}
 {#if result}<section aria-label="Différences entre les dossiers"><p class="help">Activités rapprochées uniquement lorsque leur intitulé et leur rôle sont identiques et uniques dans chaque dossier. Un changement de nom n’est pas rapproché automatiquement. L’ordre et les identifiants propres à chaque livraison sont ignorés.</p>
 {#if result.scopeChanged}<p class="notice">Le destinataire, le profil ou le périmètre diffère. Les écarts peuvent venir de cette sélection, sans modification des faits.</p>{/if}
 {#if result.ambiguous.length}<p class="notice">Rapprochement ambigu, champs non comparés : {result.ambiguous.join(', ')}. Consultez les deux dossiers pour ces activités homonymes.</p>{/if}
 <p role="status">{result.differences.length} écarts de contenu dans les éléments comparables.</p>
 {#each result.differences.slice(0,all?undefined:12) as d}<article class="difference"><p class="eyebrow">{d.section}</p><h3>{d.label}</h3><div class="grid-two"><div><h4>Premier dossier</h4><p>{readable(d.before,d.structured)||'Non inclus'}</p></div><div><h4>Second dossier</h4><p>{readable(d.after,d.structured)||'Non inclus'}</p></div></div></article>{/each}
 {#if result.differences.length>12}<button class="secondary" onclick={()=>all=!all}>{all?'Réduire la comparaison':'Voir tous les écarts'}</button>{/if}</section>{/if}
 </div></details>{/if}
<style>.delivery-comparison{border:1px solid #aebfcf;border-radius:6px 20px 6px 6px;background:linear-gradient(120deg,#e1eaf2,#f5f7fa);margin-top:1.4rem}summary{display:flex;align-items:center;gap:.8rem;padding:1.2rem;cursor:pointer;font-weight:600}.comparison-body{padding:0 1.3rem 1.3rem}.difference{padding:1rem 0;border-top:1px solid #bbc9d4}.difference .grid-two>div{padding:1rem;background:#ffffffa8;border-radius:4px}.difference p{white-space:pre-wrap;overflow-wrap:anywhere}.difference h3{font-size:1.1rem}h4{margin:0 0 .5rem}</style>
