<script lang="ts">
  import { DEMO_STEPS, type DemoPanel } from "../demo-journey";
  import Icon from "./Icon.svelte";
  let { onNavigate, busy }: { onNavigate: (panel: DemoPanel) => void; busy: boolean } = $props();
</script>
<section class="demo-cover" aria-labelledby="demo-title">
  <div class="demo-cover-copy"><p class="eyebrow">Dossier ouvert / Maison Sillage</p><h2 id="demo-title">Prenez la place<br />du <em>DPO.</em></h2><p>Commencez par le projet de badges de Maison Sillage. Sa fiche, ses flux et son étude d’impact sont déjà remplis : suivez le même projet d’un écran à l’autre, puis essayez de préparer un dossier à partager.</p><button disabled={busy} onclick={() => onNavigate("register")}>Commencer par le registre <Icon name="arrow" /></button><button class="text-button" disabled={busy} onclick={() => onNavigate("delivery")}>Voir directement le résultat à partager <Icon name="arrow" size={16} /></button><small>Organisme, intervenants et situations entièrement fictifs.</small></div>
  <div class="demo-dossier" role="group" aria-label="Contenu de l’exercice : 4 activités, 7 flux et 1 AIPD"><span class="dossier-tab">SILLAGE / ÉTUDE DE CAS</span><div class="dossier-paper"><span class="dossier-mark">S.</span><p class="eyebrow">Le dossier de mission</p><h3>Des faits.<br />Des questions.<br /><em>Des choix à étayer.</em></h3><dl><div><dt>Activités</dt><dd>04</dd></div><div><dt>Flux décrits</dt><dd>07</dd></div><div><dt>AIPD à approfondir</dt><dd>01</dd></div></dl><span class="dossier-seal"><Icon name="eye" size={18} />EXERCICE / NON VALIDÉ</span></div></div>
</section>
<div class="demo-introduction"><div><p class="eyebrow">Une visite, dix gestes métier</p><h2>Suivez le fil.<br /><em>Ou ouvrez le dossier qui vous intéresse.</em></h2></div><p>Tout se passe dans cet onglet. Vous pouvez essayer les formulaires avec des données fictives. Vos modifications disparaissent en quittant la démo ou en rechargeant la page.</p></div>
<ol class="demo-route">{#each DEMO_STEPS as step, i}<li><button disabled={busy} onclick={() => onNavigate(step.panel)}><span class="demo-route-index">{String(i + 1).padStart(2, "0")}</span><span class="demo-route-icon"><Icon name={step.icon} size={27} /></span><span class="demo-route-copy"><strong>{step.title}</strong><span>{step.result}</span></span><Icon name="arrow" size={20} /></button></li>{/each}</ol>
<aside class="demo-editorial"><Icon name="book" size={26} /><div><h3>Un exemple de travail, pas un modèle juridique à recopier.</h3><p>Les fondements juridiques et les durées restent à déterminer. L’AIPD est renvoyée pour approfondissement ; aucun traitement n’est autorisé par cet exercice. Les références de documents sont inventées et ne constituent pas des justificatifs.</p><a href="/app/privacy/guide/" target="_blank" rel="noopener noreferrer">Retrouver les méthodes et leurs sources dans le guide <Icon name="arrow" size={16} /></a></div></aside>
