<script lang="ts">
 import {documentaryActionLabel,entityDossier,resolveFlow,knowledgeText,type Workspace} from "@rgpdesk/privacy-core";
 let {workspace,kind,id,busy,onActivity,onDocument,onActions}:{workspace:Workspace;kind:"party"|"system";id:string;busy:boolean;onActivity:(id:string)=>void;onDocument:(id:string)=>void;onActions:(id:string)=>void}=$props();
 let dossier=$derived(entityDossier(workspace,kind,id));
 let entity=$derived((kind==='party'?workspace.parties:workspace.systems).find(e=>e.id===id));
</script>
{#if entity}<section class="subpanel entity-dossier" aria-label="Fiche transversale"><p class="eyebrow">{kind==='party'?'Intervenant':'Outil'} · Vue d’ensemble</p><h3>{entity.name}</h3><p class="help">Les liens déclarés dans votre inventaire se retrouvent ici. Aucun rôle ni contrat n’est déduit des noms ou du contenu des documents.</p>
<h4>Activités liées · {dossier.activities.length}</h4><ul class="records">{#each dossier.activities as a}<li><span>{a.title}</span><button class="secondary" disabled={busy} onclick={()=>onActivity(a.id)}>Ouvrir la fiche</button></li>{/each}</ul>{#if !dossier.activities.length}<p>Aucune activité explicitement liée. Reliez cet élément depuis une fiche ou un flux.</p>{/if}
<h4>Flux qui passent par cet élément · {dossier.flows.length}</h4>{#each dossier.flows as pair}{@const f=resolveFlow(pair.flow,pair.activity,workspace)}<figure class="entity-flow"><figcaption>{pair.activity.title}</figcaption><div><span>{knowledgeText(f.source)||"Origine à préciser"}</span><span aria-label="vers">→</span><span>{knowledgeText(f.destination)||"Destination à préciser"}</span></div><p>{knowledgeText(f.operation)||"Opération à préciser"}</p></figure>{/each}
<h4>Références et contrats · {dossier.documents.length}</h4><ul class="records">{#each dossier.documents as d}<li><div class="grow"><strong>{d.title}</strong><p>{kind==='party'&&d.partyIds.includes(id)?'Lien direct déclaré avec cet intervenant':'Référence d’une activité liée'} · {d.version||'Version à préciser'}</p></div><button class="secondary" disabled={busy} onclick={()=>onDocument(d.id)}>Examiner la référence</button></li>{/each}</ul>
{#if dossier.questions.length}<details><summary>Questions étayées par ces références · {dossier.questions.length}</summary><ul>{#each dossier.questions as q}<li>{q.title}</li>{/each}</ul><p class="help">Retrouvez les citations dans l’analyse ou le dossier concerné. Cette liste indique les liens, sans valider les preuves.</p></details>{/if}
<h4>Actions ouvertes · {dossier.actions.length}</h4><ul class="records">{#each dossier.actions as a}<li><div class="grow"><strong>{documentaryActionLabel(a)}</strong><p>{a.owner||'À affecter'} · {a.due||'Sans échéance'}</p></div><button class="secondary" disabled={busy} onclick={()=>onActions(a.activityId!)}>Voir les suites</button></li>{/each}</ul></section>{/if}
