<script lang="ts">
  import { entityDossier, canonicalJson, type Party, type System, type Workspace } from '@rgpdesk/privacy-core';
  import Icon from './Icon.svelte';
  let {workspace,draft,kind,busy,onActivity,onDocument,onAnalysis,onPia,onCase}:{workspace:Workspace;draft:Party|System;kind:'party'|'system';busy:boolean;onActivity:(id:string)=>void;onDocument:(id:string)=>void;onAnalysis:(id:string)=>void;onPia:(id:string)=>void;onCase:(id:string)=>void}=$props();
  let previous=$derived(workspace[kind==='party'?'parties':'systems'].find(e=>e.id===draft.id));
  let changed=$derived(!!previous&&canonicalJson(previous)!==canonicalJson(draft));
  let dossier=$derived(entityDossier(workspace,kind,draft.id));
  let pias=$derived(workspace.impactAssessments.filter(p=>dossier.activities.some(a=>a.id===p.activityId)));
  let cases=$derived(workspace.dpoCases.filter(c=>c.activityIds.some(id=>dossier.activities.some(a=>a.id===id))));
</script>
{#if changed}<aside class="entity-change-preview" aria-label="Portée de la modification"><h3><Icon name="flows"/>Ce changement sera partagé</h3><p><strong>{previous?.name}</strong> → <strong>{draft.name||'Nom à renseigner'}</strong></p><p>{dossier.activities.length} activités liées · {dossier.flows.length} flux liés · {pias.length} études AIPD · {cases.length} dossiers DPO</p><p class="help">Les liens utiliseront la nouvelle fiche après enregistrement. Examinez si ce changement affecte vos analyses ; les revues historiques conservent leur contexte. Aucun avis n’est modifié automatiquement.</p>
  <details><summary>Voir les éléments à examiner</summary><ul>{#each dossier.activities as a}<li><span>{a.title}</span><button type="button" class="text-button" disabled={busy} onclick={()=>onActivity(a.id)}>Voir l’activité</button><button type="button" class="text-button" disabled={busy} onclick={()=>onAnalysis(a.id)}>Voir l’analyse</button></li>{/each}{#each dossier.documents as d}<li><span>{d.title}</span><button type="button" class="text-button" disabled={busy} onclick={()=>onDocument(d.id)}>Voir la référence</button></li>{/each}{#each pias as p}<li><span>Étude AIPD · {workspace.activities.find(a=>a.id===p.activityId)?.title}</span><button type="button" class="text-button" disabled={busy} onclick={()=>onPia(p.activityId)}>Voir l’étude</button></li>{/each}{#each cases as c}<li><span>{c.title}</span><button type="button" class="text-button" disabled={busy} onclick={()=>onCase(c.id)}>Voir le dossier</button></li>{/each}</ul>{#if !dossier.activities.length&&!dossier.documents.length}<p>Aucun lien explicite dans ce coffre. Les noms saisis en texte libre ne sont pas des liens.</p>{/if}</details>
</aside>{/if}
<style>.entity-change-preview{margin:1.5rem 0;padding:1.2rem 1.4rem;border:1px solid #adbecb;border-left:3px solid #536d83;background:linear-gradient(130deg,#dde8f0,#f4f6f8);border-radius:5px 20px 5px 5px}h3{display:flex;gap:.8rem;align-items:center;font-size:1.1rem}li{display:flex;gap:.7rem;flex-wrap:wrap;align-items:center;padding:.65rem 0}li span{flex:1 1 200px}ul{list-style:none;padding:0}summary{cursor:pointer;font-weight:600}</style>
