<script lang="ts">
  import { piaReviewState, dpoChanges, rightsDeadline, breachDeadline, evaluateWorkspace, type Activity, type Workspace } from "@rgpdesk/privacy-core";
  import Pictogram from "./Pictogram.svelte";
  import Icon from "./Icon.svelte";
  let { workspace, busy, onNavigate, onEdit, onCase, onPia }: { workspace: Workspace; busy: boolean; onNavigate: (panel: "dpo" | "pia" | "pia-sharing" | "flows" | "analysis" | "register" | "organization" | "documents" | "actions" | "delivery" | "backup" | "import") => void; onEdit: (activity: Activity) => void; onCase: (id: string) => void; onPia: (activityId: string) => void } = $props();
  let findings = $derived(evaluateWorkspace(workspace, new Date().toISOString().slice(0, 10)));
  let openActions = $derived(workspace.actions.filter((action) => !action.closure));
  let nextActivity = $derived(workspace.activities.find((activity) => activity.status === "draft") ?? workspace.activities.find((activity) => activity.status !== "archived"));
  const dossierDue = (c: Workspace["dpoCases"][number]) => {
    try { return c.kind === "rights" ? rightsDeadline(c.content.rights).due : c.kind === "breach" ? breachDeadline(c.content.breach.awarenessAt, c.content.breach.role) : c.content.reviewDue; }
    catch { return null; }
  };
  let cases = $derived(workspace.dpoCases.filter((c) => c.reviews.at(-1)?.outcome !== "closed" || dpoChanges(workspace,c).length).toSorted((a,b) => (dossierDue(a) ?? "9999").localeCompare(dossierDue(b) ?? "9999")));
  let changedStudies = $derived(workspace.impactAssessments.filter((p) => piaReviewState(workspace, p) === "changed"));
  const route = [
    { panel: "organization", icon: "organization", title: "Cadrer votre mission", text: "Précisez l’organisme, les contacts et le périmètre que vous accompagnez.", action: "Décrire l’organisation" },
    { panel: "register", icon: "register", title: "Rencontrer les métiers", text: "Choisissez une activité, préparez l’entretien et consignez ce que vous apprenez.", action: "Ouvrir le registre" },
    { panel: "flows", icon: "flows", title: "Suivre les données", text: "Décrivez les opérations, les origines, les destinations et les accès connus.", action: "Voir la cartographie" },
    { panel: "analysis", icon: "analysis", title: "Construire votre analyse", text: "Examinez les finalités, les fondements, les droits et la sécurité du traitement.", action: "Ouvrir la grille" },
    { panel: "dpo", icon: "folder", title: "Instruire les dossiers du quotidien", text: "Intérêt légitime par finalité, transferts, demandes de droits et violations : gardez le contexte, les preuves et les revues ensemble.", action: "Ouvrir les dossiers DPO" },
    { panel: "pia", icon: "analysis", title: "Étudier les effets sur les personnes", text: "Cadrez l’AIPD, comparez les options et argumentez les risques avant une décision humaine.", action: "Ouvrir l’atelier AIPD" },
    { panel: "pia-sharing", icon: "delivery", title: "Restituer l’AIPD examinée", text: "Choisissez les rubriques, le destinataire et les réserves, puis relisez le rapport avant de le télécharger.", action: "Préparer la restitution AIPD" },
    { panel: "documents", icon: "documents", title: "Rassembler les références", text: "Retrouvez les notices, contrats et procédures qui éclairent chaque traitement.", action: "Relier les documents" },
    { panel: "actions", icon: "actions", title: "Organiser les suites", text: "Transformez une question ouverte en action, avec un responsable et une échéance.", action: "Examiner les questions" },
    { panel: "delivery", icon: "delivery", title: "Préparer votre restitution", text: "Sélectionnez les fiches utiles au destinataire et relisez le dossier avant de le transmettre.", action: "Préparer un partage" },
    { panel: "backup", icon: "backup", title: "Conserver votre travail", text: "Téléchargez une sauvegarde chiffrée et gardez une copie séparément de cet appareil.", action: "Sauvegarder le coffre" },
  ] as const;
</script>

<section class="mission-next" aria-labelledby="mission-next-title">
  <div><p class="eyebrow">{workspace.activities.length ? "Votre prochaine séance" : "Bienvenue dans votre mission"}</p><h2 id="mission-next-title">{nextActivity ? "Reprenez une activité, gardez le fil." : "Votre première fiche commence par une conversation."}</h2>
  <p>{nextActivity ? "Ouvrez une fiche pour poursuivre l’entretien ou examinez les questions restées ouvertes. Vous pouvez avancer par petites étapes." : "Choisissez un usage de données concret, puis échangez avec la personne qui le connaît. RGPDESK vous aide à poser les questions et à organiser les réponses."}</p>
  <div class="actions">{#if nextActivity}<button disabled={busy} onclick={() => onEdit(nextActivity!)}>Reprendre {nextActivity.title}<Icon name="arrow" /></button><button class="secondary" disabled={busy} onclick={() => onNavigate("actions")}>Voir les questions ouvertes</button>{:else}<button disabled={busy} onclick={() => onNavigate("register")}>Choisir ma première activité<Icon name="arrow" /></button><button class="secondary" disabled={busy} onclick={() => onNavigate("import")}>J’ai déjà un registre CSV</button>{/if}</div></div>
  <aside><Pictogram kind="book" /><h3>Le bon réflexe</h3><p>Notez ce qui est connu. Laissez une information à examiner si vous ne l’avez pas encore. Enregistrez, puis revenez avec la réponse.</p></aside>
</section>
<nav class="mission-facts" aria-label="Accès au travail en cours"><button class="secondary" disabled={busy} onclick={() => onNavigate("register")}><strong>{workspace.activities.length}</strong> fiches au registre</button><button class="secondary" disabled={busy} onclick={() => onNavigate("actions")}><strong>{findings.length}</strong> questions à examiner</button><button class="secondary" disabled={busy} onclick={() => onNavigate("actions")}><strong>{openActions.length}</strong> actions en cours</button></nav>
<section class="panel" aria-label="Dossiers en suivi"><div class="section-heading"><div><p class="eyebrow">Votre file de travail</p><h2>Les dossiers à reprendre.</h2></div><button class="secondary" disabled={busy} onclick={() => onNavigate("dpo")}>Tous les dossiers DPO</button></div><ul class="records">{#each cases.slice(0, 8) as c}<li><div class="grow"><strong>{c.title}</strong><p>{c.owner || "Responsable à désigner"} · {dossierDue(c) || "Échéance à examiner"}</p><p>{dpoChanges(workspace,c).join(" · ") || "Contexte inchangé depuis la revue"}</p></div><button class="secondary" disabled={busy} onclick={() => onCase(c.id)}>Reprendre ce dossier</button></li>{/each}</ul>{#if !cases.length}<p>Commencez par une demande, une question de transfert ou une finalité dont vous examinez l’intérêt légitime.</p>{/if}<p class="help">Les repères découlent de vos paramètres. Cette liste ne vaut ni alerte externe ni qualification juridique.</p></section>
{#if changedStudies.length}<section class="panel" aria-label="Études à réexaminer"><p class="eyebrow">Après votre dernière revue</p><h2>Ces études ont un contexte qui évolue.</h2><p>Retrouvez les différences, les références et la position conservée avant de décider des suites.</p><ul class="records">{#each changedStudies as p}<li><div class="grow"><strong>{workspace.activities.find((a) => a.id === p.activityId)?.title}</strong><p>Faits ou arguments modifiés depuis la revue du {p.reviews.at(-1)?.at.slice(0,10)}</p></div><button class="secondary" disabled={busy} onclick={() => onPia(p.activityId)}>Comparer cette AIPD</button></li>{/each}</ul></section>{/if}
<section aria-labelledby="mission-route-title"><div class="section-heading"><div><p class="eyebrow">Du premier entretien à la restitution</p><h2 id="mission-route-title">Un fil conducteur pour votre mission.</h2></div></div><div class="mission-route">{#each route as item, index}<article class="panel"><span class="route-number">{String(index + 1).padStart(2, "0")}</span><Icon name={item.icon} size={26} /><h3>{item.title}</h3><p>{item.text}</p><button class="text-button" disabled={busy} onclick={() => onNavigate(item.panel)}>{item.action}<Icon name="arrow" size={16} /></button></article>{/each}</div></section>
<p class="help">Ce parcours organise votre travail. Les questions signalent des informations à examiner ; leur nombre n’est pas une mesure de conformité.</p>
