<script lang="ts">
  import { knowledgeText, piaOpenPoints, type PiaContent, type PiaContext, type ReviewNote } from "@rgpdesk/privacy-core";
  import { PIA_NECESSITY_METHOD } from "../review-methods";
  import { PIA_PRINCIPLE_QUESTIONS, PIA_RISK_FIELDS, PIA_ALTERNATIVE_FIELDS, PIA_MEASURE_FIELDS, SCREENING_LABELS, PIA_SOURCES } from "../pia-method";
  import FlowMap from "./FlowMap.svelte";
  import PiaRiskMap from "./PiaRiskMap.svelte";
  let { content, context }: { content: PiaContent; context: PiaContext } = $props();
  const noteFields = { facts: "Faits", evidence: "Références", objections: "Objections", assessment: "Appréciation", followUp: "Suites" } as const;
</script>
{#snippet notes(values: ReviewNote[], titles: readonly { id: string; title: string }[])}
  {#each values as note}<details><summary>{titles.find((q) => q.id === note.questionId)?.title ?? note.questionId}</summary><dl>{#each Object.entries(noteFields) as [key, label]}<dt>{label}</dt><dd>{knowledgeText(note[key as keyof typeof noteFields]) || "À documenter"}</dd>{/each}</dl></details>{/each}
{/snippet}
<article class="pia-dossier" aria-label="Dossier AIPD en lecture">
  <header><p class="eyebrow">Dossier interne · AIPD</p><h3>{context.activity.title}</h3><p>{context.organization.name} · {context.activity.role === "controller" ? "Responsable de traitement" : "Contribution sous-traitant"}</p><p>Informations et appréciations déclarées. Cette lecture ne constitue ni une certification ni une autorisation de traitement.</p></header>
  <section><h4>Points à instruire</h4>{#if piaOpenPoints(content).length}<ul>{#each piaOpenPoints(content) as point}<li>{point}</li>{/each}</ul>{:else}<p>Aucun manque détecté par les contrôles de saisie. La justesse des éléments et la décision restent à examiner par les personnes compétentes.</p>{/if}</section>
  <section><h4>1. Déclenchement et contexte</h4><dl><dt>Examen du champ applicable</dt><dd>{knowledgeText(content.applicability) || "À documenter"}</dd><dt>Position sur la réalisation de l’AIPD</dt><dd>{({ unknown: "Décision à instruire", required: "AIPD jugée requise", voluntary: "AIPD engagée volontairement", "not-required": "AIPD jugée non requise" })[content.screeningDecision]}</dd><dt>Motif de réalisation ou de non-réalisation</dt><dd>{knowledgeText(content.screeningReason) || "À documenter"}</dd><dt>Portée de l’organisation</dt><dd>{knowledgeText(context.scope) || "À documenter"}</dd><dt>Juridiction examinée</dt><dd>{knowledgeText(context.jurisdiction) || "À documenter"}</dd></dl>
    {#each content.screening as criterion}<p><strong>{SCREENING_LABELS[criterion.criterionId]}</strong> : {criterion.answer === "yes" ? "Identifié" : criterion.answer === "no" ? "Non identifié après examen" : "À examiner"}. {knowledgeText(criterion.reason) || "Motif à documenter"}</p>{/each}
    <dl>{#each [["Personnes", context.activity.dataSubjects], ["Données", context.activity.dataCategories], ["Destinataires", context.activity.recipients], ["Transferts", context.activity.transfers], ["Sécurité", context.activity.securityMeasures]] as [label, value]}<dt>{label}</dt><dd>{knowledgeText(value as typeof context.scope) || "À documenter"}</dd>{/each}</dl>
    {#if context.activity.role === "controller"}{#each context.activity.purposes as purpose, index}<h5>Finalité {index + 1}</h5><dl><dt>Objectif</dt><dd>{knowledgeText(purpose.description) || "À documenter"}</dd><dt>Fondement juridique</dt><dd>{knowledgeText(purpose.legalBasis) || "À documenter"}</dd><dt>Conservation / déclencheur</dt><dd>{knowledgeText(purpose.retention.period) || "À documenter"} / {knowledgeText(purpose.retention.trigger) || "À documenter"}</dd></dl>{/each}{:else}<dl><dt>Opérations confiées</dt><dd>{knowledgeText(context.activity.operations) || "À documenter"}</dd><dt>Instructions</dt><dd>{knowledgeText(context.activity.instructions) || "À documenter"}</dd></dl>{/if}
    <h5>Acteurs et supports liés</h5><ul>{#each context.parties as party}<li>{party.name} · {knowledgeText(party.contact) || "Contact à documenter"}</li>{/each}{#each context.systems as system}<li>{system.name} · {knowledgeText(system.description) || "Description à documenter"}</li>{/each}</ul>
    <h5>Références documentaires liées</h5><ul>{#each context.documents as doc}<li>{doc.title} · version {doc.version || "non renseignée"} · {doc.internalRef || "référence à documenter"} · {doc.reservations || "Aucune réserve saisie"}</li>{/each}</ul>
    {#if context.activity.flows.length}<FlowMap flows={context.activity.flows} />{:else}<p>Aucun flux décrit.</p>{/if}
    {@render notes(content.principles, PIA_PRINCIPLE_QUESTIONS)}
  </section>
  <section><h4>2. Nécessité et proportionnalité</h4><dl><dt>Opérations examinées</dt><dd>{knowledgeText(content.necessity.operations) || "À documenter"}</dd><dt>Accès examinés</dt><dd>{knowledgeText(content.necessity.access) || "À documenter"}</dd></dl>{@render notes(content.necessity.notes, PIA_NECESSITY_METHOD)}
    <h5>Alternatives</h5>{#each content.alternatives as alternative, index}<h5>Option {index + 1}</h5><dl>{#each Object.entries(PIA_ALTERNATIVE_FIELDS) as [key, label]}<dt>{label}</dt><dd>{knowledgeText(alternative[key as keyof typeof PIA_ALTERNATIVE_FIELDS]) || "À documenter"}</dd>{/each}</dl>{:else}<p>Aucune alternative décrite.</p>{/each}
  </section>
  <section><h4>3. Risques pour les personnes</h4><p>{knowledgeText(content.evaluationMethod) || "Méthode d’appréciation à documenter"}</p><div class="grid-two"><PiaRiskMap risks={content.risks} /><PiaRiskMap risks={content.risks} residual /></div>
    {#each content.risks as risk, index}<details><summary>R{index + 1} · {risk.title}</summary><dl>{#each Object.entries(PIA_RISK_FIELDS) as [key, label]}<dt>{label}</dt><dd>{knowledgeText(risk[key as keyof typeof PIA_RISK_FIELDS]) || "À documenter"}</dd>{/each}<dt>Risque résiduel élevé, appréciation humaine</dt><dd>{risk.residualHigh === "unknown" ? "Non apprécié" : risk.residualHigh === "yes" ? "Oui" : "Non, selon les motifs saisis"}</dd></dl></details>{/each}
  </section>
  <section><h4>4. Mesures et suivi</h4>{#each content.measures as measure, index}<details><summary>Mesure {index + 1} · {measure.status === "planned" ? "Prévue" : measure.status === "implemented" ? "Mise en œuvre déclarée" : "Vérification déclarée"}</summary><p>Échéance : {measure.due || "À fixer"}. Scénarios : {measure.riskIds.map((id) => `R${content.risks.findIndex((r) => r.id === id) + 1}`).join(", ") || "Aucun lien saisi"}.</p><dl>{#each Object.entries(PIA_MEASURE_FIELDS) as [key, label]}<dt>{label}</dt><dd>{knowledgeText(measure[key as keyof typeof PIA_MEASURE_FIELDS]) || "À documenter"}</dd>{/each}</dl></details>{:else}<p>Aucune mesure complémentaire décrite.</p>{/each}</section>
  <section><h4>5. Avis et réexamen</h4><dl><dt>Avis du DPO</dt><dd>{knowledgeText(content.dpoAdvice) || "À documenter"}</dd><dt>Consultation des personnes</dt><dd>{knowledgeText(content.peopleConsultation) || "À documenter"}</dd><dt>Consultation préalable de l’autorité</dt><dd>{knowledgeText(content.authorityConsultation) || "À documenter"}</dd><dt>Surveillance des changements</dt><dd>{knowledgeText(content.monitoring) || "À documenter"}</dd><dt>Prochain réexamen</dt><dd>{content.reviewDue || "À fixer"}</dd></dl></section>
  <footer><a href={PIA_SOURCES.law} target="_blank" rel="noopener noreferrer">RGPD, articles 35 et 36</a> · <a href={PIA_SOURCES.method} target="_blank" rel="noopener noreferrer">Méthode CNIL, février 2018</a> · <a href={PIA_SOURCES.criteria} target="_blank" rel="noopener noreferrer">G29, WP248 rév.01, annexe 2</a></footer>
</article>
