<script lang="ts">
  import { reviewTargets, reexaminationQueue, reexamineCitation, knowledgeText, type Workspace } from "@rgpdesk/privacy-core";
  import { onDestroy } from "svelte";
  let { workspace, busy, onSave }: {workspace:Workspace;busy:boolean;onSave:(w:Workspace)=>Promise<boolean>}=$props();
  let rows=$derived(reexaminationQueue(workspace)), selected=$state(""), locator=$state(""), documentId=$state(""), author=$state(""), reason=$state(""), assessment=$state(""), outcome=$state<"maintained"|"revised">("maintained"), error=$state("");
  let row=$derived(rows.find(r=>r.target.key===selected&&r.citation.locator===locator&&r.citation.documentId===documentId));
  let alive=true; onDestroy(()=>{alive=false;});
  export function hasUnsavedChanges(){return !!selected;}
  function open(r:typeof rows[number]){selected=r.target.key;locator=r.citation.locator;documentId=r.document.id;author=reason="";assessment=knowledgeText(r.target.note.assessment);outcome=r.target.note.assessment.state==='documented'?'maintained':'revised';error="";}
  async function save(){if(!row)return;try{const next=reexamineCitation($state.snapshot(workspace),{target:selected,documentId,locator,fromVersion:row.citation.version,toVersion:row.document.version,outcome,assessment,author,reason},workspace.revision,new Date().toISOString());if(await onSave(next)&&alive)selected="";}catch{if(alive)error="Le réexamen n’a pas été enregistré. Vérifiez le motif, l’auteur et l’appréciation, puis reprenez la référence actuelle.";}}
</script>
{#if rows.length}<section class="panel reexamination-queue" aria-label="Réexamens des références"><p class="eyebrow">Une preuve a changé</p><h2>{rows.length} passage(s) à relire.</h2><p>Ces questions citent une autre version du document. Le changement n’impose aucune conclusion : relisez le passage, puis motivez votre position.</p>
{#if !selected}<ul class="records">{#each rows.slice(0,5) as r}<li><div class="grow"><strong>{r.target.title}</strong><p>{r.document.title} · {r.citation.locator} · {r.citation.version||"Sans version"} → {r.document.version||"Sans version"}</p></div><button class="secondary" disabled={busy} onclick={()=>open(r)}>Réexaminer ce passage</button></li>{/each}</ul>{#if rows.length>5}<details><summary>Les {rows.length-5} autres passages</summary><ul class="records">{#each rows.slice(5) as r}<li><span>{r.target.title} · {r.document.title}</span><button class="secondary" disabled={busy} onclick={()=>open(r)}>Réexaminer ce passage</button></li>{/each}</ul></details>{/if}
{:else if row}<form onsubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy}><h3 data-draft-heading tabindex="-1">{row.target.title}</h3><dl><dt>Document à retrouver</dt><dd>{row.document.title} · {row.document.version}<br>{row.document.internalRef}</dd><dt>Passage et argument cités</dt><dd>{row.citation.locator}<br>{row.citation.meaning}</dd><dt>Appréciation précédente</dt><dd>{knowledgeText(row.target.note.assessment)||"Non documentée"}</dd></dl><label class="field">À l’issue de votre relecture<select aria-label="À l’issue de votre relecture" bind:value={outcome}><option value="maintained" disabled={row.target.note.assessment.state!=='documented'}>Maintenir mon appréciation</option><option value="revised">Réviser mon appréciation</option></select></label>{#if outcome==='revised'}<label class="field">Nouvelle appréciation<textarea required maxlength="4000" bind:value={assessment}></textarea></label>{/if}<label class="field">Motif du réexamen<textarea required maxlength="4000" bind:value={reason}></textarea></label><label class="field">Auteur de cette relecture<input required maxlength="160" bind:value={author} /></label><p class="help">La version citée sera actualisée. Le passage, l’argument, l’ancienne appréciation et votre motif resteront dans l’historique chiffré.</p>{#if error}<p role="alert">{error}</p>{/if}<div class="actions"><button type="submit">Consigner le réexamen</button><button type="button" class="secondary" onclick={()=>selected=""}>Annuler le réexamen</button></div></fieldset></form>{/if}</section>{/if}
{#if workspace.citationReviews?.length}<details class="panel"><summary>Historique des relectures de preuves · {workspace.citationReviews.length}</summary>{#each [...workspace.citationReviews].reverse() as r}<article class="subpanel"><p class="eyebrow">{reviewTargets(workspace).find(t=>t.key===r.target)?.title||"Question historique"}</p><h3>{workspace.documents.find(d=>d.id===r.documentId)?.title||"Référence historique"} · {r.locator}</h3><p>{r.at.slice(0,10)} · {r.author} · {r.outcome==='maintained'?'Appréciation maintenue':'Appréciation révisée'}</p><dl><dt>Versions relues</dt><dd>{r.fromVersion} → {r.toVersion}</dd><dt>Avant</dt><dd>{knowledgeText(r.before)||"Non documenté"}</dd><dt>Après</dt><dd>{knowledgeText(r.after)}</dd><dt>Motif</dt><dd>{r.reason}</dd></dl></article>{/each}</details>{/if}
