<script lang="ts">
  import { createCollection, type Workspace } from "@rgpdesk/privacy-core";
  import { requestItems, requestText } from "../request-brief";
  import type { RecoveryForm } from "../persistence/recovery";
  import Icon from "./Icon.svelte";
  let {workspace,busy,onSave}:{workspace:Workspace;busy:boolean;onSave:(next:Workspace)=>Promise<void>}=$props();
  let due=$state('');
  let opened=$state(false);
  let recipient=$state(''), owner=$state(''), selected=$state<string[]>([]), preview=$state(''), confirmed=$state(false), message=$state(''), error=$state('');
  let items=$derived(requestItems(workspace,new Date().toISOString().slice(0,10)));
  let owners=$derived([...new Set(items.map(i=>i.owner).filter(Boolean))]);
  let visible=$derived(items.filter(i=>!owner||i.owner===owner));
  export function getRecovery():RecoveryForm|null {return recipient||due||selected.length?{kind:'request-prepare',recipient,due,owner,selected:$state.snapshot(selected)}:null;}
  export function restoreRecovery(f:RecoveryForm){if(f.kind!=='request-prepare')return;opened=true;recipient=f.recipient;due=f.due;owner=f.owner;selected=f.selected;preview='';confirmed=false;}
  async function save(){if(!confirmed)return;try{await onSave(createCollection(workspace,{id:crypto.randomUUID(),recipient:recipient.trim(),due:due||null,items:items.filter(i=>selected.includes(i.key)).map(i=>({id:crypto.randomUUID(),activityId:i.activityId,activity:i.activity,question:i.question,evidenceHint:i.evidence}))},workspace.revision,new Date().toISOString()));}catch{error='La demande n’a pas été enregistrée. Vérifiez les champs et réessayez.';}}
  function prepare(){error='';try{preview=requestText(recipient,items.filter(i=>selected.includes(i.key)).map(i=>({...i,due:due||i.due})));confirmed=false;message='';}catch{error='Indiquez le destinataire et sélectionnez entre 1 et 30 questions.';}}
  function download(){if(!confirmed)return;const url=URL.createObjectURL(new Blob([preview],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');try{a.href=url;a.download='rgpdesk-demande.txt';a.click();message='Demande téléchargée. Son envoi reste à votre initiative.';}finally{URL.revokeObjectURL(url);}}
</script>
<details class="panel request-brief" bind:open={opened}><summary><Icon name="interview"/> Préparer une demande de réponses et de pièces</summary>{#if opened}<p>Réunissez les questions pour un interlocuteur, à partir de votre travail enregistré. Aucun envoi automatique.</p>
{#if error}<p role="alert">{error}</p>{/if}{#if !preview}<form onsubmit={e=>{e.preventDefault();prepare();}}><fieldset disabled={busy}><div class="grid-two"><label class="field">Destinataire de la demande<input required maxlength="160" bind:value={recipient}/></label><label class="field">Questions affectées à<select bind:value={owner}><option value="">Tous les responsables</option>{#each owners as name}<option value={name}>{name}</option>{/each}</select></label></div><label class="field">Échéance choisie pour cette demande<input type="date" bind:value={due}/></label><p class="help">Le filtre ne sélectionne rien. Cochez uniquement les éléments utiles à ce destinataire, 30 au maximum. Les textes libres peuvent contenir des informations internes : relisez-les avant téléchargement.</p><fieldset class="choices"><legend>Questions à communiquer</legend>{#each visible as i}<label><input type="checkbox" checked={selected.includes(i.key)} disabled={!selected.includes(i.key)&&selected.length>=30} onchange={e=>selected=e.currentTarget.checked?[...selected,i.key]:selected.filter(k=>k!==i.key)}/><span><strong>{i.activity}</strong><span>{i.question}</span>{#if i.evidence}<small>À retrouver : {i.evidence}</small>{/if}{#if i.owner}<small>Suivi : {i.owner}</small>{/if}</span></label>{/each}</fieldset>{#if !visible.length}<p>Aucune question dans ce filtre.</p>{/if}<button disabled={!selected.length}>Relire la demande ({selected.length})</button></fieldset></form>
{:else}<h3>Voici le texte à transmettre</h3><pre class="request-text">{preview}</pre><label class="check"><input type="checkbox" bind:checked={confirmed}/>J’ai relu les questions, les noms et le destinataire de cette demande en clair.</label><div class="actions"><button disabled={busy||!confirmed||(workspace.collections?.length??0)>=40} onclick={save}>Conserver le suivi dans le coffre</button><button class="secondary" disabled={busy||!confirmed} onclick={download}>Télécharger la demande</button><button class="secondary" onclick={()=>{preview='';confirmed=false;}}>Modifier la sélection</button></div>{/if}{#if message}<p role="status">{message}</p>{/if}{/if}</details>
