<script lang="ts">
  import { ANALYSIS_METHOD, CONTRACT_METHOD, DEMARCO_METHOD, EDPS_NECESSITY, EDPB_PROCESSORS, REVIEW_EDITION } from "../review-methods";
  import { createDataFlow, knowledge } from "@rgpdesk/privacy-core";
  import Pictogram from "./Pictogram.svelte";
  import FlowMap from "./FlowMap.svelte";
  const example = { ...createDataFlow("00000000-0000-4000-8000-000000000001"), source: knowledge("Candidats fictifs"), destination: knowledge("Outil de recrutement fictif"), operation: knowledge("Collecte des candidatures"), data: knowledge("Coordonnées et CV"), channel: knowledge("Formulaire de candidature fictif") };
</script>
<section id="atelier-dpo" class="method-library" aria-labelledby="method-library-title">
  <header class="method-library-heading"><Pictogram kind="analysis" /><div><p class="eyebrow">L’atelier du DPO</p><h2 id="method-library-title">Passer des réponses à l’analyse.</h2><p>Un entretien fait apparaître des faits, des doutes et parfois des contradictions. Ces trames vous aident à les examiner sans transformer une case remplie en conclusion juridique.</p></div></header>
  <p class="method-caption">{REVIEW_EDITION}. Les questions sont proposées par RGPDESK. Les références distinguent le texte du règlement des repères méthodologiques.</p>
  <details class="method-guide-chapter" open><summary><span>01</span>Nécessité et proportionnalité</summary>
    <p>Dans l’application, ouvrez <strong>Analyse</strong>, choisissez une activité puis <strong>Travailler l’analyse</strong>. Décrivez les opérations et les habilitations avant d’examiner chaque question.</p>
    <div class="argument-route"><span>Faits</span><span>Preuves</span><span>Objections</span><span>Appréciation</span><span>Suites</span></div>
    <ol class="method-reference-list">{#each ANALYSIS_METHOD as question}<li><h3>{question.title}</h3><p>{question.question}</p><p class="help"><strong>Éléments à rechercher.</strong> {question.evidence}</p><a href={question.source} target="_blank" rel="noopener noreferrer">{question.reference}</a><small>{question.nature}</small></li>{/each}</ol>
    <aside class="method-boundary"><strong>Une grille n’est pas, à elle seule, une AIPD.</strong><p>L’article 35 §7 prévoit notamment la description des opérations, l’examen de leur nécessité et proportionnalité, les risques pour les droits et libertés et les mesures envisagées. Il faut aussi examiner les autres exigences applicables de l’article 35 et, le cas échéant, la consultation préalable de l’article 36. RGPDESK conserve ici vos notes d’analyse ; il ne prononce aucune conclusion à votre place.</p><a href="https://www.cnil.fr/fr/reglement-europeen-protection-donnees/chapitre4" target="_blank" rel="noopener noreferrer">Lire les articles 35 et 36 du RGPD</a></aside>
  </details>
  <details class="method-guide-chapter"><summary><span>02</span>Examiner une relation de sous-traitance</summary>
    <p>Identifiez d’abord les rôles au regard des faits. Dans <strong>Documents</strong>, ouvrez la référence de contrat, reliez les activités et intervenants concernés, puis choisissez <strong>Commencer la revue article 28</strong>. Pour chaque point, conservez le passage examiné, sa portée, vos réserves et les suites à donner.</p>
    <ol class="method-reference-list">{#each CONTRACT_METHOD as question}<li><h3>{question.title}</h3><p>{question.question}</p><p class="help"><strong>Éléments à rechercher.</strong> {question.evidence}</p><a href={question.source} target="_blank" rel="noopener noreferrer">{question.reference}</a><small>{question.nature}</small></li>{/each}</ol>
    <p>Pour les transferts, examinez aussi le <a href="https://www.cnil.fr/fr/reglement-europeen-protection-donnees/chapitre5" target="_blank" rel="noopener noreferrer">chapitre V du RGPD (articles 44 à 49)</a>.</p>
    <p>Les clauses doivent décrire le traitement dans son contexte et leur mise en œuvre. Une reprise abstraite du règlement ne remplace pas cet examen. <a href={EDPB_PROCESSORS} target="_blank" rel="noopener noreferrer">CEPD, lignes directrices 07/2020, version 2.1, §111 à 115</a>.</p>
  </details>
  <details class="method-guide-chapter"><summary><span>03</span>Construire une carte des flux utile</summary>
    <p>Dans <strong>Cartographie</strong>, sélectionnez une activité puis <strong>Compléter la cartographie</strong>. Chaque flux décrit une origine, une destination et une opération, avec les données, le canal, les lieux et les accès connus. La carte se dessine à partir de ces seules déclarations.</p>
    <figure class="guide-visual guide-flow-example"><div class="visual-kicker">Exemple fictif · un flux, des questions précises</div><FlowMap flows={[example]} /><figcaption>Les lieux et habilitations restent à examiner dans cet exemple. Leur absence ne signifie ni absence d’accès, ni absence de transfert. Les noms d’outils et d’acteurs ne suffisent pas à déduire un flux.</figcaption></figure>
    <p>Un traitement comprend notamment des opérations de collecte, consultation, utilisation, communication, rapprochement ou effacement. La distinction entre les rubriques du registre et votre analyse détaillée reste nécessaire. <a href="https://www.cnil.fr/fr/reglement-europeen-protection-donnees/chapitre1" target="_blank" rel="noopener noreferrer">RGPD, article 4 §2</a> et <a href="https://www.cnil.fr/fr/reglement-europeen-protection-donnees/chapitre4" target="_blank" rel="noopener noreferrer">article 30</a>.</p>
    <p>Les cartes, notes d’analyse et revues contractuelles sont internes au coffre et à sa sauvegarde chiffrée. Les profils de partage actuels ne les incluent pas.</p>
  </details>
  <details class="method-bibliography"><summary>Repères méthodologiques et sources</summary><ul><li><a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj/fra" target="_blank" rel="noopener noreferrer">Règlement (UE) 2016/679, texte officiel sur EUR-Lex</a>. Les liens par article ci-dessus renvoient à sa reproduction par la CNIL.</li><li><a href={EDPB_PROCESSORS} target="_blank" rel="noopener noreferrer">Comité européen de la protection des données, lignes directrices 07/2020</a>, version 2.1 du 20 septembre 2022.</li><li><a href={EDPS_NECESSITY} target="_blank" rel="noopener noreferrer">Contrôleur européen de la protection des données, guide nécessité et proportionnalité</a>, 28 janvier 2020. Repère issu de l’évaluation des mesures législatives européennes ; il ne constitue pas un formulaire universel d’AIPD.</li><li><a href={DEMARCO_METHOD} target="_blank" rel="noopener noreferrer">Estelle De Marco, support ESIEA 2025–2026</a>, pages 74 à 89 : démarche, vue d’ensemble et cas pratique d’analyse. Lecture complémentaire ; les questions de cette application sont rédigées par RGPDESK.</li></ul><p class="help">Sources consultées le 22 septembre 2026. Une recommandation méthodologique ne devient pas une obligation légale par sa présence dans ce guide.</p></details>
</section>
