export const DEMO_STEPS = [
  { panel: "register", icon: "register", title: "Partir du terrain", action: "Ouvrir le registre", text: "Quatre activités, deux rôles. Ouvrez une fiche et modifiez-la : vous explorez les vrais écrans du registre.", result: "Une activité, ses finalités, ses acteurs et ses inconnues." },
  { panel: "flows", icon: "flows", title: "Suivre les données", action: "Voir les flux", text: "Suivez la candidature jusqu’au responsable du poste, ou un événement de badge jusqu’à l’équipe sécurité.", result: "Les opérations, destinataires et accès deviennent visibles." },
  { panel: "analysis", icon: "analysis", title: "Mettre le besoin à l’épreuve", action: "Examiner la nécessité", text: "Le projet de badges contient des arguments, des objections et des éléments à demander. Lisez sa grille, puis essayez de l’enrichir.", result: "Une justification à discuter, pas une case à cocher." },
  { panel: "pia", icon: "analysis", title: "Faire l’analyse d’impact", action: "Explorer l’AIPD", text: "Deux alternatives, trois risques et leurs mesures. Ouvrez le projet de badges puis la revue conservée pour voir ce qui reste à étudier.", result: "Les effets sur les personnes, les garanties et une décision motivée." },
  { panel: "documents", icon: "documents", title: "Relier les justificatifs", action: "Examiner les documents", text: "Examinez le contrat fictif du prestataire de badges : la référence, ses limites et les questions sur les clauses restent ensemble.", result: "La présence d’un contrat ne vaut pas validation de ses garanties." },
  { panel: "actions", icon: "actions", title: "Préparer le prochain entretien", action: "Voir les actions", text: "Trois actions ont déjà un responsable fictif. Filtrez les questions, ajoutez une action ou documentez sa clôture.", result: "Des informations manquantes transformées en travail concret." },
  { panel: "delivery", icon: "delivery", title: "Montrer le résultat", action: "Préparer un partage", text: "Chargez la sélection d’exemple, relisez les rubriques, puis téléchargez le dossier. Ouvrez report.html dans le ZIP pour découvrir le rendu remis au destinataire.", result: "Un dossier HTML, CSV et JSON, limité à votre sélection." },
  { panel: "backup", icon: "backup", title: "Garder une copie chiffrée", action: "Essayer la sauvegarde", text: "Choisissez une phrase pour chiffrer une copie de cet exercice. Rien n’est enregistré dans vos coffres. La restauration est accessible depuis l’accueil.", result: "Une sauvegarde complète, distincte du dossier à partager." },
] as const;
export type DemoPanel = typeof DEMO_STEPS[number]["panel"];
