import type { DpoKind } from "@rgpdesk/privacy-core";
import { RGPD_OFFICIAL, type ReviewQuestion } from "./review-methods";
export const DPO_TITLES: Record<DpoKind, string> = { security: "Risques SI", interest: "Intérêt légitime", transfer: "Transferts", rights: "Demandes de droits", breach: "Violations" };
export const DPO_INTRO: Record<DpoKind, string> = {
  security: "Un dossier par scénario : interruption, altération ou accès indu. Reliez les activités concernées, décrivez les conséquences opérationnelles et argumentez les mesures. Les risques pour les personnes se travaillent séparément dans l’AIPD. Cette trame RGPDESK ne constitue pas une étude EBIOS RM complète.",
  interest: "Une finalité, un examen distinct. Comparez les moyens, examinez les effets sur les personnes et conservez une position argumentée.",
  transfer: "Suivez les entités, les accès et les transferts ultérieurs. Examinez le mécanisme invoqué, son efficacité dans le contexte réel et les mesures supplémentaires.",
  rights: "De la réception à la réponse : délimitez la demande, affectez le travail, préparez une réponse et consignez les éléments d’envoi.",
  breach: "Tenez la chronologie dès les premiers faits. Distinguez détection, prise de connaissance, effets sur les personnes et décisions de notification.",
};
const q = (id: string, title: string, question: string, evidence: string, reference: string, source = RGPD_OFFICIAL): ReviewQuestion => ({ id, title, question, evidence, source, reference, nature: source === RGPD_OFFICIAL ? "Texte applicable · RGPD" : "Repère méthodologique d’autorité" });
export const DPO_METHODS: Record<DpoKind, readonly ReviewQuestion[]> = {
  security: [
    q("scope", "Délimiter le scénario", "Quelle activité, quels outils et quels acteurs sont concernés ? Appuyez-vous sur les faits du registre liés à ce dossier. Précisez seulement les limites particulières à ce scénario.", "Inventaire lié, dépendances et périmètre retenu.", "RGPD, art. 32 §1 et §2"),
    q("event", "Décrire l’événement redouté", "Que pourrait-il arriver à la disponibilité, à l’intégrité ou à la confidentialité ? Décrivez un événement concret, son déroulement et les limites de vos informations.", "Retour d’expérience, architecture et observations documentées.", "RGPD, art. 32 §1 b), c) et §2"),
    q("threats", "Identifier les causes et les dépendances", "Quelles défaillances, erreurs ou actions malveillantes pourraient produire cet événement ? Quels prestataires et systèmes en propageraient les effets ?", "Flux déclarés, entretiens techniques et contrôles.", "ANSSI, démarche d’analyse des risques", "https://cyber.gouv.fr/securisation/analyse-des-risques/methode-ebios-rm/"),
    q("impact", "Argumenter les conséquences sur l’activité", "Quelles missions seraient perturbées, pendant combien de temps et avec quelles conséquences ? Définissez votre échelle si vous en utilisez une. Identifiez séparément les effets sur les personnes à examiner dans l’AIPD.", "Besoins métiers, engagements, dépendances et hypothèses.", "ANSSI, événements redoutés et gravité", "https://cyber.gouv.fr/securisation/analyse-des-risques/methode-ebios-rm/"),
    q("likelihood", "Motiver la vraisemblance", "Sur quels faits repose votre appréciation de la possibilité de ce scénario ? Indiquez la période et les incertitudes. Aucun chiffre ou niveau n’est déduit automatiquement.", "Exposition, incidents connus, contrôles et limites des essais.", "ANSSI, appréciation des risques", "https://cyber.gouv.fr/securisation/analyse-des-risques/methode-ebios-rm/"),
    q("measures", "Vérifier les mesures", "Quelles mesures préviennent, détectent ou limitent cet événement ? Distinguez ce qui est prévu, déployé et testé, notamment la restauration et le rétablissement.", "Références de procédures, résultats de tests et responsables.", "RGPD, art. 32 §1 c) et d)"),
    q("residual", "Réexaminer le scénario après mesures", "Que reste-t-il possible, avec quelles conséquences ? Expliquez l’effet réel des garanties, leur dépendance et leur éventuelle défaillance.", "Résultats observés, réserves et argument de réduction du risque.", "RGPD, art. 32 §1 et §2"),
    q("decision", "Faire décider et organiser le suivi", "Qui retient quelle position, pour quel périmètre et avec quelles réserves ? Qui vérifie les correctifs et quels changements imposeraient un réexamen ?", "Position motivée, responsable, échéance et actions reliées.", "RGPD, art. 24 et 32"),
  ],
  interest: [
    q("interest", "Identifier l’intérêt poursuivi", "Qui poursuit quel intérêt ? Est-il licite, précis, réel et actuel ? Examinez le contexte et la situation de l’organisme, notamment les missions d’une autorité publique.", "Bénéficiaires, finalité, contexte, textes et éléments factuels.", "RGPD, art. 6 §1 f) et considérant 47"),
    q("necessity", "Mettre les moyens en concurrence", "Ces opérations sont-elles nécessaires à cet intérêt ? Comparez une absence de traitement et des moyens aussi efficaces portant moins atteinte aux personnes. Motivez les options écartées.", "Opérations et flux du registre, options, essais, efficacité et incertitudes.", "RGPD, art. 6 §1 f)"),
    q("balance", "Examiner les personnes et leurs attentes", "Quelles conséquences pour les intérêts, droits et libertés des personnes ? Examinez attentes raisonnables, vulnérabilité, relation avec l’organisme, nature des données et effets cumulés.", "Situation des personnes, ampleur des effets, objections, droits et garanties.", "RGPD, art. 6 §1 f), considérants 47 et 75"),
    q("safeguards", "Éprouver les garanties additionnelles", "Quelles garanties limitent effectivement les atteintes ? Distinguez obligations ordinaires et mesures additionnelles. Vérifiez information, opposition, et si concernés articles 9 et 10.", "Mesures, tests, modalités d’opposition et références datées.", "RGPD, art. 9, 10, 13, 14 et 21"),
    q("decision", "Motiver la position et son réexamen", "Que conclut le responsable sur les trois conditions ? Quelles réserves empêchent encore de retenir ce fondement ? Quels changements imposent un nouvel examen ?", "Avis du DPO, décision du responsable, alternatives et suites assignées.", "CNIL, intérêt légitime · méthode et changements de contexte", "https://www.cnil.fr/fr/les-bases-legales/interet-legitime"),
  ],
  transfer: [
    q("scope", "Délimiter le transfert et l’analyse", "Quelles opérations constituent un transfert ? Pourquoi une analyse d’impact du transfert est-elle requise ou non dans le cas examiné ? Distinguez cette question de la licéité du traitement.", "Périmètre, finalités, données, personnes, fréquence et flux.", "RGPD, art. 44 à 49"),
    q("actors", "Identifier toute la chaîne", "Qui exporte, reçoit, héberge ou accède à distance ? Dans quels pays et pour quelles opérations ? Incluez sous-traitants ultérieurs et transferts suivants.", "Entités juridiques, rôles, lieux d’accès, chaîne contractuelle et documents datés.", "RGPD, art. 28 et 44"),
    q("instrument", "Vérifier le mécanisme invoqué", "Quel mécanisme est invoqué, et couvre-t-il exactement l’entité, les données et l’usage ? Vérifiez sa validité et son champ à la date de votre examen. Aucun pays n’est présumé adéquat par cet outil.", "Décision, clauses, annexes, engagements et champ ; conditions précises d’une éventuelle dérogation.", "RGPD, art. 45 à 49"),
    q("country", "Examiner le droit et les pratiques", "Les lois et pratiques pertinentes peuvent-elles affecter l’efficacité des garanties ? Examinez les accès des autorités, les recours et les limites des éléments disponibles.", "Sources primaires datées, analyse du pays, expérience documentée et incertitudes.", "CNIL, guide AITD, étapes 1 à 3", "https://www.cnil.fr/sites/cnil/files/2025-02/guide_aitd_pdf.pdf"),
    q("measures", "Comparer les mesures supplémentaires", "Quelles mesures techniques, contractuelles et organisationnelles répondent aux lacunes identifiées ? Qui détient les clés et qui peut accéder aux données lisibles ?", "Architecture, tests, clauses et limites effectives de chaque mesure.", "CNIL, guide AITD, étape 4", "https://www.cnil.fr/sites/cnil/files/2025-02/guide_aitd_pdf.pdf"),
    q("implementation", "Vérifier la mise en œuvre", "Quelles formalités et mesures sont réalisées, par qui et avec quelles preuves ? Une mesure prévue ou un contrat référencé ne suffisent pas à démontrer leur efficacité.", "Dates, responsables, contrôles, résultats et écarts.", "CNIL, guide AITD, étape 5", "https://www.cnil.fr/sites/cnil/files/2025-02/guide_aitd_pdf.pdf"),
    q("decision", "Décider et surveiller les changements", "Quelle position motivée retient l’exportateur ? Que faut-il suspendre, modifier ou réexaminer ? Qui suit les changements de droit, d’entités, de finalités ou de garanties ?", "Décision, réserves, alternatives, responsable et date de réexamen.", "CNIL, guide AITD, étape 6", "https://www.cnil.fr/sites/cnil/files/2025-02/guide_aitd_pdf.pdf"),
  ],
  rights: [
    q("request", "Qualifier la demande reçue", "Quel droit est exercé, auprès de quel responsable, pour quel périmètre ? Utilisez une référence de dossier et conservez les coordonnées nécessaires dans votre circuit sécurisé.", "Date de réception, canal, demande résumée, régime applicable et rôle de l’organisme.", "RGPD, art. 12 et 15 à 22"),
    q("identity", "Proportionner la vérification d’identité", "Existe-t-il un doute raisonnable sur l’identité ou le mandat ? Quel élément strictement nécessaire permet de le lever ? Ne demandez pas systématiquement une pièce d’identité et n’en stockez pas ici.", "Motif du contrôle, méthode, résultat déclaré et réserves ; aucune copie de pièce.", "RGPD, art. 12 §6"),
    q("scope", "Délimiter les informations recherchées", "Quels traitements, systèmes et organismes sont concernés ? Quelles précisions sont nécessaires ? Aucun échange ne suspend automatiquement le délai dans RGPDESK.", "Activités liées, périmètre, échanges et analyse d’un éventuel régime particulier.", "RGPD, art. 12 et 15 à 22"),
    q("search", "Organiser les recherches et les suites", "Qui interroge quels systèmes et prestataires ? Quelles opérations sont nécessaires pour répondre au droit effectivement exercé ?", "Responsables, demandes d’assistance, résultats et opérations réalisées.", "RGPD, art. 19 et 28 §3 e)"),
    q("exceptions", "Motiver les limites éventuelles", "Existe-t-il une restriction applicable, une atteinte aux droits de tiers ou un motif de refus ? Examinez sa portée sans refus automatique et justifiez chaque occultation.", "Texte applicable, analyse individualisée, tiers et motivation.", "RGPD, art. 12 §4 et §5, 15 §4 et 23"),
    q("response", "Préparer une réponse compréhensible", "Rédigez votre projet dans l’appréciation ci-dessous : suites données, informations pertinentes, limites motivées et voies de recours si nécessaires. La réponse n’est ni générée juridiquement ni envoyée automatiquement.", "Projet relu, destinataire vérifié, mode de remise sécurisé et pièces conservées hors de l’application.", "RGPD, art. 12"),
    q("dispatch", "Consigner l’envoi et la clôture", "Qu’a-t-on réellement transmis, quand, par quel canal et avec quel justificatif ? Quelles suites restent ouvertes ? Un téléchargement ou une saisie n’est pas une preuve de réception.", "Références d’envoi, date, contenu transmis, retour et décision de clôture.", "RGPD, art. 5 §2 et 12"),
  ],
  breach: [
    q("facts", "Séparer les faits des hypothèses", "Que s’est-il passé ? Distinguez perte de confidentialité, intégrité et disponibilité, détection et prise de connaissance. Conservez les événements successifs dans la chronologie.", "Faits datés, sources, périmètre, confirmations et incertitudes ; pas de logs bruts.", "RGPD, art. 4 §12 et 33 §5"),
    q("scope", "Décrire les personnes et les données", "Quelles catégories de personnes et d’enregistrements sont concernées ? Quels volumes approximatifs sont connus et quelles informations manquent encore ?", "Catégories, estimations justifiées, traitements, prestataires et point de contact.", "RGPD, art. 33 §3"),
    q("consequences", "Apprécier les effets pour les personnes", "Quelles conséquences sont plausibles, avec quelle gravité et vraisemblance ? Examinez vulnérabilité, identification et possibilités d’usage des données. Un risque inconnu n’est pas un risque absent.", "Scénarios, conséquences, garanties réellement efficaces et réserves.", "RGPD, art. 33 et 34"),
    q("containment", "Documenter les mesures", "Qu’a-t-on contenu ou corrigé ? Quelles mesures sont prévues, réalisées ou vérifiées, par qui et quand ?", "Mesures, efficacité, limites, responsables et suites.", "RGPD, art. 33 §3 d) et §5"),
    q("authority", "Motiver la notification à l’autorité", "Quelle décision prend le responsable et sur quels motifs ? Préparez le contenu, consignez notification initiale, compléments et éventuel retard. Sous-traitant : informez le responsable dans les meilleurs délais ; le repère 72 heures ne vous est pas attribué automatiquement.", "Qualification, autorité compétente, décision, références d’envoi et compléments attendus.", "RGPD, art. 33"),
    q("people", "Examiner l’information des personnes", "Le risque élevé justifie-t-il une communication aux personnes ? Examinez les conditions d’une éventuelle exception et motivez votre position. Préparez une information claire et utile.", "Appréciation, garanties, projet de communication, décision et envoi déclaré.", "RGPD, art. 34"),
    q("followup", "Conserver les suites et les enseignements", "Quelles actions évitent une répétition ? Conservez aussi les violations non notifiées et leurs motifs. Qui vérifie les correctifs et réexamine la situation ?", "Actions, responsables, échéances, résultats et clôture motivée.", "RGPD, art. 33 §5 et 32"),
  ],
};
