// Editorial prompts only: never copied into a vault, a review or an export.
// Adapted from Estelle De Marco's guides (CC BY 4.0); supplied examples excluded.
export interface MethodHint { icon: string; points: readonly string[]; guide: string; reference: string }
export type MethodHintKind = "rgpd" | "necessity";
export const METHOD_HINT_EDITION = "Aides de lecture · 23 septembre 2026";
export const METHOD_GUIDES = {
  rgpd: { title: "Guide d’analyse RGPD", version: "1.0", sheet: "ET1 analyse RGPD" },
  necessity: { title: "Guide d’analyse de nécessité et de proportionnalité", version: "1.2 du 20 septembre 2026", sheet: "Analyse N & P" },
} as const;
export const METHOD_HINTS: Record<MethodHintKind, Readonly<Record<string, MethodHint>>> = {
  rgpd: {
    objective: { icon: "target", guide: "CR1, CR2", reference: "RGPD · art. 2, 3, 5 §1 b), 6 §4",
      points: ["Distinguez le champ matériel et territorial du RGPD du choix d’une règle nationale applicable. Une localisation ne suffit pas, à elle seule, à trancher ces questions.", "Pour un nouvel usage, examinez le lien entre les finalités, le contexte de collecte, les attentes raisonnables, la nature des données, les conséquences et les garanties. Motivez le régime applicable avant de conclure à la compatibilité.", "Rattachez chaque opération et chaque accès à la finalité déjà décrite dans le registre. Complétez le raisonnement ici sans recopier l’inventaire."] },
    lawfulness: { icon: "balance", guide: "CR3, CR4", reference: "RGPD · art. 6 à 10",
      points: ["Examinez les conditions concrètes du fondement envisagé par finalité. Un intitulé ou un contrat ne suffit pas à les établir.", "Si le consentement est envisagé, vérifiez notamment sa liberté, sa précision, l’information, la preuve et les conditions de retrait ; examinez le cas des enfants lorsqu’il est pertinent.", "Pour l’intérêt légitime, distinguez l’intérêt poursuivi, la nécessité du traitement et la mise en balance. Incluez les attentes, la vulnérabilité, les effets, les garanties et les arguments opposés.", "L’examen des catégories particulières et des données relatives aux infractions s’ajoute à celui de l’article 6 ; il ne le remplace pas."] },
    effectiveness: { icon: "flows", guide: "CR2, CR5", reference: "RGPD · art. 5 §1 b), c), d) et §2",
      points: ["Pour une donnée ou une opération, expliquez son utilité dans l’usage décrit. Distinguez constat, déclaration d’un interlocuteur et hypothèse.", "Examinez l’adéquation, la pertinence et l’exactitude séparément : une donnée exacte peut être inutile à la finalité.", "Si une preuve manque, indiquez où la rechercher et qui peut la fournir, sans transformer l’absence de preuve en conclusion favorable."] },
    alternatives: { icon: "eye", guide: "CR6", reference: "RGPD · art. 5 §1 c), 25 §1 et §2",
      points: ["Examinez aussi les sources de collecte, les destinataires, les habilitations et les usages par défaut.", "Comparez une restriction d’accès, une réduction des données ou une autre organisation du service. Conservez les raisons concrètes du choix.", "Un lien vers un intervenant ne décrit pas son accès : précisez cet accès dans les flux existants."] },
    minimisation: { icon: "clock", guide: "CR5, CR6", reference: "RGPD · art. 5 §1 c), d), e), 25 §2",
      points: ["Distinguez la durée, son événement déclencheur et la procédure qui l’applique. Examinez les copies, archives et exceptions.", "Documentez comment une correction est propagée et comment l’effacement est vérifié.", "Ne déduisez aucune durée standard : rattachez le choix à la finalité et aux références applicables."] },
    rights: { icon: "security", guide: "CR8, CR9", reference: "RGPD · art. 24, 25, 32",
      points: ["Reliez les événements affectant la confidentialité, l’intégrité ou la disponibilité à leurs conséquences concrètes pour les personnes.", "Appréciez probabilité et gravité dans le contexte réel, avec les incertitudes et les éléments disponibles. La sécurité des données ne se limite pas aux attaques informatiques.", "L’article 32 prend en compte les risques pour les droits et libertés même sans AIPD obligatoire. Il ne prescrit pas pour chaque traitement une méthode unique ni une matrice chiffrée."] },
    safeguards: { icon: "rights", guide: "CR7, CR9 à CR13", reference: "RGPD · art. 12 à 22, 26 à 29, 32, 37 à 39, 44 à 49",
      points: ["Distinguez collecte directe et indirecte : contenu de l’information, moment, accès effectif et exception éventuellement invoquée.", "Examinez l’exercice réel des droits : retrait, accès, rectification, effacement, limitation, portabilité, opposition, notifications et décisions automatisées selon les conditions applicables.", "Retrouvez les contrôles des prestataires, des transferts et des habilitations dans leurs dossiers. Citez les éléments utiles ici sans recréer ces dossiers.", "Séparez la mesure prévue, sa mise en œuvre et la vérification de son efficacité ; identifiez le responsable et les moyens de la faire durer."] },
    conclusion: { icon: "actions", guide: "CR14", reference: "RGPD · art. 5 §2, 24 §1, 32 §1 d)",
      points: ["Distinguez les mesures à maintenir, celles à corriger et les informations encore attendues.", "Affectez les suites dans Actions & décisions : responsable, échéance, moyens et élément attendu pour vérifier la réalisation.", "Après décision, mettez à jour les faits concernés dans le registre et prévoyez les événements qui déclencheront un réexamen."] },
  },
  necessity: {
    objective: { icon: "target", guide: "CC1 · 1-1.1, 1-1.2, 1-1.4 à 1-1.6", reference: "Guide De Marco · besoin et finalité",
      points: ["Quel besoin concret motive la mesure, avec quelle importance, quelle actualité et quelle urgence ? Distinguez ces trois appréciations et leurs preuves.", "Quels usages ultérieurs sont prévus, pour quels besoins et quelles finalités ? Appuyez-vous sur l’inventaire existant.", "Quelles observations contredisent l’existence ou l’importance du besoin ? Répondez-y ou conservez explicitement l’incertitude."] },
    lawfulness: { icon: "balance", guide: "CC1 · 1-1.3 ; introduction, B8 à B19", reference: "CEDH et Charte · champ applicable à examiner",
      points: ["Distinguez le fondement du traitement au titre du RGPD de la justification d’une limitation d’un droit fondamental.", "Identifiez les droits concernés, le cadre applicable et les motifs admis pour les limiter. Citez les dispositions et la jurisprudence pertinentes au contexte, sans transposer automatiquement une règle propre à l’action publique.", "Reliez l’examen RGPD déjà réalisé ; consignez ici le raisonnement complémentaire et ses réserves."] },
    effectiveness: { icon: "analysis", guide: "CC1 · 1-2.1 à 1-2.3", reference: "Guide De Marco · réponse appropriée",
      points: ["Quels résultats établissent l’efficacité attendue, avec quelles limites ? Une intuition ou une promesse commerciale reste une hypothèse.", "Quelles mesures existent déjà, quels sont leurs résultats et pourquoi ne suffisent-elles pas ?", "Quel apport supplémentaire de la nouvelle mesure est démontré ? Examinez aussi les données ou opinions contraires."] },
    alternatives: { icon: "flows", guide: "CC2 · 2-3", reference: "Guide De Marco · autres moyens praticables",
      points: ["Comparez des moyens praticables qui poursuivent la même finalité, y compris une option moins intrusive ou sans traitement lorsque c’est envisageable.", "Justifiez l’efficacité et les limites de chaque option ; une contrainte supposée ne suffit pas à écarter une alternative.", "Utilisez le tableau des alternatives de cet atelier pour conserver la comparaison, puis citez son résultat dans l’appréciation."] },
    minimisation: { icon: "eye", guide: "CC2 · 2-2.1 à 2-2.6", reference: "Guide De Marco · étendue des limitations",
      points: ["Examinez les lieux, les sources, les personnes, le volume, les accès, les circonstances d’usage et la durée de la limitation.", "Reliez chaque limite aux finalités et flux déjà décrits. Examinez les paramètres réels, pas seulement la procédure annoncée.", "La mesure laisse-t-elle un exercice effectif du droit concerné ? Identifiez les restrictions qui videraient ce droit de sa substance."] },
    rights: { icon: "rights", guide: "CC2 · 2-1.1 à 2-1.4 ; CC3", reference: "Guide De Marco · contexte et effets sur les libertés",
      points: ["Examinez les attentes de confidentialité, l’âge, la vulnérabilité, la capacité d’adaptation et la possibilité réelle de refuser.", "Identifiez les comportements légitimes affectés et l’importance des droits limités, y compris lorsque l’outil fonctionne comme prévu.", "Comparez les bénéfices établis aux atteintes et à leur contexte. L’absence de fuite de données ne démontre pas, à elle seule, la proportionnalité."] },
    safeguards: { icon: "evidence", guide: "CC4 · 4-1 et 4-2", reference: "Guide De Marco · effectivité des garanties",
      points: ["Quels engagements encadrent réellement la mesure ? Examinez leur portée, leur clarté, leur précision, leur accessibilité et leur stabilité.", "Pour chaque correctif, identifiez les moyens techniques, juridiques, humains et financiers nécessaires, ainsi que le contrôle de sa réalisation.", "Distinguez les garanties existantes et vérifiées des promesses. Consignez les responsables, les échéances et les tests dans Mesures."] },
    conclusion: { icon: "balance", guide: "CC3, CC4", reference: "Guide De Marco · bilan et suites",
      points: ["Mettez en regard les bénéfices démontrés, les limitations de droits, les alternatives et les garanties. Ne remplacez pas ce raisonnement par un score.", "Distinguez les objections résolues de celles qui restent ouvertes et expliquez les conditions de votre position.", "Reliez les correctifs aux décisions et prévoyez le contrôle de leur mise en œuvre ainsi que les changements imposant une nouvelle analyse."] },
  },
};
