import type { ReviewNote } from "@rgpdesk/privacy-core";

export interface ReviewQuestion {
  id: string; title: string; question: string; evidence: string;
  source: string; reference: string; nature: string;
}
const principles = "https://www.cnil.fr/fr/reglement-europeen-protection-donnees/chapitre2";
const responsibilities = "https://www.cnil.fr/fr/reglement-europeen-protection-donnees/chapitre4";
export const REVIEW_EDITION = "Questions RGPDESK · 22 septembre 2026";
export const EDPB_PROCESSORS = "https://www.edpb.europa.eu/system/files/2023-10/EDPB_guidelines_202007_controllerprocessor_final_en.pdf";
export const EDPS_NECESSITY = "https://www.edps.europa.eu/sites/default/files/publication/20-01-28_edps_quickguide_en.pdf";
export const DEMARCO_METHOD = "https://www.inthemis.fr/ressources/supports/Esiea_Ethique_202601_v2.12.pdf#page=75";
const law = (reference: string, source = responsibilities) => ({ reference: `RGPD · ${reference}`, source, nature: "Texte du règlement reproduit par la CNIL" });

// These are product-authored interview questions, not quotations or legal conclusions.
// Sources identify the requirement or methodological point that the question examines.
export const ANALYSIS_METHOD: readonly ReviewQuestion[] = [
  { id: "objective", title: "Définir le résultat recherché", question: "Quel résultat concret justifie chaque opération ? Rattachez-le à une finalité précise. Distinguez l’objectif de l’outil utilisé et les usages ultérieurs envisagés.", evidence: "Description métier, finalités de la fiche, demande à l’origine du traitement, usages prévus et exclus.", ...law("art. 5 §1 b) et §2", principles) },
  { id: "lawfulness", title: "Motiver le fondement juridique", question: "Pour chaque finalité dont votre organisme est responsable, quel fondement de l’article 6 retenez-vous et pourquoi ses conditions sont-elles réunies ? Examinez séparément, si concernés, les articles 9 et 10. Sous-traitant : décrivez votre mandat et les questions à soumettre au responsable.", evidence: "Texte applicable, analyse du contexte et de la portée, référence aux instructions ou à l’examen du fondement retenu. Aucun choix par défaut.", ...law("art. 6, 9 et 10", principles) },
  { id: "effectiveness", title: "Établir l’utilité réelle", question: "Sur quels faits repose l’idée que cette opération permet d’atteindre l’objectif ? Distinguez résultats observés, hypothèses et éléments qui contredisent l’utilité attendue.", evidence: "Observation métier, étude ou test existant, incertitudes et limites de la démonstration.", source: EDPS_NECESSITY, reference: "Contrôleur européen (EDPS) · guide nécessité / proportionnalité, étapes 1, 3 et 5", nature: "Repère méthodologique conçu pour l’évaluation des mesures législatives de l’UE ; question adaptée au travail du DPO" },
  { id: "alternatives", title: "Comparer les autres moyens", question: "Peut-on atteindre le même objectif avec moins de données, moins d’accès ou une méthode moins intrusive ? Décrivez les options étudiées, leur efficacité attendue et les raisons vérifiables de votre choix.", evidence: "Options comparées, essai disponible, contraintes établies et hypothèses restant à vérifier.", source: EDPS_NECESSITY, reference: "Contrôleur européen (EDPS) · guide nécessité / proportionnalité, étape 4", nature: "Repère méthodologique ; comparaison proposée par RGPDESK, sans conclusion automatique" },
  { id: "minimisation", title: "Justifier l’étendue du traitement", question: "Pourquoi ces catégories de données, ces personnes, ces destinataires et ces durées sont-ils nécessaires à cette finalité ? Examinez aussi les accès par défaut et les copies intermédiaires.", evidence: "Inventaire par finalité, habilitations, configuration, règle de conservation et modalités effectives de suppression.", ...law("art. 25 §2") },
  { id: "rights", title: "Examiner les effets sur les personnes", question: "Quels effets l’usage prévu peut-il avoir sur la vie privée et les autres droits ? Considérez le contexte, les personnes vulnérables, les rapprochements de données et les possibilités réelles d’exercer les droits. Ne limitez pas cet examen à une fuite informatique.", evidence: "Situations concrètes, attentes exprimées, parcours d’information et d’exercice des droits, observations contradictoires.", ...law("art. 24 §1, art. 35 §7 c)") },
  { id: "safeguards", title: "Vérifier les garanties", question: "Quelles mesures répondent aux effets identifiés ? Distinguez ce qui fonctionne aujourd’hui de ce qui est prévu. Pour chaque mesure, précisez qui la met en œuvre et comment son efficacité sera vérifiée.", evidence: "Procédure appliquée, test daté, référence documentaire, responsable et action à réaliser.", ...law("art. 25, art. 32 §1 d), art. 35 §7 d)") },
  { id: "conclusion", title: "Motiver la position et les suites", question: "Au vu des faits et des objections, quelle appréciation humaine portez-vous sur la nécessité et la proportionnalité ? Consignez les réserves, les correctifs, les avis à obtenir et les changements qui imposeraient un nouvel examen.", evidence: "Justification datée, auteur et périmètre de la décision dans Actions & décisions ; correctifs avec responsable et échéance.", ...law("art. 24 §1, art. 35 §7 b) et §11") },
];

export const CONTRACT_METHOD: readonly ReviewQuestion[] = [
  { id: "scope", title: "Périmètre et caractère contraignant", question: "Le contrat ou l’acte écrit lie-t-il les parties et décrit-il l’objet, la durée, la nature, la finalité, les données, les personnes concernées ainsi que les droits et obligations du responsable ?", evidence: "Version applicable, parties, référence de la clause et annexes décrivant la prestation.", ...law("art. 28 §3 et §9") },
  { id: "instructions", title: "Instructions, y compris les transferts", question: "Où sont définies les instructions documentées et leurs modifications ? Comment le prestataire traite-t-il une obligation légale de traitement, notamment l’information du responsable sous les réserves prévues par le texte ?", evidence: "Clause, circuit d’instruction, annexes de localisation et de transfert. Le contrat article 28 ne suffit pas à encadrer un transfert du chapitre V.", ...law("art. 28 §3 a)") },
  { id: "confidentiality", title: "Confidentialité des personnes autorisées", question: "Qu’est-ce qui encadre la confidentialité des personnes autorisées à traiter les données ?", evidence: "Clause et dispositif d’engagement ou obligation légale applicable ; périmètre des accès.", ...law("art. 28 §3 b)") },
  { id: "security", title: "Mesures de sécurité adaptées", question: "Les mesures applicables à cette prestation sont-elles décrites et vérifiables ? Leur portée couvre-t-elle les opérations et données réellement confiées ?", evidence: "Annexe de sécurité, périmètre, tests disponibles et écarts à traiter.", ...law("art. 28 §3 c), art. 32") },
  { id: "subprocessors", title: "Sous-traitants ultérieurs", question: "Comment sont recueillies les autorisations préalables, annoncés les changements et exercées les objections en cas d’autorisation générale ? Quelles obligations sont imposées aux sous-traitants ultérieurs ?", evidence: "Liste datée, procédure d’information, autorisation et clauses répercutées.", ...law("art. 28 §2, §3 d) et §4") },
  { id: "rights", title: "Assistance à l’exercice des droits", question: "Comment le prestataire aide-t-il le responsable à traiter les demandes des personnes, compte tenu de la nature du traitement ?", evidence: "Clause d’assistance, interlocuteur, modalités pratiques et capacité démontrée.", ...law("art. 28 §3 e)") },
  { id: "assistance", title: "Sécurité, violations et analyses d’impact", question: "Quelle assistance est prévue pour les obligations des articles 32 à 36 ? Le circuit d’information sur une violation permet-il d’avertir le responsable dans les meilleurs délais ?", evidence: "Clauses, contacts d’incident, procédure de notification et assistance à l’AIPD ou à la consultation préalable.", ...law("art. 28 §3 f), art. 33 §2") },
  { id: "termination", title: "Sort des données en fin de prestation", question: "Comment le choix du responsable entre restitution et suppression est-il mis en œuvre, y compris pour les copies ? Quelles obligations légales de conservation peuvent s’appliquer ?", evidence: "Clause de réversibilité, procédure, périmètre des copies et éléments de vérification attendus.", ...law("art. 28 §3 g)") },
  { id: "audit", title: "Informations, audit et inspections", question: "Quels moyens donnent au responsable les informations nécessaires et permettent les audits, y compris les inspections ? Les modalités prévues rendent-elles ce contrôle praticable ?", evidence: "Clause, modalités d’accès aux informations, rapports disponibles et limites à examiner.", ...law("art. 28 §3 h)") },
  { id: "unlawful", title: "Alerte sur une instruction illicite", question: "Comment le prestataire informe-t-il immédiatement le responsable lorsqu’une instruction lui paraît contraire au RGPD ou aux autres règles européennes ou nationales de protection des données ?", evidence: "Clause et procédure de remontée vers l’interlocuteur compétent.", ...law("art. 28 §3, dernier alinéa") },
  { id: "guarantees", title: "Garanties examinées dans la durée", question: "Quels éléments concrets permettent d’apprécier les garanties de ce prestataire pour cette prestation ? Quel suivi est prévu si la prestation, les mesures ou les sous-traitants évoluent ?", evidence: "Documentation technique, expérience et moyens, rapports ou certifications avec leur périmètre ; date de contrôle et réserves. Aucun logo ne clôt l’examen.", source: EDPB_PROCESSORS, reference: "CEPD · lignes directrices 07/2020, version 2.1, §95 à 99 ; RGPD art. 28 §1", nature: "Interprétation du CEPD ; les modalités d’examen restent adaptées au contexte" },
];
export const hasNotes = (note: ReviewNote): boolean => [note.facts, note.evidence, note.objections, note.assessment, note.followUp].some((field) => field.state === "documented");
