import {describe,it,expect} from 'vitest';
import {createWorkspace,createActivity,unknown,knowledge,createCollection,addCollectionReply,applyCollectionReply,closeCollection,reviseWorkspace,assertWorkspace,migrateWorkspace,matchingReferences,citeEvidence,reviewTargets,compareDeliveries,projectShare,createPurpose,createDataFlow,type EvidenceReference,type Workspace} from '../src/index';
let seq=910000;const id=()=>`00000000-0000-4000-8000-${String(seq++).padStart(12,'0')}`,at='2026-09-24T08:00:00.000Z';
function fixture(){const w=createWorkspace(id(),'Organisme fictif',at),a=createActivity(w.id,id(),'controller'),b=createActivity(w.id,id(),'controller');a.title='Recrutement';b.title='Relation client';w.activities=[a,b];const doc:EvidenceReference={id:id(),workspaceId:w.id,title:'PRIVATE_REFERENCE',category:'other',activityIds:[],purposeIds:[],partyIds:[],scope:'Fictif',version:'1',declaredAuthor:'',internalRef:'PRIVATE_PATH',publicReference:'',reservations:'',sensitivity:'internal',status:'declared',reviewedRevision:null,reviewedAt:null,reviewDue:null,audience:'',channel:'',availability:unknown(),contractReview:null};w.documents=[doc];return{w,a,b,doc};}
function requested(w:Workspace){return createCollection(w,{id:id(),recipient:'PRIVATE_RECIPIENT',due:'2026-10-01',items:[{id:id(),activityId:w.activities[0]!.id,activity:'Recrutement',question:'PRIVATE_QUESTION',evidenceHint:'PRIVATE_PIECE'}]},w.revision,at);}
function answered(w:Workspace){const r=w.collections![0]!;return addCollectionReply(w,r.id,r.items[0]!.id,{id:id(),author:'PRIVATE_AUTHOR',text:'PRIVATE_REPLY',documentIds:[w.documents[0]!.id]},w.revision,at);}
const share=(w:Workspace)=>projectShare(w,{profile:'internal-review',recipient:'Direction fictive',scope:'Périmètre choisi',reservations:[],activityIds:w.activities.map(a=>a.id),documentIds:[],clientId:null},id,at);
describe('tracked requests remain explicit and private',()=>{
 it('migrates v7 only in memory, retains every original field and rejects unknown properties',()=>{const{w}=fixture(),old={...w,format:'rgpd-master-v7'},bytes=JSON.stringify(old);expect(migrateWorkspace(old)).toEqual(w);expect(JSON.stringify(old)).toBe(bytes);expect(()=>migrateWorkspace({...old,collections:[]})).toThrow('INVALID');expect(()=>migrateWorkspace({...old,extra:true})).toThrow('INVALID');});
 it('retains the request and reply without changing facts, then applies one selected field in one revision',()=>{let w=answered(requested(fixture().w));const r=w.collections![0]!,i=r.items[0]!,reply=i.replies[0]!;expect(w.activities[0]!.dataSubjects).toEqual(unknown());const before=JSON.stringify(w),n=applyCollectionReply(w,r.id,i.id,reply.id,'dataSubjects',unknown(),'DPO fictif',w.revision,at);expect(n.revision).toBe(w.revision+1);expect(n.activities[0]!.dataSubjects).toEqual(knowledge('PRIVATE_REPLY'));expect(n.activities[0]!.recipients).toEqual(unknown());expect(n.activities[0]!.analysis).toEqual(w.activities[0]!.analysis);expect(n.collections![0]!.items[0]!.replies[0]!.application?.before).toEqual(unknown());expect(JSON.stringify(w)).toBe(before);w=n;expect(()=>applyCollectionReply(w,r.id,i.id,reply.id,'dataSubjects',unknown(),'DPO',w.revision,at)).toThrow('CONFLICT');});
 it('refuses stale revisions, changed facts, legal fields and replies without an activity',()=>{let w=answered(requested(fixture().w));const r=w.collections![0]!,i=r.items[0]!,reply=i.replies[0]!;const apply=(field='dataSubjects',before=unknown(),revision=w.revision)=>applyCollectionReply(w,r.id,i.id,reply.id,field as 'dataSubjects',before,'DPO',revision,at);expect(()=>apply('dataSubjects',unknown(),1)).toThrow('CONFLICT');expect(()=>apply('legalBasis')).toThrow('INVALID');expect(()=>apply('constructor')).toThrow('INVALID');w=reviseWorkspace(w,w.revision,at,{activities:w.activities.map(a=>({...a,dataSubjects:knowledge('New fact')}))});expect(()=>apply()).toThrow('CONFLICT');i.activityId=null;expect(()=>applyCollectionReply({...w,collections:[r]},r.id,i.id,reply.id,'recipients',unknown(),'DPO',w.revision,at)).toThrow('CONFLICT');});
 it('preserves original questions, replies, applications and closure history',()=>{let w=answered(requested(fixture().w));for(const mutation of ['remove','question','reply']){const copy=structuredClone(w.collections!);if(mutation==='remove')copy.pop();else if(mutation==='question')copy[0]!.items[0]!.question='rewrite';else copy[0]!.items[0]!.replies[0]!.text='rewrite';expect(()=>reviseWorkspace(w,w.revision,at,{collections:copy})).toThrow('INVALID');}const r=w.collections![0]!;w=closeCollection(w,r.id,'DPO','Réponse conservée, portée restant à vérifier',w.revision,at);expect(()=>answered(w)).toThrow('CONFLICT');expect(()=>reviseWorkspace(w,w.revision,at,{collections:w.collections!.map(r=>({...r,closed:null}))})).toThrow('INVALID');});
 it('rejects foreign references, duplicate IDs, oversized and malformed inputs',()=>{const w=requested(fixture().w),r=w.collections![0]!,item=r.items[0]!;for(const patch of [{documentIds:[id()]},{text:'x'.repeat(4001)},{author:' '},{id:item.id},{documentIds:[w.documents[0]!.id,w.documents[0]!.id]},{text:'\u202ehidden'}])expect(()=>addCollectionReply(w,r.id,item.id,{id:id(),author:'Fictif',text:'Réponse',documentIds:[],...patch},w.revision,at)).toThrow('INVALID');expect(()=>createCollection(w,{id:id(),recipient:'x',due:'2026-02-30',items:[]},w.revision,at)).toThrow('INVALID');const bad={...w,collections:w.collections!.map(r=>({...r,url:'https://example.invalid'}))};expect(()=>assertWorkspace(bad)).toThrow('INVALID');});
 it('excludes all request history from the unchanged positive share projection',()=>{const w=answered(requested(fixture().w)),s=share(w);expect(JSON.stringify(s)).not.toMatch(/PRIVATE_|collections|receivedAt/);});
});
describe('reuse references without files or copied conclusions',()=>{
 it('matches hash plus size, excludes the current reference, and does not infer a legal review',()=>{const{w,doc}=fixture();doc.fingerprint={algorithm:'SHA-256',sha256:'a'.repeat(64),bytes:6,version:'1',capturedAt:at};expect(matchingReferences(w.documents,doc.fingerprint)).toEqual([doc]);expect(matchingReferences(w.documents,{...doc.fingerprint,bytes:7})).toEqual([]);expect(matchingReferences(w.documents,doc.fingerprint,doc.id)).toEqual([]);expect(doc.status).toBe('declared');});
 it('cites one passage across selected activities and questions, preserving assessments',()=>{const{w,a,b,doc}=fixture(),keys=[`activity/${a.id}/objective`,`activity/${b.id}/rights`],original=JSON.stringify(w);const n=citeEvidence(w,doc.id,keys,'p. 2','Périmètre factuel',w.revision,at);expect(n.revision).toBe(2);expect(n.documents[0]!.activityIds).toEqual([a.id,b.id]);expect(reviewTargets(n).filter(t=>t.note.citations?.length).map(t=>t.key)).toEqual(keys);expect(n.activities[0]!.analysis.notes[0]!.assessment).toEqual(unknown());expect(JSON.stringify(w)).toBe(original);expect(()=>citeEvidence(n,doc.id,keys,'p. 2','duplicate',n.revision,at)).toThrow('COLLISION');});
 it('refuses out-of-scope targets, duplicate keys, missing passages and limits atomically',()=>{const{w,a,doc}=fixture(),key=`activity/${a.id}/objective`;for(const keys of[[],[key,key],['activity/foreign/objective'],Array.from({length:21},(_,i)=>`${key}${i}`)])expect(()=>citeEvidence(w,doc.id,keys,'p. 1','Sens',w.revision,at)).toThrow('INVALID');expect(()=>citeEvidence(w,doc.id,[key],' ','Sens',w.revision,at)).toThrow('INVALID');expect(()=>citeEvidence(w,doc.id,[key],'p. 1','x'.repeat(3001),w.revision,at)).toThrow('INVALID');expect(()=>citeEvidence(w,doc.id,[key],'p. 1','Sens',42,at)).toThrow('CONFLICT');});
});
describe('comparison of actual shared contents',()=>{
 it('ignores new opaque IDs and order but detects actual field differences',()=>{const{w,a}=fixture();if(a.role==='controller')a.purposes=[createPurpose(id())];const x=share(w),y=share(w);expect(x.activities[0]!.id).not.toBe(y.activities[0]!.id);y.activities.reverse();expect(compareDeliveries(x,y).differences).toEqual([]);y.activities[1]!.recipients=knowledge('Équipe autorisée');const d=compareDeliveries(x,y).differences;expect(d).toHaveLength(1);expect(d[0]).toMatchObject({section:'Recrutement',label:'Destinataires',before:'À documenter',after:'Déclaré : Équipe autorisée',structured:false});});
 it('flags changed sharing scope and avoids asserting deletion, closure or renamed identity',()=>{const{w}=fixture(),x=share(w),y=share(w);y.recipient='Autre destinataire';y.scope='Autre périmètre';y.activities.pop();const c=compareDeliveries(x,y);expect(c.scopeChanged).toBe(true);expect(c.differences.find(d=>d.section==='Activités')?.after).toBe('Absente de ce dossier');expect(JSON.stringify(c)).not.toMatch(/supprim|clôtur/);});
 it('reports homonyms as ambiguous and compares disclosed flow contents without private data',()=>{const{w,a,b}=fixture();b.title=a.title;const x=share(w),y=share(w);expect(compareDeliveries(x,y).ambiguous).toEqual([a.title]);const flow=createDataFlow(id());a.flows=[flow];b.title='Autre';const options={profile:'internal-review' as const,recipient:'Fictif',scope:'Fictif',reservations:[],activityIds:w.activities.map(a=>a.id),documentIds:[],clientId:null,flowIds:[flow.id]};const s=projectShare(w,options,id,at),t=projectShare(w,options,id,at);expect(compareDeliveries(s,t).differences).toEqual([]);t.flows![0]!.channel=knowledge('<img src=x>');expect(compareDeliveries(s,t).differences.some(d=>d.section==='Flux')).toBe(true);expect(JSON.stringify(compareDeliveries(s,t))).not.toContain('PRIVATE_PATH');});
 it('validates both DTOs before comparison',()=>{const{w}=fixture(),s=share(w);expect(()=>compareDeliveries({...s,secret:'private'} as typeof s,s)).toThrow();});
});


it('distinguishes an unknown fact from a literal matching its displayed placeholder',()=>{
 const {w}=fixture(),before=share(w),after=share(w);after.activities[0]!.dataSubjects=knowledge('À documenter');
 const result=compareDeliveries(before,after).differences;expect(result).toHaveLength(1);expect(result[0]).toMatchObject({before:'À documenter',after:'Déclaré : À documenter',structured:false});
 after.activities[0]!.dataSubjects=knowledge('null');expect(compareDeliveries(before,after).differences[0]!.after).toBe('Déclaré : null');
});
