import { describe, it, expect } from "vitest";
import { createWorkspace, createActivity, createDataFlow, createDpoCase, createImpactAssessment, assertWorkspace, migrateWorkspace, resolvedFlows, citationChanges, recordPiaReview, piaChanges, reviseWorkspace, projectShare, assertShare, renderShareFiles, unknown, knowledge as k, type EvidenceReference } from "../src/index";
let seq = 70000; const id = () => `00000000-0000-4000-8000-${String(seq++).padStart(12,"0")}`, at = "2026-09-23T10:00:00.000Z";
function fixture() {
 const w = createWorkspace(id(),"Fictif",at), a = createActivity(w.id,id(),"controller");
 const s = {id:id(),workspaceId:w.id,name:"Outil fictif",description:unknown()}; w.systems=[s]; w.activities=[a];
 const f = createDataFlow(id()); f.sourceRef="subjects"; f.destinationRef=`system:${s.id}`; f.dataFromActivity=true; a.flows=[f]; a.dataSubjects=k("Adhérents fictifs"); a.dataCategories=k("Coordonnées");
 const d: EvidenceReference = {id:id(),workspaceId:w.id,title:"PRIVATE_REFERENCE",category:"other",activityIds:[a.id],purposeIds:[],partyIds:[],scope:"Fictif",version:"1",declaredAuthor:"Fictif",internalRef:"PRIVATE_LOCATION",publicReference:"",reservations:"",sensitivity:"internal",status:"declared",reviewedRevision:null,reviewedAt:null,reviewDue:null,audience:"",channel:"",availability:unknown(),contractReview:null}; w.documents=[d];
 a.analysis.notes[0]!.citations=[{documentId:d.id,version:"1",locator:"PRIVATE_PAGE",meaning:"PRIVATE_ARGUMENT"}]; assertWorkspace(w); return {w,a,s,f,d};
}
describe("linked facts and evidence boundaries", () => {
 it("migrates a strict v5 without mutation or changes to existing histories", () => { const {w,a}=fixture(); a.flows=[]; delete a.analysis.notes[0]!.citations; const old={...w,format:"rgpd-master-v5"}; const bytes=JSON.stringify(old); const next=migrateWorkspace(old); expect(next).toEqual({...old,format:"rgpd-master-v10"}); expect(JSON.stringify(old)).toBe(bytes); expect(() => migrateWorkspace({...old,extra:true})).toThrow("INVALID"); });
 it("rejects missing endpoints, contradictory copies, orphan citations and duplicate passages", () => {
   for (const mutate of [(v:ReturnType<typeof fixture>)=>v.f.destinationRef=`system:${id()}`,(v:ReturnType<typeof fixture>)=>v.f.destination=k("Contradiction"),(v:ReturnType<typeof fixture>)=>v.f.data=k("Contradiction"),(v:ReturnType<typeof fixture>)=>v.d.activityIds=[],(v:ReturnType<typeof fixture>)=>v.a.analysis.notes[0]!.citations!.push({...v.a.analysis.notes[0]!.citations![0]!}),(v:ReturnType<typeof fixture>)=>v.a.analysis.notes[0]!.citations![0]!.meaning=""]) {const v=fixture();mutate(v);expect(()=>assertWorkspace(v.w)).toThrow("INVALID");}
 });
 it("freezes resolved entities and citations in a review without rewriting history", () => { const {w,a,s}=fixture(); w.impactAssessments=[createImpactAssessment(w.id,a,id())]; let saved=recordPiaReview(w,w.impactAssessments[0]!.id,{id:id(),author:"Fictif",outcome:"rework",reason:"À revoir"},w.revision,at); const snapshot=JSON.stringify(saved.impactAssessments[0]!.reviews); saved=reviseWorkspace(saved,saved.revision,at,{systems:[{...s,name:"Nouveau nom"}]}); const old=saved.impactAssessments[0]!.reviews[0]!.context; expect(resolvedFlows(old.activity,old)[0]!.destination).toEqual(k("Outil fictif")); expect(piaChanges(saved,saved.impactAssessments[0]!).some((c)=>c.label==="Destination")).toBe(true); expect(JSON.stringify(saved.impactAssessments[0]!.reviews)).toBe(snapshot); });
 it("flags version changes without modifying a cited version or assessment", () => {const {w,a,d}=fixture(); d.version="2"; assertWorkspace(w); expect(citationChanges(a.analysis.notes,w.documents)).toEqual(["objective"]); expect(a.analysis.notes[0]!.citations![0]!.version).toBe("1");});
 it("supports separate SI dossiers without applying human-risk levels or legal positions", () => {const {w,a}=fixture(); const c=createDpoCase(w.id,id(),"security"); c.activityIds=[a.id]; w.dpoCases=[c]; assertWorkspace(w); expect(c.content.notes).toHaveLength(8); expect(c.content.notes.every((n)=>n.assessment.state==="unknown")).toBe(true); expect(c.reviews).toEqual([]);});
});
describe("explicit presentation projection", () => {
 const options = (aid:string) => ({profile:"internal-review" as const,recipient:"Conseil fictif",scope:"Fictif",reservations:[],activityIds:[aid],documentIds:[],clientId:null});
 it("keeps default v1 unchanged and includes only individually selected resolved flows in v2", () => {const {w,a,f}=fixture(); const v1=projectShare(w,options(a.id),id,at); expect(v1.format).toBe("rgpd-share-v1"); expect(v1.flows).toBeUndefined(); const v2=projectShare(w,{...options(a.id),flowIds:[f.id]},id,at); expect(v2.format).toBe("rgpd-share-v2"); expect(v2.flows![0]!.destination).toEqual(k("Outil fictif")); const files=JSON.stringify(renderShareFiles(v2)); for(const secret of [w.id,a.id,f.id,w.systems[0]!.id,w.documents[0]!.id,"PRIVATE_REFERENCE","PRIVATE_LOCATION","PRIVATE_PAGE","PRIVATE_ARGUMENT","sourceRef"]) expect(files).not.toContain(secret);});
 it("refuses foreign/duplicate flow selection, stable public IDs, unknown public properties and client-excerpt flows", () => {const {w,a,f}=fixture(); for(const patch of [{flowIds:[id()]},{flowIds:[f.id,f.id]}]) expect(()=>projectShare(w,{...options(a.id),...patch},id,at)).toThrow("INVALID"); expect(()=>projectShare(w,{...options(a.id),flowIds:[f.id]},()=>f.id,at)).toThrow(); const dto=projectShare(w,{...options(a.id),flowIds:[f.id]},id,at); expect(()=>assertShare({...dto,internalNotes:"unsafe"})).toThrow(); expect(()=>assertShare({...dto,profile:"client-excerpt"})).toThrow(); expect(()=>assertShare({...dto,flows:[{...dto.flows![0],sourceRef:"subjects"}]})).toThrow();});
 it("escapes every flow and summary string in HTML and neutralizes formula prefixes in CSV", () => {const {w,a,f}=fixture(); f.operation=k('<img src=x onerror="probe">'); f.channel=k("=DANGEROUS()"); const dto=projectShare(w,{...options(a.id),flowIds:[f.id]},id,at), files=renderShareFiles(dto); expect(files["report.html"]).not.toContain('<img src=x'); expect(files["report.html"]).toContain('&lt;img'); expect(files["register.csv"]).toContain("'=DANGEROUS()"); expect(files["report.html"]).toContain("default-src 'none'");});
});
