import {describe,it,expect} from "vitest";
import {documentaryActionLabel,CATALOG_VERSION,createWorkspace,createActivity,createDataFlow,unknown,knowledge as k,assertWorkspace,reexaminationQueue,reexamineCitation,reviseWorkspace,entityDossier,checkpointExists,projectShare,renderShareFiles,assertShare,type EvidenceReference} from "../src/index";
let seq=80000;const id=()=>`00000000-0000-4000-8000-${String(seq++).padStart(12,"0")}`,at="2026-09-23T10:00:00.000Z";
function fixture(){const w=createWorkspace(id(),"Fictif",at),a=createActivity(w.id,id(),"controller");w.activities=[a];const s={id:id(),workspaceId:w.id,name:"Outil",description:unknown()};w.systems=[s];const f=createDataFlow(id());f.destinationRef=`system:${s.id}`;a.flows=[f];const d:EvidenceReference={id:id(),workspaceId:w.id,title:"PRIVATE_DOC",category:"other",activityIds:[a.id],purposeIds:[],partyIds:[],scope:"Fictif",version:"2",declaredAuthor:"",internalRef:"PRIVATE_LOCATION",publicReference:"",reservations:"",sensitivity:"internal",status:"declared",reviewedRevision:null,reviewedAt:null,reviewDue:null,audience:"",channel:"",availability:unknown(),contractReview:null};w.documents=[d];a.analysis.notes[0]!.citations=[{documentId:d.id,version:"1",locator:"PRIVATE_PASSAGE",meaning:"PRIVATE_ARGUMENT"}];a.analysis.notes[0]!.assessment=k("Ancienne appréciation");assertWorkspace(w);return{w,a,s,d};}
function input(w:ReturnType<typeof fixture>["w"]){const r=reexaminationQueue(w)[0]!;return{target:r.target.key,documentId:r.document.id,locator:r.citation.locator,fromVersion:r.citation.version,toVersion:r.document.version,outcome:"maintained" as const,assessment:"ignored",author:"DPO fictif",reason:"Passage relu"};}
describe("five short workbench paths",()=>{
 it("reexamines only linked current questions and retains before/after and motive atomically",()=>{const{w}=fixture(),original=JSON.stringify(w);let n=reexamineCitation(w,input(w),w.revision,at);expect(reexaminationQueue(n)).toHaveLength(0);expect(n.revision).toBe(2);expect(n.citationReviews![0]!.before).toEqual(k("Ancienne appréciation"));expect(n.citationReviews![0]!.after).toEqual(k("Ancienne appréciation"));expect(JSON.stringify(w)).toBe(original);n=reviseWorkspace(n,n.revision,at,{documents:n.documents.map(d=>({...d,version:"3"}))});n=reexamineCitation(n,{...input(n),outcome:"revised",assessment:"Réserve nouvelle"},n.revision,at);expect(n.citationReviews).toHaveLength(2);expect(n.activities[0]!.analysis.notes[0]!.assessment).toEqual(k("Réserve nouvelle"));expect(()=>reviseWorkspace(n,n.revision,at,{citationReviews:[]})).toThrow("INVALID");});
 it("rejects stale scope/version/revision, empty explanation, missing assessment and unknown properties",()=>{const{w}=fixture();for(const patch of[{target:"activity/foreign/unknown"},{fromVersion:"0"},{toVersion:"3"},{documentId:id()},{locator:"other"},{reason:" "},{author:" "},{outcome:"revised" as const,assessment:""}])expect(()=>reexamineCitation(w,{...input(w),...patch},w.revision,at)).toThrow();expect(()=>reexamineCitation(w,input(w),42,at)).toThrow("CONFLICT");w.activities[0]!.analysis.notes[0]!.assessment=unknown();expect(()=>reexamineCitation(w,input(w),w.revision,at)).toThrow("INVALID");});
 it("groups only explicit entity links without guessing from matching names",()=>{const{w,a,s,d}=fixture();const unrelated=createActivity(w.id,id(),"controller");unrelated.title=s.name;w.activities.push(unrelated);const x=entityDossier(w,"system",s.id);expect(x.activities.map(a=>a.id)).toEqual([a.id]);expect(x.flows).toHaveLength(1);expect(x.documents.map(d=>d.id)).toEqual([d.id]);expect(x.questions).toHaveLength(1);expect(entityDossier(w,"system",id()).activities).toEqual([]);});
 it("validates saved checkpoints and bounded interview questions without touching existing fields",()=>{const{w,a}=fixture();w.workCheckpoint={kind:"activity",id:a.id,section:"interview",step:4};a.interviewQuestions=["Qui vérifie les habilitations ?"];assertWorkspace(w);expect(checkpointExists(w,w.workCheckpoint)).toBe(true);for(const patch of[{...w.workCheckpoint,step:9},{...w.workCheckpoint,id:id()},{...w.workCheckpoint,url:"https://example.test"}])expect(()=>assertWorkspace({...w,workCheckpoint:patch})).toThrow();a.interviewQuestions=["x","x"];expect(()=>assertWorkspace(w)).toThrow();});
 it("projects a deliberate executive page without private notes, reference paths or checkpoint",()=>{const{w,a}=fixture();w.workCheckpoint={kind:"activity",id:a.id,section:"interview",step:5};a.interviewQuestions=["PRIVATE_QUESTION"];const options={profile:"internal-review" as const,recipient:"Direction fictive",scope:"Fictif",reservations:[],activityIds:[a.id],documentIds:[],clientId:null};const legacy=projectShare(w,options,id,at);expect(legacy.format).toBe("rgpd-share-v1");const dto=projectShare(w,{...options,executive:{changes:'<img src=x onerror="probe">',arbitrations:"=FORMULA()"}},id,at);const files=renderShareFiles(dto);expect(files["report.html"]).toContain('&lt;img');expect(files["report.html"]).not.toContain('<img src=x');expect(files["report.html"]!.indexOf('Comprendre. Arbitrer. Agir.')).toBeLessThan(files["report.html"]!.indexOf('Le périmètre, en un regard.'));expect(files["register.csv"]).toContain("'=FORMULA()");for(const secret of["PRIVATE_DOC","PRIVATE_LOCATION","PRIVATE_PASSAGE","PRIVATE_QUESTION","workCheckpoint",w.id])expect(JSON.stringify(files)).not.toContain(secret);expect(()=>assertShare({...dto,executive:{...dto.executive,extra:"private"}})).toThrow();expect(()=>projectShare(w,{...options,executive:{changes:"x".repeat(801),arbitrations:"x"}},id,at)).toThrow();});
});

it("names the explicitly tracked question, keeping unknown historical catalogs explicit",()=>{
 expect(documentaryActionLabel({ruleId:"R-004",catalogVersion:CATALOG_VERSION,scope:"Paie fictive"})).toBe("Conservation à documenter · Paie fictive");
 expect(documentaryActionLabel({ruleId:"R-004",catalogVersion:"historical",scope:"Paie fictive"})).toBe("R-004 · Paie fictive");
});
