import {test,expect} from '@playwright/test';
import {build} from 'esbuild';
import {readFile} from 'node:fs/promises';
import JSZip from 'jszip';
import type {} from '../../fixtures/privacy/vault-harness';

test('DPO prepares, previews and applies a correction with evidence, then opens the updated register export',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/app/privacy/#demo/actions');const plan=page.getByRole('region',{name:'Plan de corrections'});
 await plan.getByRole('button',{name:'Préparer un correctif',exact:true}).click();await plan.getByRole('combobox',{name:'Ensemble à corriger',exact:true}).selectOption({label:'Accès aux locaux par badge · projet fictif'});
 await plan.getByLabel('Correctif attendu',{exact:true}).fill('Restreindre les accès · exercice fictif');await plan.getByRole('combobox',{name:'Priorité choisie',exact:true}).selectOption('first');await plan.getByLabel('Responsable de la réalisation',{exact:true}).fill('Responsable fictif');await plan.getByLabel('Pourquoi ce correctif et cette priorité ?',{exact:true}).fill('Limiter le périmètre des personnes autorisées dans cet exercice.');
 await plan.getByRole('combobox',{name:'Élément à modifier',exact:true}).selectOption({label:'D1 · Garanties et vérification'});await plan.getByRole('button',{name:'Ajouter ce changement',exact:true}).click();await plan.getByLabel('Nouvelle valeur · D1 · Garanties et vérification',{exact:true}).fill('GARANTIE_FICTIVE_CORRIGEE · Relecture des habilitations par le responsable.');
 await plan.getByRole('combobox',{name:'Élément à modifier',exact:true}).selectOption({label:'D1 · Catégories de données'});await plan.getByRole('button',{name:'Ajouter ce changement',exact:true}).click();await plan.getByLabel('Nouvelle valeur · D1 · Catégories de données',{exact:true}).fill('DONNEES_FICTIVES_CORRIGEES');
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.setViewportSize({width:1280,height:850});
 await plan.getByRole('button',{name:'Enregistrer le correctif prévu',exact:true}).click();await expect(plan.getByRole('heading',{name:'Restreindre les accès · exercice fictif',exact:true})).toBeVisible();await expect(plan).toContainText('1 à réaliser');
 await plan.getByRole('button',{name:'C’est fait, voilà la preuve',exact:true}).click();await plan.getByText('Voir la description et les flux après ce correctif',{exact:true}).click();await expect(plan.getByRole('article',{name:'Aperçu après application'})).toContainText('GARANTIE_FICTIVE_CORRIGEE');
 await plan.getByRole('group',{name:'Justificatifs de réalisation',exact:true}).getByRole('checkbox').first().check();await plan.getByLabel('Passage ou repère examiné',{exact:true}).fill('Section fictive 2');await plan.getByLabel('Ce que cette pièce permet de constater',{exact:true}).fill('La restriction fictive est documentée dans la version relue.');await plan.getByLabel('Auteur de la validation',{exact:true}).fill('DPO fictif');await plan.getByLabel('Constat de réalisation',{exact:true}).fill('Mise en œuvre déclarée pour cet exercice.');
 const apply=plan.getByRole('button',{name:'Confirmer la réalisation et mettre à jour le dossier',exact:true});await expect(apply).toBeDisabled();await plan.getByRole('checkbox',{name:'J’ai relu les changements et les justificatifs. Je confirme leur application aux faits du registre.',exact:true}).check();await apply.click();
 await expect(plan).toContainText('1 appliqués au registre');await plan.getByText('Avant / après et justificatifs conservés · v1 → v2',{exact:true}).click();await plan.getByText('Description après · v2',{exact:true}).click();await expect(plan.getByRole('article',{name:'Description conservée v2'})).toContainText('GARANTIE_FICTIVE_CORRIGEE');await expect(plan).toContainText('Section fictive 2');
 await plan.getByRole('button',{name:'Voir le registre actualisé',exact:true}).click();await expect(page.locator('.activity-reader')).toContainText('GARANTIE_FICTIVE_CORRIGEE');await expect(page.locator('.activity-reader')).toContainText('v2');
 await page.getByRole('navigation',{name:'Espace RGPD'}).getByRole('button',{name:/Actions/}).click();await plan.getByRole('button',{name:'Préparer l’export du registre',exact:true}).click();await expect(page.getByLabel('Périmètre public de cette livraison',{exact:true})).toHaveValue(/v2/);await expect(page.getByLabel('Destinataire déclaré',{exact:true})).toHaveValue('');await page.getByLabel('Destinataire déclaré',{exact:true}).fill('Conseil fictif');await page.getByRole('button',{name:'Prévisualiser le dossier',exact:true}).click();await page.getByRole('checkbox',{name:'J’ai relu ce contenu en clair, ses réserves et son destinataire. Je confirme ce partage pour cette révision.',exact:true}).check();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Confirmer et télécharger le dossier',exact:true}).click();const file=await download,zip=await JSZip.loadAsync(await readFile((await file.path())!));const json=await zip.file('register.json')!.async('string');expect(json).toContain('DONNEES_FICTIVES_CORRIGEES');expect(json).not.toContain('Section fictive 2');expect(await zip.file('report.html')!.async('string')).toContain('DONNEES_FICTIVES_CORRIGEES');expect(errors).toEqual([]);
});

test('v10 opens without rewriting ciphertext; corrections and drafts remain encrypted and atomic',async({page})=>{
 test.setTimeout(60000);
 const harness=(await build({entryPoints:['tests/fixtures/privacy/vault-harness.ts'],bundle:true,platform:'browser',format:'iife',write:false})).outputFiles[0]!.text;
 await page.route('**/__corrective.js',r=>r.fulfill({contentType:'application/javascript',body:harness}));await page.route('**/__corrective',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html><head><script src="/__corrective.js"></script></head><body>Fictional corrective test</body></html>'}));await page.goto('/__corrective');await page.waitForFunction(()=>!!window.privacyTest);
 const result=await page.evaluate(async()=>{
  const t=window.privacyTest,at=new Date().toISOString(),phrase='Fictional corrective phrase 2026 protected',vault=new t.PrivacyVault(),session={epoch:await vault.initialize(),signal:new AbortController().signal};
  const w=t.createDemoWorkspace(()=>crypto.randomUUID(),at),old={...w,format:'rgpd-master-v10'};
  const [envelope]=await t.encryptLocalPayloadBatch([{aad:t.contextFor(w.id,w.revision,'master'),value:old}],phrase);await vault.table('records').add({id:w.id,revision:w.revision,format:'rgpd-envelope-v1',envelope});
  const before=JSON.stringify(await vault.table('records').toArray()),opened=await vault.unlock(w.id,phrase,session),untouched=before===JSON.stringify(await vault.table('records').toArray());
  const a=opened.activities[0]!,field=t.correctionFields(a,opened).find(f=>f.key==='activity/securityMeasures')!,change={...t.newCorrectionChange(field),after:t.knowledge('PRIVATE_CORRECTION_CANARY')};
  const prepared=t.prepareCorrectiveAction(opened,{id:crypto.randomUUID(),activityId:a.id,title:'PRIVATE_TITLE_CANARY',priority:'first',reason:'Fictional reason',owner:'Fictional owner',due:null,dependsOn:[],changes:[change]},opened.revision,at);await vault.save(prepared,phrase,opened.revision,session);
  const action=prepared.actions.at(-1)!,doc=prepared.documents.find(d=>d.activityIds.includes(a.id))!,input={author:'Fictional author',justification:'Fictional observation',evidence:[{documentId:doc.id,version:doc.version,locator:'PRIVATE_LOCATOR_CANARY',meaning:'PRIVATE_MEANING_CANARY'}]},next=t.completeCorrectiveAction(prepared,action.id,input,prepared.revision,at);
  const preparedBytes=JSON.stringify(await vault.table('records').toArray()),put=IDBObjectStore.prototype.put;let quota=false;IDBObjectStore.prototype.put=function(...args){if(this.name==='records')throw new DOMException('Quota','QuotaExceededError');return put.apply(this,args);};
  try{await vault.save(next,phrase,prepared.revision,session);}catch{quota=true;}finally{IDBObjectStore.prototype.put=put;}
  const unchanged=preparedBytes===JSON.stringify(await vault.table('records').toArray());await vault.save(next,phrase,prepared.revision,session);
  let conflict=false;try{await vault.save(next,phrase,prepared.revision,session);}catch{conflict=true;}
  const reopened=await vault.unlock(w.id,phrase,session),backup=await vault.backup(reopened,phrase,session),decoded=await t.decodeBackup(backup,phrase);
  const draft={format:'rgpd-draft-v4' as const,workspaceId:w.id,revision:next.revision,id:crypto.randomUUID(),sequence:1,updatedAt:at,form:{kind:'corrective' as const,mode:'complete' as const,actionId:action.id,activityId:a.id,title:'PRIVATE_DRAFT_CANARY',priority:'first' as const,reason:'',owner:'',due:'',dependsOn:[],changes:[change],author:'',justification:'',evidence:input.evidence}};
  const sealed=await t.sealRecovery(draft,phrase),recovered=await t.openRecovery(sealed,phrase,w.id,next.revision,draft.id,1),raw=JSON.stringify(await vault.table('records').toArray());vault.close();
  return{untouched,format:opened.format,quota,unchanged,conflict,roundTrip:JSON.stringify(next)===JSON.stringify(decoded),draftSame:JSON.stringify(draft)===JSON.stringify(recovered),leak:(raw+backup+JSON.stringify(sealed)).includes('CANARY'),revision:reopened.revision===prepared.revision+1,applied:reopened.actions.at(-1)!.corrective!.application!.version};
 });expect(result).toEqual({untouched:true,format:'rgpd-master-v11',quota:true,unchanged:true,conflict:true,roundTrip:true,draftSame:true,leak:false,revision:true,applied:2});
});
