import { expect, test } from "@playwright/test";

test("guide is readable without JavaScript and every local link and chapter resolves", async ({ browser, baseURL }) => {
  const context = await browser.newContext({ javaScriptEnabled: false, baseURL });
  try {
    const page = await context.newPage();
    await page.goto("/app/privacy/guide/");
    await expect(page.getByRole("heading", { level: 1 })).toContainText("Un registre compris.");
    const chapters = page.getByRole("navigation", { name: "Sommaire du guide" }).getByRole("link");
    await expect(chapters).toHaveCount(12);
    const localLinks = await page.locator('a[href^="/"], a[href^="#"]').evaluateAll((elements) => elements.map((element) => (element as HTMLAnchorElement).getAttribute("href")!));
    for (const href of new Set(localLinks)) {
      if (href.startsWith("#")) {
        await expect(page.locator(`[id=${JSON.stringify(decodeURIComponent(href.slice(1)))}]`)).toHaveCount(1);
      } else {
        // release.json is generated by the isolated-release builder, after the mixed build.
        if (href === "/release.json") continue;
        const response = await page.request.get(href);
        expect(response.status(), href).toBe(200);
      }
    }
    await expect(page.getByRole("article")).toContainText("La sauvegarde du serveur RGPDESK ne contient pas vos coffres.");
    await expect(page.getByRole("article")).toContainText("sans revue juridique humaine");
    await expect(page.locator("script, iframe, form")).toHaveCount(0);
  } finally {
    await context.close();
  }
});

test("entry explains the product, keeps the guide separate from an open vault and fits small screens", async ({ page }) => {
  await page.goto("/app/privacy/");
  await expect(page.locator('[data-rgpdesk-ready="true"]')).toBeVisible();
  await expect(page.getByRole("heading", { level: 1 })).toContainText("Votre registre RGPD.");
  const guide = page.getByRole("navigation", { name: "Aide" }).getByRole("link", { name: "Guide d’utilisation" });
  await expect(guide).toHaveAttribute("target", "_blank");
  await expect(guide).toHaveAttribute("rel", /noopener/);
  await page.getByRole("link", { name: "Commencer mon registre" }).click();
  await expect(page.getByRole("heading", { name: "Créer le registre de mon organisation" })).toBeInViewport();
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
    expect(overflow, `entry width ${width}`).toBe(false);
  }
  await page.goto("/app/privacy/guide/");
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), `guide width ${width}`).toBe(false);
  }
  await page.emulateMedia({ media: "print" });
  await expect(page.getByRole("navigation", { name: "Sommaire du guide" })).toBeHidden();
  await expect(page.getByRole("heading", { name: "9. Sauvegarder et restaurer sans perdre son travail", exact: true })).toBeVisible();
});
