import {test,expect} from "@playwright/test";
async function demo(page:import("@playwright/test").Page){await page.goto("/app/privacy/");await page.getByRole("button",{name:"Explorer la démo",exact:true}).click();}
test("interview edits the same inventory and records the exact saved step",async({page})=>{
 await demo(page);await page.getByRole("button",{name:"Registre",exact:true}).click();await page.getByRole('button',{name:'Modifier Recrutement · exemple fictif',exact:true}).click();await page.getByRole('button',{name:'Mener l’entretien',exact:true}).click();await page.getByRole('button',{name:'2 Les personnes et données',exact:true}).click();await page.getByLabel('De quelles personnes parle-t-on ?', {exact:true}).fill('Personnes fictives pour test');await page.getByRole('button',{name:'6 Les réponses attendues',exact:true}).click();await page.getByRole('button',{name:'Ajouter une question à poser',exact:true}).click();await page.getByLabel('À demander au métier · 1',{exact:true}).fill('Qui examine les accès ?');await page.getByRole('button',{name:'Enregistrer la fiche',exact:true}).click();await page.getByRole('button',{name:'Ma mission',exact:true}).click();
 // Demo overview still offers the same saved-step action as a real vault.
 await page.getByRole('button',{name:'Reprendre là où j’ai enregistré',exact:true}).click();await expect(page.getByRole('button',{name:'6 Les réponses attendues',exact:true})).toHaveAttribute('aria-current','step');await expect(page.getByLabel('À demander au métier · 1',{exact:true})).toHaveValue('Qui examine les accès ?');await page.getByRole('button',{name:'2 Les personnes et données',exact:true}).click();await expect(page.getByLabel('De quelles personnes parle-t-on ?', {exact:true})).toHaveValue('Personnes fictives pour test');
});
test("entity overview and deliberate executive summary remain scoped",async({page})=>{
 await demo(page);await page.getByRole('button',{name:'Systèmes',exact:true}).click();await page.getByRole('button',{name:'Voir la fiche',exact:true}).first().click();await expect(page.getByRole('region',{name:'Fiche transversale'})).toContainText('Activités liées');await page.getByRole('button',{name:'Partager un dossier',exact:true}).click();await page.getByRole('button',{name:'Charger la sélection d’exemple',exact:true}).click();await page.getByText('Ajouter une synthèse direction et des flux choisis',{exact:true}).click();await page.getByRole('checkbox',{name:'Ouvrir le rapport par une lecture pour la direction',exact:true}).check();await page.getByLabel('Ce qui change pour ce périmètre',{exact:true}).fill('Examen fictif du changement de prestataire.');await page.getByLabel('Arbitrages demandés à la direction',{exact:true}).fill('Désigner un responsable de la vérification.');await page.getByRole('button',{name:'Prévisualiser le dossier',exact:true}).click();await page.getByText('Examiner tous les champs du dossier',{exact:true}).click();await expect(page.getByRole('table',{name:'Contenu exact à partager'})).toContainText('Désigner un responsable de la vérification.');await expect(page.getByRole('button',{name:'Confirmer et télécharger le dossier',exact:true})).toBeDisabled();
});
test("vault entry cards are readable at desktop and narrow widths",async({page})=>{
 await page.goto('/app/privacy/');for(const width of[1440,390,320]){await page.setViewportSize({width,height:1000});await page.locator('#creer-registre').scrollIntoViewIfNeeded();await expect(page.locator('.vault-card-icon')).toHaveCount(2);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const h=page.locator('#client-vaults h2');expect(await h.evaluate(e=>getComputedStyle(e).color)).toBe('rgb(244, 248, 251)');}
});

test("a changed reference can be reexamined with an explicit reason and preserved assessment",async({page})=>{
 await demo(page);await page.getByText("Dix situations métier à explorer",{exact:true}).click();await page.getByRole("combobox",{name:"Choisir un cas de référence",exact:true}).selectOption("paie");await page.getByRole("button",{name:"Ouvrir ce cas fictif",exact:true}).click();
 await page.getByRole('button',{name:'Documents',exact:true}).click();await page.getByRole('button',{name:'Examiner Compte rendu fictif de l’entretien',exact:true}).click();await page.getByLabel('Version déclarée',{exact:true}).fill('EXERCICE-v2');await page.getByRole('button',{name:'Enregistrer la référence',exact:true}).click();await expect(page.getByLabel('Titre interne',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Ma mission',exact:true}).click();
 const queue=page.getByRole('region',{name:'Réexamens des références'});await expect(queue.getByRole('button',{name:'Réexaminer ce passage'})).toHaveCount(2);await queue.getByRole('button',{name:'Réexaminer ce passage'}).first().click();await page.getByLabel('À l’issue de votre relecture',{exact:true}).selectOption('revised');await page.getByLabel('Nouvelle appréciation',{exact:true}).fill('Position fictive à faire relire.');await page.getByLabel('Motif du réexamen',{exact:true}).fill('La nouvelle version précise le périmètre.');await page.getByLabel('Auteur de cette relecture',{exact:true}).fill('DPO fictif');await page.getByRole('button',{name:'Consigner le réexamen',exact:true}).click();await expect(queue.getByRole('button',{name:'Réexaminer ce passage'})).toHaveCount(1);await page.getByText('Historique des relectures de preuves · 1',{exact:true}).click();await expect(page.getByText('La nouvelle version précise le périmètre.',{exact:true})).toBeVisible();
});
test("encrypted vault resumes after lock and backup check leaves stored ciphertext unchanged",async({page})=>{
 test.setTimeout(60000);await page.goto('/app/privacy/');await expect(page.locator('[data-rgpdesk-ready="true"]')).toBeVisible();const phrase='Fictitious checkpoint backup phrase 2026!';await page.getByLabel('Nom de l’organisme',{exact:true}).fill('TEST_FICTIF_REPRISE');await page.getByLabel('Nouvelle phrase secrète',{exact:true}).fill(phrase);await page.getByLabel('Confirmer la phrase secrète',{exact:true}).fill(phrase);await page.getByLabel('Je comprends qu’une phrase perdue').check();await page.getByRole('button',{name:'Créer le coffre chiffré',exact:true}).click();await page.getByRole('button',{name:'Registre',exact:true}).click();await page.getByRole('button',{name:'Ajouter une activité responsable',exact:true}).click();await page.getByLabel('Nom de l’activité',{exact:true}).fill('TEST_FICTIF_ENTRETIEN');await page.getByRole('button',{name:'Mener l’entretien',exact:true}).click();await page.getByRole('button',{name:'6 Les réponses attendues',exact:true}).click();await page.getByRole('button',{name:'Enregistrer la fiche',exact:true}).click();await expect(page.getByRole('button',{name:'Modifier TEST_FICTIF_ENTRETIEN',exact:true})).toBeVisible();await page.getByRole('button',{name:'Verrouiller le coffre',exact:true}).click();await page.getByRole('button',{name:'Ouvrir le coffre 1',exact:true}).click();await page.getByLabel('Phrase secrète du coffre',{exact:true}).fill(phrase);await page.getByRole('button',{name:'Déverrouiller',exact:true}).click();await page.getByRole('button',{name:'Reprendre là où j’ai enregistré',exact:true}).click();await expect(page.getByRole('button',{name:'6 Les réponses attendues',exact:true})).toHaveAttribute('aria-current','step');
 await page.getByRole('button',{name:'Sauvegarde',exact:true}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Télécharger la sauvegarde chiffrée',exact:true}).click();const file=await(await download).path();
 const disk=()=>page.evaluate(()=>new Promise<string>((resolve,reject)=>{const open=indexedDB.open('rgpdesk-vault-v1');open.onerror=()=>reject(new Error('database'));open.onsuccess=()=>{const db=open.result,tx=db.transaction(['records','snapshots','metadata'],'readonly'),result:Record<string,unknown>={};for(const name of ['records','snapshots','metadata']){const req=tx.objectStore(name).getAll();req.onsuccess=()=>result[name]=req.result;}tx.oncomplete=()=>{db.close();resolve(JSON.stringify(result));};tx.onerror=()=>{db.close();reject(new Error('read'));};};}));
 const before=await disk();expect(before).not.toContain('TEST_FICTIF');expect(before).not.toContain('workCheckpoint');await page.getByLabel('Sauvegarde à vérifier',{exact:true}).setInputFiles(file!);await page.getByLabel('Phrase de cette sauvegarde',{exact:true}).fill(phrase);await page.getByRole('button',{name:'Vérifier sans restaurer',exact:true}).click();await expect(page.getByText('Sauvegarde lisible et structure vérifiée.',{exact:true})).toBeVisible();expect(await disk()).toBe(before);await expect(page.getByLabel('Phrase de cette sauvegarde',{exact:true})).toHaveValue('');await page.getByRole('button',{name:'Verrouiller le coffre',exact:true}).click();await expect(page.getByText('Sauvegarde lisible et structure vérifiée.',{exact:true})).toHaveCount(0);
});
