import { test, expect } from "@playwright/test";
import { build } from "esbuild";
import type {} from "../../fixtures/privacy/vault-harness";

test("decline operations, channels and storage, then link and remove parallel paths", async ({ page }) => {
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await page.goto("/app/privacy/#demo/registre");
  await page.getByRole("button", { name: "Modifier Accès aux locaux par badge · projet fictif", exact: true }).click();
  await page.getByRole("navigation", { name: "Étapes de la fiche" }).getByRole("button", { name: "Les flux" }).click();
  const group = page.locator(".data-group-card").first(); await group.locator("summary").first().click();
  await group.getByRole("button", { name: "Ajouter un parcours", exact: true }).click();
  const journeys = group.locator(".analysis-question").filter({ has: page.locator(".journey-editor") });
  const first = journeys.first();
  await first.getByLabel("Flux précédent", { exact: true }).selectOption("none");
  await first.getByLabel("Flux suivant", { exact: true }).selectOption("pending");
  await first.getByLabel("Parcours 1a · Étape 1 · Opération", { exact: true }).fill("Recueillir la demande fictive");
  const builder = first.locator(".flow-branches"); await builder.locator("summary").first().click();
  await expect(builder.getByLabel("Opération alternative 1", { exact: true })).toHaveValue("Recueillir la demande fictive");
  await builder.getByRole("button", { name: "Autre opération", exact: true }).click();
  await builder.getByLabel("Opération alternative 2", { exact: true }).fill("Vérifier la demande fictive");
  await builder.getByLabel("Canal ou support alternatif 1", { exact: true }).fill("Email fictif");
  await builder.getByRole("button", { name: "Autre canal ou support", exact: true }).click();
  await builder.getByLabel("Canal ou support alternatif 2", { exact: true }).fill("Recueil direct fictif");
  await builder.getByLabel("Lieu de stockage alternatif 1", { exact: true }).fill("Formulaires papier fictifs");
  for (const [n, text] of [[2,"Boîte mail fictive"],[3,"Dossier informatique fictif"]] as const) {
    await builder.getByRole("button", { name: "Autre lieu de stockage", exact: true }).click();
    await builder.getByLabel(`Lieu de stockage alternatif ${n}`, { exact: true }).fill(text);
  }
  await expect(builder.locator(".branch-result")).toContainText("12 flux distincts");
  await builder.locator("summary").first().click();
  await builder.locator("summary").first().click();
  await expect(builder.getByLabel("Opération alternative 2", { exact: true })).toHaveValue("Vérifier la demande fictive");
  await expect(builder.locator(".branch-result")).toContainText("12 flux distincts");
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.setViewportSize({ width: 1280, height: 800 });
  await builder.getByRole("button", { name: "Créer les flux parallèles", exact: true }).click();
  await expect(journeys).toHaveCount(12);
  await first.getByLabel("Flux suivant", { exact: true }).selectOption("linked");
  await first.getByRole("group", { name: "Ce qui suit", exact: true }).getByRole("checkbox", { name: /^Parcours 1b/ }).check();
  const second = journeys.nth(1); await second.locator("summary").first().click();
  await expect(second.getByLabel("Flux précédent", { exact: true })).toHaveValue("linked");
  await second.getByRole("button", { name: "Retirer le parcours 1b", exact: true }).click();
  await second.getByRole("button", { name: "Confirmer le retrait du parcours 1b", exact: true }).click();
  await expect(first.getByLabel("Flux suivant", { exact: true })).toHaveValue("pending");
  await page.getByRole("button", { name: "Enregistrer la fiche", exact: true }).click();
  await page.getByRole("button", { name: "Modifier Accès aux locaux par badge · projet fictif", exact: true }).click();
  await page.getByRole("navigation", { name: "Vues de l’activité" }).getByRole("button", { name: "Les flux", exact: true }).click();
  await expect(page.locator(".flow-map .journey-map")).toHaveCount(11);
  await expect(page.locator(".flow-map")).toContainText("En attente de description");
  await expect(page.locator(".flow-map")).toContainText("Dossier informatique fictif");
  expect(errors).toEqual([]);
});

test("an intermediary creates two connected passages with shared data", async ({ page }) => {
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await page.goto("/app/privacy/#demo/registre");
  await page.getByRole("button", { name: "Modifier Accès aux locaux par badge · projet fictif", exact: true }).click();
  await page.getByRole("button", { name: "Les flux", exact: true }).click();
  await page.getByRole("button", { name: "Ajouter un flux", exact: true }).click();
  const first = page.locator(".analysis-question").nth(2);
  await first.getByLabel("Flux 3 · Origine", { exact: true }).fill("Étudiants fictifs");
  await first.getByLabel("Flux 3 · Destination", { exact: true }).fill("Organisateurs fictifs");
  await first.getByLabel("Flux 3 · Opération", { exact: true }).fill("Recueil des formulaires fictifs");
  const intermediary = first.locator(".flow-intermediary"); await intermediary.locator("summary").first().click();
  await intermediary.getByLabel("Intermédiaire · fonction ou groupe", { exact: true }).fill("Équipe fictive de collecte en amphithéâtre");
  await intermediary.getByRole("button", { name: "Scinder le flux avec cet intermédiaire", exact: true }).click();
  await expect(page.locator(".analysis-question")).toHaveCount(4);
  await expect(first.getByLabel("Flux 3 · Destination", { exact: true })).toHaveValue("Équipe fictive de collecte en amphithéâtre");
  await expect(first.getByLabel("Flux suivant", { exact: true })).toHaveValue("linked");
  const second = page.locator(".analysis-question").nth(3); await second.locator("summary").first().click();
  await expect(second.getByLabel("Flux 4 · Origine", { exact: true })).toHaveValue("Équipe fictive de collecte en amphithéâtre");
  await expect(second.getByLabel("Flux 4 · Destination", { exact: true })).toHaveValue("Organisateurs fictifs");
  await expect(second.getByLabel("Flux 4 · Opération", { exact: true })).toHaveValue("");
  await expect(second.getByLabel("Flux précédent", { exact: true })).toHaveValue("linked");
  await page.getByRole("button", { name: "Enregistrer la fiche", exact: true }).click();
  await page.getByRole("button", { name: "Modifier Accès aux locaux par badge · projet fictif", exact: true }).click();
  await page.getByRole("button", { name: "Les flux", exact: true }).click();
  await expect(page.locator(".flow-map .flow-route")).toHaveCount(4);
  await expect(page.locator(".flow-map")).toContainText("Équipe fictive de collecte en amphithéâtre");
  expect(errors).toEqual([]);
});

test("v11 vault is preserved, v12 parallel links survive backup and v5 recovery without plaintext storage", async ({ page }) => {
  test.setTimeout(60_000);
  const harness = (await build({ entryPoints: ["tests/fixtures/privacy/vault-harness.ts"], bundle: true, platform: "browser", format: "iife", write: false })).outputFiles[0]!.text;
  await page.route("**/__branches.js", r => r.fulfill({ contentType: "application/javascript", body: harness }));
  await page.route("**/__branches", r => r.fulfill({ contentType: "text/html", body: '<!doctype html><html><head><script src="/__branches.js"></script></head><body>Fictional branch test</body></html>' }));
  await page.goto("/__branches"); await page.waitForFunction(() => !!window.privacyTest);
  const result = await page.evaluate(async () => {
    const t = window.privacyTest, at = new Date().toISOString(), phrase = "Fictional parallel-flow phrase 2026 protected", vault = new t.PrivacyVault();
    const session = { epoch: await vault.initialize(), signal: new AbortController().signal };
    const w = t.createWorkspace(crypto.randomUUID(), "Fictional branches", at);
    const [envelope] = await t.encryptLocalPayloadBatch([{ aad: t.contextFor(w.id, 1, "master"), value: { ...w, format: "rgpd-master-v11" } }], phrase);
    await vault.table("records").add({ id: w.id, revision: 1, format: "rgpd-envelope-v1", envelope });
    const before = JSON.stringify(await vault.table("records").toArray()), opened = await vault.unlock(w.id, phrase, session);
    const untouched = before === JSON.stringify(await vault.table("records").toArray());
    const a = t.createActivity(w.id, crypto.randomUUID(), "controller"), flow = t.createDataFlow(crypto.randomUUID());
    a.flows = [flow];
    let branched = t.splitFlow(a, flow.id, { operations: [t.knowledge("PRIVATE_BRANCH_CANARY"), t.knowledge("Second fictional operation")] }, () => crypto.randomUUID());
    branched = t.setFlowConnection(branched, branched.flows[0]!.id, "next", { state: "linked", flowIds: [branched.flows[1]!.id] });
    const next = t.putActivity(opened, branched, 1, at); await vault.save(next, phrase, 1, session);
    const raw = JSON.stringify(await vault.table("records").toArray()), reopened = await vault.unlock(w.id, phrase, session);
    const backup = await vault.backup(reopened, phrase, session), decoded = await t.decodeBackup(backup, phrase);
    const draft = { format: "rgpd-draft-v5" as const, workspaceId: w.id, revision: 2, id: crypto.randomUUID(), sequence: 1, updatedAt: at, form: { kind: "activity" as const, draft: branched, documentIds: [], section: "record" as const, step: 2 } };
    const encrypted = await t.sealRecovery(draft, phrase), recovered = await t.openRecovery(encrypted, phrase, w.id, 2, draft.id, 1);
    vault.close();
    return { untouched, format: opened.format, same: JSON.stringify(next) === JSON.stringify(decoded), draftSame: JSON.stringify(draft) === JSON.stringify(recovered), leak: (raw + backup + JSON.stringify(encrypted)).includes("PRIVATE_BRANCH_CANARY"), reciprocal: decoded.activities[0]!.flows[1]!.sequence!.previous.state === "linked" };
  });
  expect(result).toEqual({ untouched: true, format: "rgpd-master-v12", same: true, draftSame: true, leak: false, reciprocal: true });
});
