import {test,expect,type Page} from '@playwright/test';
async function requests(page:Page){await page.getByRole('button',{name:'Actions & décisions',exact:true}).click();await page.getByRole('button',{name:/Demandes aux métiers/}).click();}
async function openSaved(page:Page){await page.locator('.request-record>summary').first().click();}
async function prepareRequest(page:Page){await page.locator('.request-brief>summary').click();await page.getByLabel('Destinataire de la demande',{exact:true}).fill('Équipe RH fictive');await page.getByLabel('Échéance choisie pour cette demande',{exact:true}).fill('2026-10-01');await page.locator('.request-brief .choices label').filter({hasText:'Recrutement'}).first().getByRole('checkbox').check();await page.getByRole('button',{name:'Relire la demande (1)',exact:true}).click();await page.getByLabel('J’ai relu les questions').check();await page.getByRole('button',{name:'Conserver le suivi dans le coffre',exact:true}).click();await expect(page.locator('.request-record')).toHaveCount(1);}
test('track a reply and explicitly review the exact field before applying it',async({page})=>{
 await page.goto('/app/privacy/#demo/registre');await requests(page);await prepareRequest(page);await openSaved(page);await expect(page.locator('.request-record')).toContainText('0 avec réponse');await page.locator('.saved-request-copy>summary').click();await expect(page.getByRole('button',{name:'Télécharger cette demande',exact:true})).toBeDisabled();await page.getByLabel('J’ai relu cette demande conservée').check();await expect(page.getByRole('button',{name:'Télécharger cette demande',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Consigner une réponse à la question 1',exact:true}).click();await page.getByLabel('Réponse reçue à consigner',{exact:true}).fill('Candidats fictifs contactés par notre équipe');await page.getByLabel('Auteur déclaré de la réponse',{exact:true}).fill('RH fictif');await page.getByRole('button',{name:'Conserver la réponse',exact:true}).click();await openSaved(page);await expect(page.locator('.request-record')).toContainText('1 avec réponse');await page.getByRole('button',{name:'Relire pour compléter la fiche',exact:true}).click();await expect(page.getByRole('button',{name:'Reprendre ce fait dans la fiche',exact:true})).toBeDisabled();await page.getByLabel('Champ factuel à compléter',{exact:true}).selectOption('dataSubjects');await page.getByLabel('Auteur déclaré de la relecture',{exact:true}).fill('DPO fictif');await page.getByLabel('J’ai relu le champ avant et après').check();await page.getByRole('button',{name:'Reprendre ce fait dans la fiche',exact:true}).click();await openSaved(page);await expect(page.locator('.request-record')).toContainText('Reprise dans « Personnes concernées »');await page.getByRole('button',{name:'Registre',exact:true}).click();await page.getByRole('button',{name:/^Lire Recrutement/}).click();await expect(page.getByRole('article',{name:'Lecture de l’activité'})).toContainText('Candidats fictifs contactés par notre équipe');
});
test('request preparation survives a lock as encrypted input with confirmation reset',async({page})=>{
 test.setTimeout(90000);const phrase='Fictional request recovery phrase 2026 correct';await page.goto('/app/privacy/');await expect(page.locator('[data-rgpdesk-ready="true"]')).toBeVisible();await page.getByLabel('Nom de l’organisme',{exact:true}).fill('Fictif');await page.getByLabel('Nouvelle phrase secrète',{exact:true}).fill(phrase);await page.getByLabel('Confirmer la phrase secrète',{exact:true}).fill(phrase);await page.getByLabel('Je comprends qu’une phrase perdue').check();await page.getByRole('button',{name:'Créer le coffre chiffré',exact:true}).click();await requests(page);await page.locator('.request-brief>summary').click();await page.getByLabel('Destinataire de la demande',{exact:true}).fill('SECRET_REQUEST_RECIPIENT');await page.locator('.request-brief .choices input').first().check();await page.getByRole('button',{name:'Relire la demande (1)',exact:true}).click();await page.getByLabel('J’ai relu les questions').check();await expect(page.locator('.recovery-status')).toContainText('Brouillon chiffré protégé');await page.getByRole('button',{name:'Verrouiller le coffre',exact:true}).click();await expect(page.locator('body')).not.toContainText('SECRET_REQUEST_RECIPIENT');await page.getByRole('button',{name:'Ouvrir le coffre 1',exact:true}).click();await page.getByLabel('Phrase secrète du coffre',{exact:true}).fill(phrase);await page.getByRole('button',{name:'Déverrouiller',exact:true}).click();await page.getByRole('button',{name:'Reprendre ce brouillon',exact:true}).click();await expect(page.getByLabel('Destinataire de la demande',{exact:true})).toHaveValue('SECRET_REQUEST_RECIPIENT');await page.getByRole('button',{name:'Relire la demande (1)',exact:true}).click();await expect(page.getByLabel('J’ai relu les questions')).not.toBeChecked();
});
test('recognize a local file and reuse its reference across several explicit arguments',async({page})=>{
 await page.goto('/app/privacy/#demo/documents');await page.getByRole('button',{name:'Ajouter une référence',exact:true}).click();await page.getByLabel('Titre interne',{exact:true}).fill('Pièce de test fictive');await page.getByLabel('Périmètre de la référence',{exact:true}).fill('Exercice');await page.getByLabel('Version déclarée',{exact:true}).fill('1');await page.locator('.document-filing>summary').click();const file={name:'fictif.txt',mimeType:'text/plain',buffer:Buffer.from('Purely fictional local bytes')};await page.locator('.fingerprint input[type=file]').setInputFiles(file);await page.getByRole('button',{name:'Conserver cette empreinte',exact:true}).click();await page.getByRole('button',{name:'Enregistrer la référence',exact:true}).click();await page.getByRole('button',{name:'Ajouter une référence',exact:true}).click();await page.getByLabel('Version déclarée',{exact:true}).fill('Autre');await page.locator('.document-filing>summary').click();await page.locator('.fingerprint input[type=file]').setInputFiles(file);await expect(page.locator('.fingerprint')).toContainText('Cette pièce est déjà référencée');await page.getByRole('button',{name:'Réutiliser Pièce de test fictive',exact:true}).click();await page.getByRole('button',{name:'Quitter sans enregistrer',exact:true}).click();await expect(page.getByLabel('Titre interne',{exact:true})).toHaveValue('Pièce de test fictive');await page.getByRole('button',{name:'Citer Pièce de test fictive',exact:true}).click();const linker=page.locator('.evidence-linker');await linker.getByLabel('Filtrer les questions par activité',{exact:true}).selectOption({label:'Recrutement · exemple fictif'});await linker.locator('.choices input').first().check();await linker.locator('.choices input').nth(1).check();await linker.getByLabel('Passage à retrouver',{exact:true}).fill('p. 2');await linker.getByLabel('Ce que ce passage permet d’établir',{exact:true}).fill('Fait fictif à examiner');await linker.getByLabel('J’ai relu ces liens').check();await linker.getByRole('button',{name:'Relier cette preuve aux questions',exact:true}).click();await expect(linker).toHaveCount(0);await page.getByRole('button',{name:'Examiner Pièce de test fictive',exact:true}).click();await expect(page.getByRole('group',{name:'Activités couvertes',exact:true}).getByLabel(/Recrutement/)).toBeChecked();
});
test('preview linked consequences before saving, and retain input when staying',async({page})=>{
 await page.goto('/app/privacy/#demo/systemes');await page.getByRole('button',{name:/^Modifier /}).first().click();await page.getByLabel('Nom du système',{exact:true}).fill('Outil renommé pour exercice');const preview=page.getByRole('complementary',{name:'Portée de la modification'});await expect(preview).toContainText('Ce changement sera partagé');await preview.locator('summary').click();await preview.getByRole('button',{name:'Voir l’activité',exact:true}).first().click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Reprendre ma saisie',exact:true}).click();await expect(page.getByLabel('Nom du système',{exact:true})).toHaveValue('Outil renommé pour exercice');for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1100});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
});
test('compare two actual frozen deliveries and clear the comparison when leaving',async({page})=>{
 await page.goto('/app/privacy/#demo/partager');for(const recipient of ['Direction fictive A','Direction fictive B']){await page.getByRole('button',{name:'Charger la sélection d’exemple',exact:true}).click();await page.getByLabel('Destinataire déclaré',{exact:true}).fill(recipient);await page.getByRole('button',{name:'Prévisualiser le dossier',exact:true}).click();await page.getByLabel('J’ai relu ce contenu en clair').check();await page.getByRole('button',{name:'Confirmer et télécharger le dossier',exact:true}).click();await expect(page.getByRole('button',{name:'Prévisualiser le dossier',exact:true})).toBeVisible();}
 await page.locator('.delivery-comparison>summary').click();await page.getByLabel('Premier dossier',{exact:true}).selectOption({index:1});await page.getByLabel('Second dossier',{exact:true}).selectOption({index:2});await page.getByRole('button',{name:'Comparer les contenus remis',exact:true}).click();const diff=page.getByRole('region',{name:'Différences entre les dossiers'});await expect(diff).toContainText('Direction fictive A');await expect(diff).toContainText('Direction fictive B');await expect(diff).toContainText('Le destinataire, le profil ou le périmètre diffère');await expect(diff).not.toContainText('EXERCICE / référence');await page.getByRole('button',{name:'Retrouver mes coffres',exact:true}).click();await expect(diff).toHaveCount(0);
});
