import { test, expect } from "@playwright/test";

const phrase = "Fictional AIPD browser phrase 2026 correct";
const marker = 'PRIVATE_PIA_<img src=x onerror="alert(1)">';
test("AIPD stays local, saves a reasoned review, reopens and preserves its former context", async ({ page, context }) => {
  test.setTimeout(90_000);
  const requests: string[] = [], logs: string[] = [];
  page.on("console", (event) => logs.push(event.text()));
  await page.goto("/app/privacy/");
  await expect(page.locator('[data-rgpdesk-ready="true"]')).toBeVisible();
  await page.waitForLoadState("networkidle");
  page.on("request", (request) => requests.push(request.url()));
  await context.setOffline(true);
  await page.getByLabel("Nom de l’organisme", { exact: true }).fill("Étude fictive AIPD");
  await page.getByLabel("Nouvelle phrase secrète", { exact: true }).fill(phrase);
  await page.getByLabel("Confirmer la phrase secrète", { exact: true }).fill(phrase);
  await page.getByLabel("Je comprends qu’une phrase perdue").check();
  await page.getByRole("button", { name: "Créer le coffre chiffré", exact: true }).click();
  await page.getByRole("button", { name: "Registre", exact: true }).click();
  await page.getByRole("button", { name: "Ajouter une activité responsable", exact: true }).click();
  await page.getByLabel("Nom de l’activité", { exact: true }).fill("Recrutement fictif avant revue");
  await page.getByRole("button", { name: "Enregistrer la fiche", exact: true }).click();
  await page.getByRole("button", { name: "AIPD / PIA", exact: true }).click();
  await page.getByRole("button", { name: "Ouvrir une étude d’impact", exact: true }).click();
  const atelier = page.getByRole("region", { name: "Atelier AIPD", exact: true });
  await expect(atelier.getByLabel("Position sur la réalisation de l’AIPD")).toHaveValue("unknown");
  await atelier.getByLabel("Champ applicable, cas légaux et listes examinées", { exact: true }).fill(marker);
  await page.getByRole("button", { name: "Registre", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Avant de changer de rubrique" })).toBeVisible();
  await page.getByRole("button", { name: "Reprendre ma saisie", exact: true }).click();
  await expect(atelier.getByLabel("Champ applicable, cas légaux et listes examinées", { exact: true })).toHaveValue(marker);
  await atelier.getByRole("button", { name: "Enregistrer l’étude", exact: true }).click();
  await expect(atelier.getByText("Étude enregistrée dans le coffre", { exact: true })).toBeVisible();
  await atelier.getByRole("button", { name: /Risques humains/ }).click();
  await atelier.getByRole("button", { name: "Décrire un scénario de risque", exact: true }).click();
  await atelier.getByLabel("Scénario 1 · Nom", { exact: true }).fill("Exclusion fictive à examiner");
  await expect(atelier.getByRole("combobox", { name: "R1 · Gravité initiale", exact: true })).toHaveValue("unknown");
  await atelier.getByLabel("R1 · Droits et libertés affectés", { exact: true }).fill(marker);
  await atelier.getByRole("button", { name: "Retirer le scénario R1", exact: true }).click();
  await atelier.getByLabel("Échelles, hypothèses et méthode d’appréciation", { exact: true }).fill("Méthode fictive modifiée après retrait");
  await atelier.getByRole("button", { name: "Annuler le dernier retrait", exact: true }).click();
  await expect(atelier.getByLabel("R1 · Droits et libertés affectés", { exact: true })).toHaveValue(marker);
  await expect(atelier.getByLabel("Échelles, hypothèses et méthode d’appréciation", { exact: true })).toHaveValue("Méthode fictive modifiée après retrait");
  await atelier.getByRole("button", { name: "Enregistrer l’étude", exact: true }).click();
  await expect(atelier.getByText("Étude enregistrée dans le coffre", { exact: true })).toBeVisible();
  await atelier.getByRole("button", { name: /Avis & décision/ }).click();
  // Native option.disabled is the guard; the generic enabled matcher follows the select.
  await expect(atelier.getByRole("combobox", { name: "Position à consigner", exact: true }).locator('option[value="proceed"]')).toHaveJSProperty("disabled", true);
  await atelier.getByLabel("Auteur déclaré de la décision", { exact: true }).fill("Relecteur fictif");
  await atelier.getByLabel("Motifs et réserves de la décision", { exact: true }).fill("Vérifier les effets du projet avant toute décision.");
  await atelier.getByLabel("J’ai relu le dossier et je consigne une décision humaine, avec ses réserves.").check();
  await atelier.getByRole("button", { name: "Enregistrer la revue humaine", exact: true }).click();
  await expect(atelier.getByRole("article", { name: "Dossier AIPD en lecture" })).toBeVisible();
  await expect(atelier.getByRole("article").getByText(marker, { exact: true }).first()).toBeVisible();
  await expect(atelier.locator('img[src="x"]')).toHaveCount(0);
  await atelier.getByRole("button", { name: "Fermer l’étude", exact: true }).click();
  await page.getByRole("button", { name: "Registre", exact: true }).click();
  await page.getByRole("button", { name: "Modifier Recrutement fictif avant revue", exact: true }).click();
  await page.getByLabel("Nom de l’activité", { exact: true }).fill("Recrutement fictif après revue");
  await page.getByRole("button", { name: "Enregistrer la fiche", exact: true }).click();
  await page.getByRole("button", { name: "AIPD / PIA", exact: true }).click();
  await expect(page.getByText(/Contexte ou étude modifié depuis la dernière revue/)).toBeVisible();
  await page.getByRole("button", { name: "Lire le dossier", exact: true }).click();
  await atelier.getByLabel("Version du dossier").selectOption("0");
  await expect(atelier.getByRole("article").getByRole("heading", { name: "Recrutement fictif avant revue", exact: true })).toBeVisible();
  await atelier.getByRole("button", { name: "Fermer l’étude", exact: true }).click();
  await page.getByRole("button", { name: "Sauvegarde", exact: true }).click();
  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: "Télécharger la sauvegarde chiffrée", exact: true }).click();
  expect((await download).suggestedFilename()).toBe("rgpdesk-sauvegarde.rgpdesk");
  await page.getByRole("button", { name: "Verrouiller le coffre", exact: true }).click();
  await expect(page.getByText(marker, { exact: true })).toHaveCount(0);
  expect(requests).toEqual([]); expect(logs.join("\n")).not.toContain("PRIVATE_PIA_");
  expect(new URL(page.url()).search + new URL(page.url()).hash).toBe("");
  await context.setOffline(false);
  await page.reload();
  await page.getByRole("button", { name: "Ouvrir le coffre 1", exact: true }).click();
  await page.getByLabel("Phrase secrète du coffre", { exact: true }).fill(phrase);
  await page.getByRole("button", { name: "Déverrouiller", exact: true }).click();
  await page.getByRole("button", { name: "AIPD / PIA", exact: true }).click();
  await page.getByRole("button", { name: "Lire le dossier", exact: true }).click();
  await atelier.getByLabel("Version du dossier").selectOption("0");
  await expect(atelier.locator(".pia-history").getByText("Vérifier les effets du projet avant toute décision.", { exact: true })).toBeVisible();
  await expect(atelier.getByRole("article").getByRole("heading", { name: "Recrutement fictif avant revue", exact: true })).toBeVisible();
});
