import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const phrase='Fictional recovery phrase 2026 correct';
async function create(page:Page){await page.goto('/app/privacy/');await expect(page.locator('[data-rgpdesk-ready="true"]')).toBeVisible();await page.getByLabel('Nom de l’organisme',{exact:true}).fill('RECOVERY_FICTIF');await page.getByLabel('Nouvelle phrase secrète',{exact:true}).fill(phrase);await page.getByLabel('Confirmer la phrase secrète',{exact:true}).fill(phrase);await page.getByLabel('Je comprends qu’une phrase perdue').check();await page.getByRole('button',{name:'Créer le coffre chiffré',exact:true}).click();await expect(page.getByRole('button',{name:'Verrouiller le coffre',exact:true})).toBeVisible();}
async function unlock(page:Page){await page.getByRole('button',{name:'Ouvrir le coffre 1',exact:true}).click();await page.getByLabel('Phrase secrète du coffre',{exact:true}).fill(phrase);await page.getByRole('button',{name:'Déverrouiller',exact:true}).click();}
async function protectedCopy(page:Page){await expect(page.locator('.recovery-status')).toContainText('Brouillon chiffré protégé');}
async function raw(page:Page){return page.evaluate(()=>new Promise<string>((resolve,reject)=>{const r=indexedDB.open('rgpdesk-vault-v1');r.onerror=()=>reject(new Error('DB'));r.onsuccess=()=>{const db=r.result,tx=db.transaction(['records','drafts'],'readonly'),a=tx.objectStore('records').getAll(),b=tx.objectStore('drafts').getAll();tx.oncomplete=()=>{resolve(JSON.stringify({records:a.result,drafts:b.result}));db.close();};};}));}

test('read an activity, edit the relevant section and review a selected request',async({page})=>{
 await page.goto('/app/privacy/#demo/registre');await page.getByRole('button',{name:/^Lire Recrutement/}).click();const reader=page.getByRole('article',{name:'Lecture de l’activité'});await expect(reader).toBeVisible();await expect(reader.locator('input,textarea')).toHaveCount(0);await expect(reader).toContainText('Le parcours des données');await reader.getByRole('button',{name:'Modifier les données',exact:true}).click();await expect(page.getByLabel('Catégories de personnes',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Annuler l’édition',exact:true}).click();
 await page.getByRole('button',{name:'Actions & décisions',exact:true}).click();await page.getByRole('button',{name:/Demandes aux métiers/}).click();await page.locator('.request-brief>summary').click();await page.getByLabel('Destinataire de la demande',{exact:true}).fill('RH fictif');await expect(page.locator('.request-brief input:checked')).toHaveCount(0);await page.locator('.request-brief .choices input').first().check();await page.getByRole('button',{name:'Relire la demande (1)',exact:true}).click();await expect(page.getByRole('button',{name:'Télécharger la demande',exact:true})).toBeDisabled();await page.getByLabel('J’ai relu les questions').check();const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Télécharger la demande',exact:true}).click();const text=await readFile((await (await dl).path())!,'utf8');expect(text).toContain('RH fictif');expect(text).not.toMatch(/EXERCICE \/ référence|NOTE INTERNE/);
});
test('the graphic preview renders the selected report safely and is cleared on exit',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/app/privacy/#demo/partager');await page.getByRole('button',{name:'Charger la sélection d’exemple',exact:true}).click();await page.getByLabel('Destinataire déclaré',{exact:true}).fill('<img src="https://invalid.example/canary" onerror="alert(1)">');await page.getByRole('button',{name:'Prévisualiser le dossier',exact:true}).click();const report=page.getByLabel('Aperçu du rapport à remettre',{exact:true});await expect(report.locator('h1')).toContainText('Maison Sillage');await expect(report).toContainText('<img src=');await expect(report.locator('img,script,iframe')).toHaveCount(0);await expect(report.locator('.activity')).toHaveCount(3);for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}await page.getByRole('button',{name:'Retrouver mes coffres',exact:true}).click();await expect(page.locator('.report-preview')).toHaveCount(0);expect(errors).toEqual([]);
});
test('an incomplete activity survives lock and reload, stays encrypted, then is consumed by explicit save',async({page})=>{
 test.setTimeout(90000);await create(page);await page.getByRole('button',{name:'Registre',exact:true}).click();await page.getByRole('button',{name:'Ajouter une activité responsable',exact:true}).click();await page.getByLabel('Nom de l’activité',{exact:true}).fill('DRAFT_PRIVATE_CANARY');await protectedCopy(page);let storage=await raw(page);expect(storage).not.toContain('DRAFT_PRIVATE_CANARY');expect(JSON.parse(storage).drafts).toHaveLength(1);expect(JSON.parse(storage).records[0].revision).toBe(1);
 await page.getByRole('button',{name:'Verrouiller le coffre',exact:true}).click();await expect(page.locator('body')).not.toContainText('DRAFT_PRIVATE_CANARY');await page.reload();await unlock(page);await expect(page.getByRole('complementary',{name:'Saisies à reprendre'})).toContainText('DRAFT_PRIVATE_CANARY');await page.getByRole('button',{name:'Reprendre ce brouillon',exact:true}).click();await expect(page.getByLabel('Nom de l’activité',{exact:true})).toHaveValue('DRAFT_PRIVATE_CANARY');await page.getByRole('button',{name:'Enregistrer la fiche',exact:true}).click();await expect(page.getByRole('button',{name:'Lire DRAFT_PRIVATE_CANARY',exact:true})).toBeVisible();storage=await raw(page);expect(JSON.parse(storage).drafts).toHaveLength(0);expect(JSON.parse(storage).records[0].revision).toBe(2);
});
test('document recovery preserves text but requires a fresh review confirmation',async({page})=>{
 test.setTimeout(90000);await create(page);await page.getByRole('button',{name:'Documents',exact:true}).click();await page.getByRole('button',{name:'Ajouter une référence',exact:true}).click();await page.getByLabel('Titre interne',{exact:true}).fill('REFERENCE_RECUPERABLE');await page.getByLabel('Périmètre de la référence',{exact:true}).fill('Fictif');await page.getByLabel('Je déclare avoir examiné cette référence').check();await protectedCopy(page);await page.getByRole('button',{name:'Verrouiller le coffre',exact:true}).click();await unlock(page);await page.getByRole('button',{name:'Reprendre ce brouillon',exact:true}).click();await expect(page.getByLabel('Titre interne',{exact:true})).toHaveValue('REFERENCE_RECUPERABLE');await expect(page.getByLabel('Je déclare avoir examiné cette référence')).not.toBeChecked();await page.getByRole('button',{name:'Annuler la référence',exact:true}).click();await expect.poll(async()=>JSON.parse(await raw(page)).drafts.length).toBe(0);
});
test('stale recovery cannot overwrite a dossier saved in another tab',async({page,context})=>{
 test.setTimeout(90000);await create(page);const second=await context.newPage();await second.goto('/app/privacy/');await unlock(second);await page.getByRole('button',{name:'Registre',exact:true}).click();await page.getByRole('button',{name:'Ajouter une activité responsable',exact:true}).click();await page.getByLabel('Nom de l’activité',{exact:true}).fill('OLD_DRAFT');await protectedCopy(page);await second.getByRole('button',{name:'Organisation',exact:true}).click();await second.getByLabel('Nom de l’organisme',{exact:true}).fill('NEW_SAVED_ORG');await second.getByRole('button',{name:'Enregistrer l’organisation',exact:true}).click();await expect(second.getByRole('status').filter({hasText:'Enregistré dans le coffre'})).toBeVisible();await page.getByRole('button',{name:'Verrouiller le coffre',exact:true}).click();await unlock(page);await expect(page.getByRole('button',{name:'Reprendre ce brouillon',exact:true})).toBeDisabled();await expect(page.locator('.recovery-shelf')).toContainText('Le dossier a changé');await expect(page.locator('.sidebar-caption')).toContainText('NEW_SAVED_ORG');
});


test('a recovered edit remains unsaved and survives another lock until explicitly discarded',async({page})=>{
 test.setTimeout(90000);await create(page);await page.getByRole('button',{name:'Registre',exact:true}).click();await page.getByRole('button',{name:'Ajouter une activité responsable',exact:true}).click();await page.getByLabel('Nom de l’activité',{exact:true}).fill('INITIAL_SAVED');await page.getByRole('button',{name:'Enregistrer la fiche',exact:true}).click();await page.getByRole('button',{name:'Modifier INITIAL_SAVED',exact:true}).click();await page.getByLabel('Nom de l’activité',{exact:true}).fill('RECOVERED_EDIT');await protectedCopy(page);
 for(let n=0;n<2;n++){await page.getByRole('button',{name:'Verrouiller le coffre',exact:true}).click();await unlock(page);await page.getByRole('button',{name:'Reprendre ce brouillon',exact:true}).click();await expect(page.getByLabel('Nom de l’activité',{exact:true})).toHaveValue('RECOVERED_EDIT');await protectedCopy(page);expect(JSON.parse(await raw(page)).drafts).toHaveLength(1);}
 await page.getByRole('button',{name:'Ma mission',exact:true}).click();await page.getByRole('button',{name:'Quitter sans enregistrer',exact:true}).click();await page.getByRole('button',{name:'Registre',exact:true}).click();await expect(page.getByRole('button',{name:'Lire INITIAL_SAVED',exact:true})).toBeVisible();expect(JSON.parse(await raw(page)).drafts).toHaveLength(0);
});


test('pending AIPD review is recovered as input without confirming or changing the saved study',async({page})=>{
 test.setTimeout(90000);await create(page);await page.getByRole('button',{name:'Registre',exact:true}).click();await page.getByRole('button',{name:'Ajouter une activité responsable',exact:true}).click();await page.getByLabel('Nom de l’activité',{exact:true}).fill('Étude fictive de reprise');await page.getByRole('button',{name:'Enregistrer la fiche',exact:true}).click();await expect(page.getByRole('button',{name:'Lire Étude fictive de reprise',exact:true})).toBeVisible();await page.getByRole('button',{name:'AIPD / PIA',exact:true}).click();await page.getByRole('button',{name:'Ouvrir une étude d’impact',exact:true}).click();await page.getByRole('button',{name:'Enregistrer l’étude',exact:true}).click();await expect(page.getByText('Étude enregistrée dans le coffre',{exact:true})).toBeVisible();const before=JSON.parse(await raw(page)).records;
 await page.getByRole('button',{name:/Avis & décision/}).click();await page.getByLabel('Auteur déclaré de la décision',{exact:true}).fill('DPO fictif');await page.getByLabel('Motifs et réserves de la décision',{exact:true}).fill('À relire avant décision.');await page.getByLabel('J’ai relu le dossier et je consigne une décision humaine, avec ses réserves.').check();await protectedCopy(page);await page.getByRole('button',{name:'Verrouiller le coffre',exact:true}).click();await unlock(page);await page.getByRole('button',{name:'Reprendre ce brouillon',exact:true}).click();await expect(page.getByLabel('Motifs et réserves de la décision',{exact:true})).toHaveValue('À relire avant décision.');await expect(page.getByLabel('J’ai relu le dossier et je consigne une décision humaine, avec ses réserves.')).not.toBeChecked();expect(JSON.parse(await raw(page)).records).toEqual(before);
});

test('a pending DPO event survives interruption without becoming a recorded event',async({page})=>{
 test.setTimeout(90000);await create(page);await page.getByRole('button',{name:'Dossiers DPO',exact:true}).click();await page.getByRole('button',{name:'Demandes de droits',exact:true}).click();await page.getByRole('button',{name:'Ouvrir un dossier',exact:true}).click();await page.getByLabel('Titre du dossier',{exact:true}).fill('Dossier fictif de reprise');await page.getByRole('button',{name:'Enregistrer le dossier',exact:true}).click();await expect(page.getByText('Dossier enregistré',{exact:true})).toBeVisible();const before=JSON.parse(await raw(page)).records;
 await page.getByRole('button',{name:'03 Chronologie',exact:true}).click();await page.getByLabel('Auteur déclaré de l’événement',{exact:true}).fill('DPO fictif');await page.getByLabel('Événement ou complément',{exact:true}).fill('Projet de réponse, non envoyé.');await protectedCopy(page);await page.getByRole('button',{name:'Verrouiller le coffre',exact:true}).click();await unlock(page);await page.getByRole('button',{name:'Reprendre ce brouillon',exact:true}).click();await expect(page.getByLabel('Événement ou complément',{exact:true})).toHaveValue('Projet de réponse, non envoyé.');await expect(page.locator('.dpo-timeline li')).toHaveCount(0);expect(JSON.parse(await raw(page)).records).toEqual(before);
});
